### ISSUE TITLE
Prompt for multi-turn suggestion intent 

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Let's say we have a hosting frame F with a slot a, on which we have a suggestion intent as VR source, the suggestion intent need more than one turn, how does the prompt work?

1. First turn: prompt on F.a, skip prompt from suggestion, and keep all inform related message (VR). 
2. Second turn: skip the prompt on F.a, keep the prompt from suggestion, and keep the inform
3. Last turn (when suggestion is on response): keep the prompt on F.a, keep the response from suggestion as inform.

### Motivation

The main consideration is less redundancy.

### Describe alternatives you've considered

stop gap, we will have more discussion for the further improvement after this is done.

**Comment by yigexu** [comment]
补充：将 suggestion intent 第一个被bot问出来的 slot 叫做 b，这种方案总是假设 **b is-A a**, regardless b 的交互是什么。

**Comment by XiaoboYuan** [comment]
@yigexu @xiaoyunwu fixed

**Comment by yigexu** [comment]
checked.
