### ISSUE TITLE
[Bug]: Frame level VR doesn't meet expectations

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在[t_VR_FrameLevel](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8e0171eb6ab6d0e8cc/intent)中，Frame level VR的表现如下：

1. 当Frame的slot均为always ask时，能正常输出VR
2. 当Frame的slot均为user mentioned时，如果intent - slot：frame为
      1. Single value(SV)时，会跳过填槽，直接输出intent的response 
      2. Multi value(MV)时，会输出VR
      
- 附截图
- 1和2-ii对话截图
![image](https://user-images.githubusercontent.com/95261974/158330340-753b4f8b-f313-45b5-a63a-c587e93c7c36.png)

- 2-i 对话截图
![image](https://user-images.githubusercontent.com/95261974/158330030-f8f61f66-57b6-495c-8897-2d08b23bd24f.png)

### Expected Behavior

2-ii情况下，不应该输出VR？

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8e0171eb6ab6d0e8cc/test_case

**Comment by hisunnymay** [comment]
@yigexu 我不确定Expected Behavior是什么，如果不对的话，你可以改一下

**Comment by yigexu** [comment]
@hisunnymay 
你试试在 host frame 的 frame slot 上增加 vr，能问出来吗？

**Comment by hisunnymay** [comment]
@yigexu num_1,num_2是user mentioned就问不出来，但是设置为always ask就可以，对话详见：[Test Cases - ThirdIntent - user mentioned](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8e0171eb6ab6d0e8cc/test_case)

**Comment by yigexu** [comment]
（让我们把nested情况的两个frame叫做 host frame 和 inner frame）

对于frame-level VR有两种情况：
1. 如果在 host frame 的 frame slot 上增加 vr，ask strategy 应该跟随 host frame 的 frame slot
2. 如果在 inner frame 上增加 frame level annotation，问不问取决于
    2.1 hosting frame 上 frame slot 的 strategy
    2.2 inner 内部 slot 的 strategy
如果没有其他的case/原因/限制，感觉可以先按 2.1 来。

potential alternative是还有：
如果 2.2 任意 slot 存在 always ask，就输出 frame level vr；
如果 2.1 和 2.2 任意 slot 存在 always ask，就输出 frame level vr；

@xiaoyunwu

**Comment by xiaoyunwu** [comment]
@xiaobo, can you take a look first? I think you might have something to say
from consistency point of view.

**Comment by XiaoboYuan** [comment]
@yigexu @xiaoyunwu 
我觉得是否输出应该取决于ask strategy表达的要不要进入该frame，如果frame slot是UserMention，那么即使inner frame有always ask我觉得也不应该进入，inner frame的slot ask strategy是控制进入以后的行为的
所以我觉得应该是按照2.1

@hisunnymay 
2.ii情况有测试intent吗？目前四个intent都不符合
BTW，改了struct的ask strategy怎么反应在en中，我尝试了，但是没反应

**Comment by hisunnymay** [comment]
@XiaoboYuan [No1_Intent](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8d0171eb6ab6d0e8c9/intent/622ffd7a0171eb6ab6d0e8d8)对应的2.ii

目前lang-agent的传递好像有问题，详见https://github.com/framely/community/issues/109

**Comment by XiaoboYuan** [comment]
@hisunnymay 
这里目前符合我的预期
这里的testFrame是一个always ask的mv，这是需要进入的，进入这个slot后第一个问题是问user要不要一个testFrame，这时候按照需求就要同时展示Value Rec
这里目前prompt是“which Frame do you want to view?”，所以连起来会有点奇怪
我对这里prompt的预期是
"do you want to have one TestFrame? we have: 1. 2. 3..."

**Comment by hisunnymay** [comment]
如果2.ii的表现是符合预期的，那么2.i的表现可能不符合预期

2.i中的testFrame是一个always ask的sv，DU没有进入这个slot，直接输出了[No2_Intent](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8e0171eb6ab6d0e8cc/intent/62301f050171eb6ab6d1e7a3)的response

输入”test2“可以测试，也可以看[Test cases - Single value - user mentioned](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622ffc8e0171eb6ab6d0e8cc/test_case)

**Comment by XiaoboYuan** [comment]
@hisunnymay 
2.i的情况我现在感觉也符合预期
现在我们把VR认为是一种辅助信息，在有一些主要信息(slot)需要ask user的时候才会出现

2.i的这种情况可以认为在user没有提及的情况下builder不想询问user什么问题，所以VR不出现我觉得也正常
2.ii的这种情况可以认为builder想询问user要不要以及要几个，但是具体要什么在未提及的情况下不想询问user
现在VR出现在2.ii中是一种特殊处理，是因为需求想要在询问"要不要以及要几个"的时候就有VR的信息，如果没有这个需求,2.ii是可以去掉VR的,但是还是会问"do you want to have a TestFrame?", 这个是主要信息

简单点说就是2.i什么都不问信息也是完整的，2.ii什么都不问的话缺了user需要几个TestFrame这个信息，信息不完整

现在这里有两个维度的决定
1. 要不要把VR作为一个主要信息，也就是说设置了VR的地方必须经过VR才能继续 -- 这个决定了2.i会不会有VR
2. 要不要在mv slot的hasmore这里显示VR信息 --- 这个决定了2.ii会不会有VR

目前我觉得在这两个问题上的决定都还是比较合理的，这个可以再讨论

另外2.i中host frame always ask但是inner frame user mention的情况在现有的context下似乎没什么意义

**Comment by hisunnymay** [comment]
@XiaoboYuan 用implement frame的方法试了一下，inner frame always ask也能实现想要的功能，所以目前没有inner frame user mention的use case，就先close这个issue了
