### ISSUE TITLE
[Bug]: Incompatible composite type generated in PostgreSQL database

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 provider [foodOrderingProvider](https://build.opencui.io/org/me.restaurant/agent/foodOrderingProvider/struct/service_schema) 中有一个 function 是：placeOrder_origin。
该 function 有一个传入参数的类型是 me.restaurant.foodOrdering.IDish。
IDish frame 中包含一个多值的 slot：options，类型是：Options[]

目前 IDish 对应在 PostgreSQL 中生成的 composite type 中的 options 是 **text** 和多值的Options[] 不匹配，导致执行 postgresql function 的时候有报错："_cannot subscript type text because it is not an array_"

![68ce6d5c-8b52-4910-a8c7-cc7e25270ec6](https://github.com/framely/community/assets/95261974/2adcf2c0-f0a4-447c-8c64-4e82a76d9395)

### Expected Behavior

期望 IDish 对应在 PostgreSQL 中生成的 composite type 中的 options 是 **text[]**

### Use Case

在 [FoodOrdering API](https://naturali-io.feishu.cn/docx/Ulh5dDBwhoKGDGxtKaAcZdfPnWe) 中，一个 dish 可以有多个 options，比如：size, toppings, flavor 等，所以 options 的类型是多值。

### Steps To Reproduce

1. 进入 provider [foodOrderingProvider](https://build.opencui.io/org/me.restaurant/agent/foodOrderingProvider/struct/service_schema)
2. 点击 Debug，选择最后一个 function: **placeOrder_origin**
3. 在 dishes_param 那栏输入
```
[{
    "category": "Pizzas",
    "name":"GreekPizza",
    "options": ["Bacon"],
    "quantity": 1
},{
    "category": "Sandwiches",
    "name":"FishSandwich",
    "options": [""],
    "quantity": 2
}]
```
4. 在 totalAmount_param 那栏输入 `3400`
5. 点击 **Execute** 可以看到报错

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.restaurant/agent/foodOrderingProvider/struct/type?page=0&imported=false&search=&category=ALL

**Comment by HuiCheng** [comment]
你可不可以先做个实验，把这个列的类型改成json，看看是不是可以满足你的需求。

**Comment by hisunnymay** [comment]
> 你可不可以先做个实验，把这个列的类型改成json，看看是不是可以满足你的需求。

@HuiCheng 你的意思是在 pgAdmin 里面修改吗？目前平台上好像改不了

**Comment by HuiCheng** [comment]
> > 你可不可以先做个实验，把这个列的类型改成json，看看是不是可以满足你的需求。
> 
> @HuiCheng 你的意思是在 pgAdmin 里面修改吗？目前平台上好像改不了

是的 在pgAdmin里修改

**Comment by hisunnymay** [comment]
好的，我试试

**Comment by hisunnymay** [comment]
@HuiCheng 改成 json 了，报错变成了：_cannot subscript type json because it is not an array_

![1srxj6Vfdx](https://github.com/framely/community/assets/95261974/3f09d84f-3101-4b95-bc49-b3de0a13a7bd)

**Comment by HuiCheng** [comment]
> 

这个错误是哪报的 func?
函数内容是什么？

**Comment by hisunnymay** [comment]
在 provider [foodOrderingProvider](https://build.opencui.io/org/me.restaurant/agent/foodOrderingProvider/struct/service_schema) 中有一个 function 是：placeOrder_origin。

函数内容是：
```
BEGIN
    -- Add a new order into Order
    INSERT INTO "Orders"("orderStatus", "totalAmount")
    VALUES('unpaid', "totalAmount_param")
    RETURNING "Orders".id INTO value;
    
    -- Insert dishes into OrderItem
    FOR i IN 1 .. array_upper("dishes_param", 1) LOOP
        INSERT INTO "OrderItems"("orderId", "category", "dishName", "optionName", "quantity")
        VALUES(value, "dishes_param"[i]."category", "dishes_param"[i]."name", "dishes_param"[i].options[0], "dishes_param"[i]."quantity");
    END LOOP;
   
    -- Return orderId
    RETURN NEXT;
END
```

**Comment by HuiCheng** [comment]
options[0] 操作是array
options->0 操作是json

**Comment by hisunnymay** [comment]
Checked, it's fixed.
