### ISSUE TITLE
[Bug]: Failed to add annotations for imported slots 

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 [foodOrdering](https://build.opencui.io/org/me.restaurant/agent/foodOrdering/struct/frame/6465987d1ca4cd155a1de518/slot/646598881ca4cd155a1de51b?tab=annotation) service 中为 IDish.category 开启了 value rec 开关

![image](https://github.com/framely/community/assets/95261974/86421e8f-ce6e-45e2-974a-4477b1b5a55f)

但在 [foodOrderingModule](https://build.opencui.io/org/me.restaurant/agent/foodOrderingModule/struct/frame/646c057bdb68271db6f714c3/slot/646598881ca4cd155a1de51b?super_id=6465987d1ca4cd155a1de518&tab=annotation) 中，implement IDish 的 frame Dish 的 category 无法添加 value rec annotation

![image](https://github.com/framely/community/assets/95261974/6a1ce19c-a4fa-49fd-97ce-2c3d6c1038ec)

### Expected Behavior

根据 " _annotaion开关要在原module中开启，在能在imported的时候添加annotation数据_ "，期望是基于上述描述， Dish 的 category 可以添加 value rec annotation (其他开启了开关的 annotation 同理)

### Use Case

/

### Steps To Reproduce

1. 点击进入 FoodOrderingModule 的 [Dish.category ](https://build.opencui.io/org/me.restaurant/agent/foodOrderingModule/struct/frame/646c057bdb68271db6f714c3/slot/646598881ca4cd155a1de51b?super_id=6465987d1ca4cd155a1de518&tab=annotation) 即可看到 annotation 无法添加
2. 或者可以自己创建两个 module，
   - 在 module A 中创建 interface frame，添加 slot，并开启 annotation
   - 在 module B 中创建 concrete frame, implement module A 中的 interface frame，可以看到对应 slot 无法添加 annotation
  

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.restaurant/agent/foodOrderingModule/struct/frame/646c057bdb68271db6f714c3/slot/646598881ca4cd155a1de51b?super_id=6465987d1ca4cd155a1de518&tab=annotation

**Comment by hisunnymay** [comment]
Checked, it's fixed.

![Uploading image.png…]()

**Comment by hisunnymay** [comment]
@jfang137 哈喽，在开启  initialization  开关的情况下，目前还是无法为 imported slot 添加  initialization annotation

![image](https://github.com/framely/community/assets/95261974/7ecc7a73-10bd-49c9-a29a-6ece06c02d3b)

**Comment by jfang137** [comment]
昨天说过的，initialization跟其他的实现不一样，需要重构

**Comment by hisunnymay** [comment]
@jfang137 明白了，刚才你让我刷新试试，我以为是都改好了，那你都改好之后麻烦告诉我一下吧，我还需要配置 Initialization

> 昨天说过的，initialization跟其他的实现不一样，需要重构

**Comment by hisunnymay** [comment]
@jfang137 btw，刚看到在 language layer 也可以添加 annotation 了，这里应该限制一下不能添加，language layer 不应该涉及 interaction layer 的操作

![image](https://github.com/framely/community/assets/95261974/011a4600-7497-4182-a4de-422a6519ccde)

**Comment by jfang137** [comment]
好的

**Comment by hisunnymay** [comment]
@jfang137 哈喽，目前 Dish.options 的 initialization 还是不能添加，是我这边需要重新定义 Dish 吗？

![image](https://github.com/framely/community/assets/95261974/92d07868-e4eb-4b00-83ea-03c7a04d0bc0)

**Comment by jfang137** [comment]
再看看可以了吗

**Comment by hisunnymay** [comment]
@jfang137 都好了，谢谢

Checked, it's fixed.

![image](https://github.com/framely/community/assets/95261974/6228d93f-a0cf-46c6-895a-6d879fe7f08d)
