### ISSUE TITLE
[Bug]: Can't change ask strategy from "Condition" to "Always ask"

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

想要修改slot：userInputCode的ask strategy为“always ask”，但是选项框里面没有这个选项

尝试了：
1. 重新进入org，选项框里面还是没有“always ask”这个选项
2. 点击选项框中的“never ask”之后，选项框里面就只有“never ask”了

背景：由于value check增加了recovering的功能，所以可以自动refocs到slot：phone了，不需要再使用“ask strategy - condition”作为限制

![image](https://user-images.githubusercontent.com/95261974/158772372-732e3e1b-b1c9-475b-b694-cafaa4e433bb.png)

### Framely Link

https://framely.naturali.io/org/5fa0e7dcf549c817cf952edd/agent/5fa27e3f3a0e9462a4a79edb/frame/620c25cf0df75223acbca6b7/slot/6214a7f0275fe93770a8b3c7

**Comment by jfang137** [comment]
你这个是旧的slot吧， PM方面之前已经决定 string slot只支持never ask了，因为string slot不再作为CUI SLOT

**Comment by hisunnymay** [comment]
@jfang137 好的

注：string slot只支持never ask，所以不能将slot：userInputCode改为“always ask”
