### ISSUE TITLE
[Bug]: Informs for skill slots in composite skills cannot be displayed

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

> 在之前的 issue 中，我们认为 frame slot 的 prompt 为 inform，尽管平台上显示的是 prompt，但因其不具备交互能力，因此是 inform。以下皆称作 inform。

Composite Skill【CompositeTset】有两个 skill slot，有如下定义：
- 【pingPong】（skill slot）
   - Always ask
   - Inform：First, start with PingPong Skill.
   
- 【number】（skill slot）
   - Always ask
   - Inform：Next is Number Skill.

- 截图参考：
<img width="1136" alt="image" src="https://github.com/framely/community/assets/37056884/c4edd0fa-cd9b-45b8-acd3-49ba1edf04ca">

**【问题】目前定义的 Inform 没有输出，即下图中红框位置：**

<img width="521" alt="image" src="https://github.com/framely/community/assets/37056884/8bd20196-7d51-4496-ade8-ba788450d22e">

### Expected Behavior

预期 builder 定义的 inform 可以正常输出。

### Use Case

因为 composite skill 是多个 skill 结合在一起的 skill，无论是最初的需求来源“订机酒套餐”还是现在的“copilot”，都需要一个衔接，即现在的 inform。

在“订机酒套餐”这个场景，订完机票需要订酒店，肯定是要 inform 一下“接下来我们订酒店”，然后再问 skill 里面的 slot，比如：“你几号入住几号离开”，而不是连续的说“已为你订好机票。你几号入住？”

### Steps To Reproduce

/

### Label of org.project

test001/pingpongSL_copy07102

### OpenCUI Link

https://build.opencui.io/org/test001/agent/pingpongSL_copy07102/en/type?page=0&imported=false&search=&category=ALL

**Comment by xiaoyunwu** [comment]
@jfang137 @Zeng666666  can you change the dialogact for component skill slot inside composite skill from SlotRequest to SlotInform?

**Comment by Zeng666666** [comment]
<img width="522" alt="image" src="https://github.com/framely/community/assets/37056884/7d5c34d3-0cd1-4009-b4a8-63ce09e3ee2a">
checked
