### ISSUE TITLE
[Discussion]: Composite Skill and Side Skill ?

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

【目前体验】在 Composite Skill 进行中：该 composite skill 涉及的所有 skill 包括嵌套 skill，如果 user 通过其表达示例触发，该 skill 会被当作 side skill，即先完成 side skill 后再回到 composite skill 继续进行。这就意味着 user 需要对同一个 skill 进行多次填槽或进行多次交易。

【预期体验】在 Composite Skill 进行中，该 composite skill 涉及的所有 skill 包括嵌套 skill，用户可以通过 skill 表达示例触发，但完成该 skill 后，可以认为该 skill 的相关信息是基于 composite skill context 下的，即和 composite skill 是相关的，而不是单纯的当作 side skill 执行完之后回到 composite skill 再执行一次。

【或者】应该让 builder 来定义，是否当作 side skill 还是当作 composite skill？

### Motivation

目前的效果展示：

现在的场景虽然体验不好，但没有实质的影响。但考虑到“机票+酒店”套餐这种 composite skill，如果 user 主动表达先订了酒店，然后回到 composite skill 中又回进行一次，且两次毫不相关。

<img width="1205" alt="image" src="https://github.com/framely/community/assets/37056884/a42c96d0-85da-4a31-9b00-b9fcf661260b">

### Describe alternatives you've considered

chatbot：https://build.opencui.io/org/test001/agent/pingpongSL_compositeTest/en/type?page=0&imported=false&search=&category=ALL

testcase 见 testcase
<img width="570" alt="image" src="https://github.com/framely/community/assets/37056884/0aeb1aa1-ffe2-4d92-a40d-ff3eaa23ef4d">

**Comment by xiaoyunwu** [comment]
How about we recognize the skill is covered by the current composite skill, and simply remind them that we should discard it, and follow the composite skill step by step first. That way, we do not get in the way of the logic of the composite skill.

**Comment by Zeng666666** [comment]
checked

<img width="517" alt="image" src="https://github.com/framely/community/assets/37056884/84c99975-8f2d-4985-bedc-1001011ff213">

**Comment by Zeng666666** [comment]
<img width="520" alt="image" src="https://github.com/framely/community/assets/37056884/4eab0927-370f-48e0-846c-1c65cb036818">

It is good now
