### ISSUE TITLE
[Bug]: Value check function triggered more than once

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Value check(VC)的function在slot filled之后,触发了多次

- 在[No6_Intent](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/intent/62332a7db1606e755314f990)中有三个slot：num_1, num_2, num_3
- VC调用的function: `add1ToNum_1()`的作用是：为slot: num_1 + 1 (num_1是never ask，初始值为0)
- num_2的VC condition为`add1ToNum_1() != 1`， num_3的VC condition为`add1ToNum_1() < 10`

1. 在num_2 fill 之前，num_1的值为0，当num_2 filled后, num_1的值为8 
   - 现状：VC passed, function触发了8次
   - 期望：VC failed, function触发1次
3. 当num_3 fill 后，输出VC prompt，此时num_1的值为21，输出num_3 prompt时，num_1的值为24 
   - 现状：VC failed, function触发了13 + 3次
   - 期望：VC passed, function触发1次

- 对话如下图所示
![image](https://user-images.githubusercontent.com/95261974/158816960-939b9642-95fe-42ad-b18a-3740a7271319.png)

### Expected Behavior

当user按slot的顺序依次填槽且不修改slot的值时，VC的function在slot filled之后, 应该只触发一次

### Use Case

在IUserProfile中，通过调用slot: phone的VC来验证短信是否发送成功`sendSms(phone) != null`，目前因为VC调用多次，导致第一调用`sendSms`是成功的，但是后面调用失败，导致已成功发送短信却告诉user短信发送异常

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/intent/62332a7db1606e755314f990

**Comment by XiaoboYuan** [comment]
@hisunnymay 
vc的condition目前改为了只call一次，修复了这个问题
condition中能不能使用非幂等操作的问题后面再讨论

**Comment by hisunnymay** [comment]
checked.
