### ISSUE TITLE
[Bug]: Sorting problem in backoffice 

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

目前在 backoffice 中，关于排序有以下问题：

1. "**created_at**" column 无法排序：点击 "created_at" column 会有报错：**column UserInfo.create_at does not exist**

   ![image](https://github.com/framely/community/assets/95261974/b7e9fb8d-52c9-4825-a987-719b19f915c9)

2. "**ID**" column 排序有问题：点击 "ID" column 后，当前页面按照 ID 升序排列，但点击进入第二页后，ID 顺序不完全是升序排列 (id 为 16 的那行是最后一行)，此时再回到第一页，当前页面没有 id 为 16的那行数据了

   ![image](https://github.com/framely/community/assets/95261974/72697d22-db3d-411e-bdae-cf31e98f0c64)

   

### Expected Behavior

在 backoffice 点击 "**created_at**" column，能按时间升序排列，点击 "**ID**" column，能按数字升序排序

### Use Case

/

### Steps To Reproduce

详见 https://naturali-io.feishu.cn/docx/U3m4d0oRko9Tm9xWO4gcXuW3nCh

### Label of org.project

/

### OpenCUI Link

/

**Comment by jfang137** [comment]
@HuiCheng 这个bug应该很早之前跟辉哥说过，有空的时候可以看下吗？

**Comment by hisunnymay** [comment]
Checked, 上述两个问题都解决了
