### ISSUE TITLE
[Bug]: "Next page" doesn't work

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

一共有8个推荐值，VR-Number of entries = 5
> B: Input a number
You can choose
[1] 1
[2] 2
[3] 3
[4] 4
[5] 5

> U: Next page

### Expected Behavior

当user说“Next page”的时候，应该显示剩下的3个推荐值

> B: Input a number
You can choose
[6] 6
[7] 7
[8] 8

### Current Behavior

当user说“Next page”的时候，实际回答了“Sorry, I did not get that.”

>B: Sorry, I did not get that.
Input a number
You can choose
[1] 1
[2] 2
[3] 3
[4] 4
[5] 5

### Steps To Reproduce

See an example saved in Test Cases

### Label of org.project

o18810675122

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62157e30275fe93770a91208/intent?page=0&imported=false&search=

### Test Case

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62157e31275fe93770a9120b/test_case

**Comment by Zeng666666** [comment]
从 io.framely.core 的定义来看：
1、Frame：NextPage、PreviousPage 都没有定义 expressions；
2、Intent：PageSelectable 没有定义我感觉应该有的 state update；
但我感觉的可能是错的，因为，似乎有个规则 external 不能定义 annotation，因此 #2 的触发应该是写死在 code 中的？

**Comment by hisunnymay** [comment]
> 从 io.framely.core 的定义来看： 1、Frame：NextPage、PreviousPage 都没有定义 expressions； 2、Intent：PageSelectable 没有定义我感觉应该有的 state update； 但我感觉的可能是错的，因为，似乎有个规则 external 不能定义 annotation，因此 #2 的触发应该是写死在 code 中的？
> 
> @xiaoyunwu 我可以先加上 expression

我试了一下，现在next page能work，但是没有“有多少页，当前在第几页”的提示，我们需要添加这样的提示吗？
@xiaoyunwu @Zeng666666 
![WechatIMG51](https://user-images.githubusercontent.com/95261974/155268964-9bc0fd38-13f5-4cfe-bd34-7f65db214df7.png)

**Comment by Zeng666666** [comment]
嗯嗯，加了 expression 就可以 work 了。

“有多少页，当前在第几页” 这个应该是单独的需求，感觉可以记录下来，放在 wishlist 中

**Comment by xiaoyunwu** [comment]
for external, the only things that is useful is the signature, what
slots/functions do we have, their types so that we can reference them. The
behavior, like state update,  is hard coded, so no need to define it here.
