### ISSUE TITLE
[Bug]: State Update 当 lang 有分支内容时，无法从 struct 传播成功

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 当 lang-agent 存在分支内容时，对于 state update 的修改，无法从 struct 传播到 lang；
2. 因为正好在定义 state update，但不确定其他地方是不是也存在此类问题。

### Expected Behavior

1. structure 内容，应当无论 lang-agent 是否存在分支，都可以稳定且确定全部传播至 lang；（目前有 lang 分支时有一些问题）

2. struct 到 lang 的传播，是不需要处理 conflict 的：
   1. 因为这个场景的冲突，是 structure 内容不同造成的，而 structure 内容应当是强制 merge 到 lang-agent 中，因此不需要 builder 处理冲突；
   2. 但如果需要，可以提示给 builder 比如 struct 传播了哪些不同，因为有可能他正在定义的部分被 struct 删除了；

3. rebase 应当还是需要的，因为 rebase 是指当前 base 落后于 master 了。因为 struct 变了，就表示 base 落后了。

### Use Case

1. struct merge 后，切换到 lang-agent，需要进行 rebase：

![9F100443-B8DB-45AA-A917-E057E2CB12E1](https://user-images.githubusercontent.com/37056884/159130890-e22d5746-b260-43c5-ac2d-7bf5109d08b0.jpeg)

2. 点击 rebase 后，需要处理 structure 内容的冲突：

![3DF0377C-F72C-4C93-9AE7-882C7E4DC33B](https://user-images.githubusercontent.com/37056884/159130895-2bf9690b-82fa-4fdf-ab6f-ade4a7a1db26.jpeg)

3. 选择 master 后，没有任何变化，即 struct 的改动没有被 merge 到 lang：

![48181980-8114-4F5C-A6E8-ED46425FC472](https://user-images.githubusercontent.com/37056884/159131076-8572ecc3-c20a-4939-a632-d074d0bcf5de.jpeg)

4. struct 定义对比：

![185B3572-C903-4E7E-A431-AEF1C08A1582](https://user-images.githubusercontent.com/37056884/159131079-0039d0e0-4092-435c-8ec9-16f8bf42f2ad.jpeg)

### Steps To Reproduce

/

### Label of org.project

test001.test_recheck

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/62346cc38a85bacb4320c064/intent/623439018a85bacb431f1aa3/state_update/62354cce8a85bacb432147a2

**Comment by xiaoyunwu** [comment]
@jfang137 @Zeng666666 can you try to figure out whether there are some deep reasons for this?  we seemed have many of the similar issues.

**Comment by jfang137** [comment]
@xiaoyunwu  propagating, importing, cloning,template，struct 创建 lang和以前的lang 创建 struct。 以上这些case走的是同一套copy逻辑的封装，是后端逻辑最复杂的地方。改动是牵一发而动全身的，确实需要更多的测试来完善其中隐藏的问题。

**Comment by xiaoyunwu** [comment]
I understand the complexity it involved. I am just want to make sure we have an solid design, and what we experienced is just a bug, instead of some systematic gap.

**Comment by jfang137** [comment]
> I understand the complexity it involved. I am just want to make sure we have an solid design, and what we experienced is just a bug, instead of some systematic gap.

这个问题不是设计缺陷导致的, marti在实现之初没有支持struct中的某一条数据propagate and rebase时，language中有未merge的对同一条数据的修改时，struct 数据向branch的propagating。这个case的支持比较难，我不久前尝试支持了rebase过程propagating struct fields到umerged data中，但没有完全解决conflicts时的相关问题，我还需要一些时间来完善完整的路由

**Comment by xiaoyunwu** [comment]
I have a quick question, what if we make sure all language/struct are always in same version, meaning the language only version will also bump the struct version even when it is not changed?

**Comment by xiaoyunwu** [comment]
I do not whether this will fix the issue, but I feel the current versioning is very complex, and this can potentially simplify it a bit. 
Then things might be easier to deal with.

**Comment by jfang137** [comment]
> I do not whether this will fix the issue, but I feel the current versioning is very complex, and this can potentially simplify it a bit. Then things might be easier to deal with.

也是一个好的思路：
#1在现在的查询基础上加dumping逻辑
#2推倒现有架构，重新设计数据组合架构
有这么两个方向，前者在做详情数据的查询时，要同时查struct和lang的两个版本，查询效率会打五折。后者几乎是所有东西重来，代价应该相当大。不管怎么样我们都应该认真考虑，短期内我还是先把这里的缺陷补完整
