### ISSUE TITLE
[Bug]: sometimes, it need to compile twice

### ISSUE THREAD

**Issue by yigexu** [framely/community#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我遇到了一些不能稳定复现的问题

1. 截图的问题遇到过好几次：
<img width="1421" alt="x" src="https://user-images.githubusercontent.com/6505755/159218691-14ddda14-b8f3-43fb-bfba-ebf3829e724b.png">

操作流程：
- 修改[library](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d1ff5c77cdfc255d0f/intent/61f0b1826a5313c74a2df848?tab=2)
- 在[chatbot](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/version)更新library
- compile
- 截图错误
- 再次compile，成功

我感觉和这个操作流程比较相关，由于每次改的东西比较多，所以记不得；如果需要知道具体改了什么，或者有什么怀疑的，可以comment后续我关注一下

2. connect 表现不正确

操作流程：
- 修改[library](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d1ff5c77cdfc255d0f/intent/61f0b1826a5313c74a2df848?tab=2)
- 在[chatbot](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/version)更新library
- compile，成功
- connect，bot 表现是更新library之前的
- 再次compile，成功
- connect，bot 表现是更新library之后的

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

见上面的链接

**Comment by jfang137** [comment]
是连续再次compile,一次不成功一次成功？ @yigexu

**Comment by yigexu** [comment]
对，两次 compile 之间我都没有改配置

**Comment by jfang137** [comment]
我反复试了每次改点东西后提测，给到compiler的数据都是最新的修改，似乎compiler的connection后表现也是按照最新的修改来的，没能复现这个问题。 @XiaoboYuan 你能大概定位下图片中的抛错是什么数据传的问题吗？

**Comment by hisunnymay** [comment]
@yigexu @jfang137 会有可能是调用到了别的bot的吗？我之前在我的org里面点击commit，但出现了不是来自我org的报错

如下图所示，我在org：o18810675122中点击commit，但是报错信息是来自org：restaurant002的

![OJhhBlGhe6](https://user-images.githubusercontent.com/95261974/159229337-25b45c0d-0855-40a1-bc9b-d3420d314421.png)

**Comment by yigexu** [comment]
我感觉存在可能性 我的问题1 和 chang的问题 是一个原因，都是因为 error 打串了？不过不太清楚 我的问题2 是怎么出来的，我目前只遇到了1次问题2

**Comment by jfang137** [comment]
provider数据是从restaurant002的provider中合并来的，在当前chatbot没有修改内容，两次compiler结果的不同很有可能 是provider的数据发生了变化

**Comment by yigexu** [comment]
现在provider如果版本和chatbot不同会弹窗，我看到弹窗会去改。所以我说我在两次compile之间什么操作都没做。
还是你在说，是provider在两次compile时，合并出来的结果可能会不一样？
@jfang137

**Comment by jfang137** [comment]
弹窗检查的是provider中service的版本与chatbot中不一致。  provider本身内容的修改是不会弹的，但是proivder每次更新都会被合并到bot的下一次compile中

**Comment by yigexu** [comment]
我今天没改过provider。
另外我感觉 @hisunnymay 的问题是可以稳定复现的。

@jfang137 

https://user-images.githubusercontent.com/6505755/159231582-423661b9-421b-4704-90c9-a9cc15255a90.mov

**Comment by yigexu** [comment]
左边是我随便找了一个bot，在response中故意写的错误的code expression ${it}，它在两个bot下面都被打出来了。
感觉可以先fix这个试试。

**Comment by jfang137** [comment]
这可能得 @XiaoboYuan 先定位一下，runtime抛错我也不知道原因

**Comment by jfang137** [comment]
我再看看是不是backend的缓存问题
