### ISSUE TITLE
[Bug]: Failed to save content while showing "Successfully saved"

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
当”Successfully saved“弹窗没有消失时，builder的如果在此期间完成了别的操作，该操作将无法被保存。

比如：在“state update”中，当某项操作(e.g. 选择trigger method, 添加state, 添加update action)成功后，会有弹窗提示”Successfully saved“，如果在弹窗还没消失之前，完成了别的操作(e.g. 选择了clear slot的target slot)，退出state update之后，就无法保存该操作添加的内容

### Expected Behavior

builder已经完成的操作，应该都能被保存下来

### Steps To Reproduce

1. 添加一个state update，选择trigger method为：“condition”, 弹窗提示：Successfully saved
2. 添加conditions，弹窗提示：Successfully saved
3. 添加update date action：clear slot，弹窗提示：Successfully saved
4. 在弹窗还没消失之前，选择target slot：num
5. 重新进入state update，发现target slot没有添加上

---

1. 步骤#4截图
![image](https://user-images.githubusercontent.com/95261974/159227940-0d362c4b-bba2-4d83-8587-dd16f4f03691.png)

2. 步骤#5截图
![image](https://user-images.githubusercontent.com/95261974/159228608-8e9afb1a-bfe1-4ba9-a99e-e5694bb3fa59.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62023ac1a7efe61fe44f3180/intent/62023bbfa7efe61fe44f3ad5/state_update/6238345e2c48df9b37ca6c1a

**Comment by jfang137** [comment]
不是bug，以前有过这样的需求，这是前端的节流操作限制的，两秒之内的频繁保存会被过滤掉。要不要改掉可以在产品层面讨论下

**Comment by hisunnymay** [comment]
@Zeng666666 @yigexu @jfang137 

如果前端有“节流操作限制”的话，要不要让builder知道不能频繁保存，比如提示：操作频繁？
或者能不能在commit的时候，自动再保存一次builder之前的操作？

我经常会有创建了state update但是没有保存上的情况，报错有：

1.  当update action - fill slot - target slot没有保存上时，commit会报错
> io.framely.compiler.entity.CompilerException: empty text for a variable type : Test
2. 当update action - fill slot -  target slot保存上了，但code expression没有保存上时，connect会报错
> Error: Internal Server Error

对于builder来说，这两个报错可能都不容易定位到：state update有值没有填上的问题上。

除此之外，由于“节流操作限制”，在“approve”后，点击“merge”，也容易出现没有merge上的情况。

站在builder的角度，他的这些操作都是有页面响应的（比如：他点击了merge，出现了确认弹窗，他也点击了确认），但是结果却是这些操作并没有被保存上（比如：没有merge上），对于builder来说可能会有点困惑。

**Comment by Zeng666666** [comment]
1. “操作频繁” 也是经常看到的一种常规提示，感觉是可以也这样提示给 builder 的；

2. Internal Server Error 的问题可见 #86 ；

3. merge 不上的情况是指什么？点击 merge 却没有 merge？这个我还没有遇到过，具体可以让 @jfang137 看一下

**Comment by hisunnymay** [comment]
@jfang137 @Zeng666666  关于“点击 merge 却没有 merge”的情况如下所示，这和“节流操作限制”有关吗？

https://user-images.githubusercontent.com/95261974/159413172-35ba8f91-598f-4597-b569-271db9011824.mov

**Comment by Zeng666666** [comment]
@hisunnymay 有可能

**Comment by Zeng666666** [comment]
@hisunnymay btw，如果定义没有被保存上，对于 builder 来讲，定义了什么是可以通过 diffs 看到的；如果按照正常顺序操作的话，builder 是不会到 lang-agent commit 时才发现。我们可以多关注一下 diffs，如果涉及 diffs 的问题，也好及时发现、反馈。

**Comment by hisunnymay** [comment]
@Zeng666666 正常顺序是：commit - 查看diff - approve - merge吗？

修改一个state update的diff是这样的，感觉可读性不是很高，因为diff的结构和平台上还是有一定区别的，builder不一定能很快地根据diff的内容对应到平台上的定义。

或许能在struct commit的时候能把应该填写但没有填写的地方（比如：选择了clear action，但是没有选择target slot）以报错的形式报出来吗？
![image](https://user-images.githubusercontent.com/95261974/159465192-aa2dde2c-fcff-4fdd-a090-60f5fd8ca6cf.png)

**Comment by Zeng666666** [comment]
@hisunnymay 
1. Diffs 的查看，是在任何时候都可以查看的，点击 Diffs icon 即可查看 master 与 branch 的区别；

2. Review 流程和其他所有需要审核机制的流程是相同的，pr 可以自己审，可以他人审，审核成功，进行提交、上线。只不过 platform 对于每一环节的叫法及展示样式参考了 github。Review PR，也是以 diff 形式呈现的，review 的目的就是让 builder 在改动合并到 master 前做最后的确认；
   1. Approve 表示 builder 确认改动；
   2. Close 表示 builder 拒绝或关闭改动；
   3. Merge 表示 PR 被接受，builder 决定将 branch 的改动合并到 master 成为新的 master。

3. json 是目前 platform diffs 的展示形式，json 也是一种阅读性较强的格式，始终以 key/value pair 形式展示，只要去看与“定义内容”相对应的字段、value 即可，虽然我不会写但我觉得读起来还是很好接受的。如果 builder 会写 sql、还懂 kotlin 的话，应该不会影响他们的体验；

4. 目前 struct commit 只是一个提交行为，并不走进行任何校验。因为 struct 的数据对于 agent 而言并不完整，有可能不太能判断？如果判断的话，那些必须定义，但又在 lang 中定义的内容是不是都会报错？还有一些是执行时才出现的问题，commit 时是不会报错的，在 struct 时就算有问题也不会有报错？


关于 version control 可见 glossary 中的描述 ： https://framely.github.io/guide/glossary.html#version-control 不过 version control 不过这部分应该是整体的段落，我抽空改一下。

**Comment by hisunnymay** [comment]
@Zeng666666 好的，明白了

**Comment by hisunnymay** [comment]
@jfang137 如果你有时间的话，可以添加：当user操作频繁时，提示“操作频繁” 的弹窗吗？

btw, "操作频繁"包括：user频繁切换页面（比如：从schema切换到annotation再切换回来)的情况吗？

**Comment by jfang137** [comment]
节流借助的是基础框架，在fe层面的调用效果不是拦截而是丢给接口，由框架内部实现过滤，调用层面是无感知的，所以无法给到提示。切换页面没有限制

**Comment by jfang137** [comment]
我能做的监控请求状态，在请求没返回之前拦截其他请求

**Comment by Zeng666666** [comment]
那拦截请求的时候会有提示吗？以及 meichang merge agent 时失败也是因为这个原因不？

**Comment by jfang137** [comment]
会的，merge agent失败我还得看

**Comment by Zeng666666** [comment]
好的，明白

**Comment by hisunnymay** [comment]
@jfang137 我试了一下，没有出现“操作频繁”的提示，是需要先在哪里设置“操作频繁”的话术吗？

**Comment by jfang137** [comment]
没有出现说明你再按的时候上个请求已经回来了，现在没有2秒的限制了。你快速按两下slot multi-valued开关试试 @hisunnymay

**Comment by hisunnymay** [comment]
还是没有..

https://user-images.githubusercontent.com/95261974/159866672-0ac16f91-83b8-4f1c-9838-6e67281cca1e.mov

**Comment by hisunnymay** [comment]
@Zeng666666 现在没有节流操作的限制了，当user发送请求前如果上一个请求还没有返回值，那么会出现弹窗。

测试结果：目前不会出现当user发送请求前，上一个请求没有返回值的情况。
