### ISSUE TITLE
[Bug]: On Service, switching lang-agent will get 'info not found'

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

service 从 struct 切换 lang 时，如果在 service 页面进行的切换，会提示报错：

![image](https://user-images.githubusercontent.com/37056884/159238331-77a27f3e-539f-457f-9668-8bc92b9ec9ba.png)

### Expected Behavior

如果在 service 上切换 lang-agent，是否可以隐藏 lang 中的 service page？或者显示出 struct 内容但整体不能编辑？还是有更好更简单的方法？不确定怎样做会比较好，但这里的预期是不应该提示报错。

![image](https://user-images.githubusercontent.com/37056884/159239936-2e42f49b-b6d2-4a42-9d10-662e407359d9.png)

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

**Comment by jfang137** [comment]
解决了一下查询问题，限定了编辑权限，没有进行隐藏。

**Comment by Zeng666666** [comment]
嗯嗯，可以的
