### ISSUE TITLE
[Improvement]: separate label hint

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

预期，label 的提示语需要分字段支持一下：
1. `Type Label`：Type label should start with capital case, limited to 2-100 characters, and only support letters, digits, underscores.
2. `Slot / Function label`：Slot label should be in camelCase, limited to 2-100 characters, and only support letters, digits, underscores.
3. `Function Parameter Name`：Enter parameter name

### Motivation

因为 label 的限制，我在“前端名称维护”页面，修改了 label 的提示语，字段 `common_name_placeholder` ：

- 前端名称维护的修改：

![image](https://user-images.githubusercontent.com/37056884/159420048-c73ea263-e39f-4425-ada3-5173d912dcce.png)

- Platform 现在：

![image](https://user-images.githubusercontent.com/37056884/159419995-7b1869cb-69a3-4591-b948-917afe7776e2.png)

后来 @hisunnymay 发现 function 的 parameter 提示语用的也是这个字段：

![image](https://user-images.githubusercontent.com/37056884/159422048-6770c220-202e-41e4-b391-d9ce07b4e0fb.png)

目前，这两个位置的提示语已经不同了，无法再用同一字段进行支持了，需要分别支持一下。

现在已经把字段 `common_name_placeholder` 恢复回去了：

![image](https://user-images.githubusercontent.com/37056884/159423493-0a133a5c-1b64-4b8a-84b8-a5bf80d82aba.png)

`common_invalid_name`这个字段的提示语不知是否需要改？不确定哪些地方用了它：

![image](https://user-images.githubusercontent.com/37056884/159423831-7460a2d9-b371-48fc-8b24-3f5cb13e77c2.png)

### Describe alternatives you've considered

/

**Comment by jfang137** [comment]
@Zeng666666 
type_label_hint
slot_label_hint
func_param_name_hint
我代码里面改成取这三个key，你可以在map里连中文的也加一下

**Comment by Zeng666666** [comment]
@jfang137 好的

**Comment by Zeng666666** [comment]
Done
