### ISSUE TITLE
[Feature Request]: better footer on the home page / content page 

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. create the new navbar/footer that mimic the supabase navbar/footer, for both home page, and content page. 
2. support new layout like supabase for the home page. 
3, support new layout for blog list and blog post 

The things we like the default theme:
1. dark mode. 
2. markdown content 
3. static site for both desktop and mobile. 

### Motivation

The currnet vuepress nvabar/footer is not enough. 

### Describe alternatives you've considered

n/a

**Comment by xiaoyunwu** [comment]
https://v2.vuepress.vuejs.org/reference/default-theme/extending.html#layout-slots

**Comment by karani12** [comment]
@xiaoyunwu I'm supposed to look at footer for supabase docs https://supabase.com/docs and not landing page?

**Comment by karani12** [comment]
> @xiaoyunwu I'm supposed to look at footer for supabase docs https://supabase.com/docs and not landing page?

Oh I got it. Home and content have different footers

**Comment by xiaoyunwu** [comment]
https://snipcart.com/blog/vuepress-tutorial-vuejs-documentation
