### ISSUE TITLE
[Feature Request]: support plpgsql instead of sql

### ISSUE THREAD

**Issue by yigexu** [framely/community#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

目前平台创建 function 采用的是 language sql，我们应该默认支持 language plpgsql。

### Background
为了保证下单的行为是 transactional 的，需要在同一个 udf 中实现 1 个 create + N 个 insert 操作，而不是分成 1 + N 个 function
```
createOrder()
foreach(item in orderItemList)
    insertOrderItem(item)
```
因此，在 function 定义中需要用到 loop。

### Motivation
1. 我没找到明确的说明，但是 postgre 官方文档的例子里，language sql 定义的全都是基本的 sql 语句，因此我怀疑 language sql 不支持 declare、loop 等复杂操作。因此，需要支持 language plpgsql。
- [udf](https://www.postgresql.org/docs/13/xfunc.html)
- [language sql](https://www.postgresql.org/docs/13/xfunc-sql.html)

2. 即使 language sql 支持 declare、loop，我也觉得应该默认 language plpgsql。
builder 在创建 provider 时其实已经选择了 provider type = postgrest ，所以在没有其他提示的情况下，我觉得对 function language 的默认预期应该是 language plpqsql。
如果后续有需要，可以支持 builder 选择 language type。但我感觉 language plpgsql 支持的能力范围包含且大于 language sql，所以目前不是特别有必要。

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
Sgtm

**Comment by yigexu** [comment]
@HuiCheng 可以先看一下这个。

**Comment by yigexu** [comment]
@HuiCheng https://stackoverflow.com/questions/24755468/difference-between-language-sql-and-language-plpgsql-in-postgresql-functions 我找到了这个。

@hisunnymay 这个需求可能会导致 function 的实现代码稍微改动一些

**Comment by yigexu** [comment]
@HuiCheng 我发的文档里有提到 select 必须要通过 into 才能 返回；截图是你 generate 的代码，它没办法通过
<img width="876" alt="Screen Shot 2022-03-24 at 1 52 44 PM" src="https://user-images.githubusercontent.com/6505755/159851369-19c849be-a81d-4859-ba1d-3b82caa47a3c.png">

**Comment by yigexu** [comment]
@xiaoyunwu 现在有一个问题是： @HuiCheng 会在 function body 外面包裹一层 **SELECT row_to_json(data) from ( `builder wrote function body` ) as data;** 让 function 返回 JSON。而包裹的这一层会导致最终 create function 的 grammar 不通。

这一点我没想到怎么解决：
builder 只能对他自己写的语法负责，且需要能定义全部的 function 内容。但他不知道(平台限制导致的)function 返回结果是 json。
有没有办法就让 builder 创建自己的 function，原来包裹的这一层，作为单独的一个函数去调用？比如 convertToJson(builder_defined_udf(...))

**Comment by yigexu** [comment]
```
# 这是 user 创建的 function，db 什么改动都不做
CREATE OR REPLACE FUNCTION "restaurantP214"."getDishInner" ("locate_param" text) RETURNS json
SET SEARCH_PATH = "restaurantP214" AS $BODY$ 
	declare ret json;
	begin
	select target into ret from "CategoryDish" where source = locate_param;
	return ret;
	end
$BODY$ LANGUAGE PLPGSQL;

# 这是 db 把原来的 function 包裹成 json
CREATE OR REPLACE FUNCTION "restaurantP214"."getDishOuter" ("locate_param" text) RETURNS TABLE (data json) 
SET SEARCH_PATH = "restaurantP214" AS $BODY$ 
begin
return query SELECT row_to_json(tdata) from (select "restaurantP214"."getDishInner"(locate_param)) as tdata;
end
$BODY$ 
LANGUAGE PLPGSQL; 
```

**Comment by yigexu** [comment]
@xiaoyunwu @HuiCheng 这样可行吗

**Comment by yigexu** [comment]
new solution: https://naturali-io.feishu.cn/docs/doccnO3f4kRDz8zrWSHLbnwOUtb#

**Comment by yigexu** [comment]
@xiaoyunwu add some comment in https://naturali-io.feishu.cn/docs/doccnO3f4kRDz8zrWSHLbnwOUtb#

**Comment by yigexu** [comment]
@xiaoyunwu 有一个问题：rowcontainer在平台上被设置为返回类型之后，在library中用的时候返回类型也是rowcontainer，这和原来的类型不匹配。

**Comment by xiaoyunwu** [comment]
What do u mean by the original type ?

**Comment by xiaoyunwu** [comment]
Expression.Map {it -> it.slot}

**Comment by yigexu** [comment]
@hisunnymay 这个功能已经上线了。
之前的 provider 如果要重新 deploy，需要改一下设置。主要包括两点：
1. 根据需要将原来的 function return type 配置成 rowcontainer，涉及到的 type 主要包括 primitive type、interface frame
2. 将 function body 适配成适合 plpgsql 的语法。

举个最常用的例子：
原来的 sql 是 
``` sql
select col1 from t1
```
现在应该写成
``` sql
begin
return query select col1 from t1;
end
```
