### ISSUE TITLE
[Bug]: runtime每次发版之后都需要buidler手动deploy

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

runtime每次发版之后都需要buidler手动deploy，但是目前builder是无法感知runtime是否发版

### Expected Behavior

/

### Current Behavior

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

### Test Case

/

**Comment by xiaoyunwu** [comment]
if we do not commit, what would happen? @hisunnymay

**Comment by hisunnymay** [comment]
> 

You mean don't deploy? 

According to kui "try it now 也会用到 runtime；runtime 发版了，你也是要 deploy 的",
so if we don't deploy, we can't use "try it now" with the latest runtime.

我刚才遇到的情况是：runtime发版之前，我有一个compile error: type mismatch，当runtime发版之后，在没有deploy的情况下，我重新compile，就没有这个“type mismatch”的报错了。

所以builder正确的流程是否是在runtime发版之后，需要先deploy才能再commit and try it now？

**Comment by xiaoyunwu** [comment]
runtime update will be a rare state when we get it to a stable mode. In
this case, I think we just need to try to commit for now. Kind of like
restart the computer. @lu zeng ***@***.***>

**Comment by Zeng666666** [comment]
> > You mean don't deploy?
> 
> According to kui "try it now 也会用到 runtime；runtime 发版了，你也是要 deploy 的", so if we don't deploy, we can't use "try it now" with the latest runtime.
> 
> 我刚才遇到的情况是：runtime发版之前，我有一个compile error: type mismatch，当runtime发版之后，在没有deploy的情况下，我重新compile，就没有这个“type mismatch”的报错了。
> 
> 所以builder正确的流程是否是在runtime发版之后，需要先deploy才能再commit and try it now？

runtime 发版，肯定是要 commit 才能用。但需要 deploy 才能 commit 是为什么呢？

**Comment by hisunnymay** [comment]
> runtime 发版，肯定是要 commit 才能用。但需要 deploy 才能 commit 是为什么呢？

我理解的可能deploy了之后才能用最新的runtime，不然用的就是旧版本的runtime

**Comment by hisunnymay** [comment]
> runtime update will be a rare state when we get it to a stable mode. In this case, I think we just need to try to commit for now. Kind of like restart the computer. @lu zeng ***@***.***>

我感觉得把你句子里说的“commit”换成“deploy”，才能理解通顺。你的意思是：等builder要用的时候，runtime已经比较stable了，所以可以不考虑当runtime发版之后，builder需要点击deploy之后才能commit的问题，对吧？

所以目前来说，正确的操作流程是在runtime发版之后，先deploy，然后再commit是吗？

**Comment by yigexu** [comment]
这个感觉并不对。不频繁发版不等于不发。总不能runtime发版所有服务端全部宕机/或者大家越好一起重启吧？

**Comment by Zeng666666** [comment]
deploy 是指什么呢？ click platform “Deploy” icon 吗？

过去是 runtime 发版后，需要手动 click platform “commit” 一次，才能使用。

现在如果不 click platform “Deploy” icon 是指  runtime 发版后，WeChat 上面的 chatbot 不 work 了吗？

**Comment by hisunnymay** [comment]
1. deploy是指：“click platform “Deploy” icon ”

2. 不 click platform “Deploy” icon 是指 ：runtime发版之后，不deploy，我用try it now 就不能成功调用function：sendSms（用来给user发短信），因为kui在runtime改了代码（在runtime创建了type：PhoneNumber）

P.S. #2目前的效果是这样，但是不确定是不是deply成功之后就能成功调用function：sendSms，因为现在deploy有一点问题，所以测试不了

**Comment by yigexu** [comment]
你说的是chatbot deploy还是provider deploy？
for chatbot，我感觉应该是
tryitnow在每次runtime发版后，需要重新commit；但它本身和deploy无关。
如果是wechat等channel，每次runtime发版完，如果runtime变更没有被那个bot使用到，那么就不需要重新deploy。

不过我不确定现在这个策略的设计和实现到底是什么

**Comment by hisunnymay** [comment]
是chatbot deploy

**Comment by xiaoyunwu** [comment]
I think we should just let builder know if they want to make sure, always
commit first and then deploy.

**Comment by xiaoyunwu** [comment]
When there r problems

**Comment by xiaoyunwu** [comment]
@hisunnymay I propose that we do not fix this for now. Hopefully, as more and more platform/runtime gaps are fixed, this is less of the problem. For now just commit one more time if there issues.
