### ISSUE TITLE
[Bug]: reply template 无法从 struct 传播至 lang

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. reply template 无法从 struct 传播至 lang，应当可以成功传播；
2. reply template 应当在 struct-agent 定义，lang-agent 处禁止编辑；
3. simple reply 支持“回车”（因为 reply 只有一个条目了，应当可以支持回车了）。

备注：涉及：response、value rec、update action。

![image](https://user-images.githubusercontent.com/37056884/160073248-ac439ed3-e85e-44d9-9d4e-bc73c70bfcd0.png)

![image](https://user-images.githubusercontent.com/37056884/160073308-b980a659-1cc4-48a8-b1f4-ab7ccf77de8c.png)

### Expected Behavior

reply template 应当在 struct 定义，且可以成功传播至 lang。

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

test001.teststruct

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/621d80f261f0057d035f643d/intent/621d942961f0057d035f8f6e?tab=2

**Comment by jfang137** [comment]
选择template我觉得可以在language里做，因为选择的过程是要同时填充body的，在struct里填充body没有意义，也使得language中失去了填充的机会

**Comment by jfang137** [comment]
@Zeng666666

**Comment by Zeng666666** [comment]
从定义上看，template 是属于结构部分，如果在不同的 lang 中选择不同的 template，结果就会不同；
不过是不是现在的情况，是不是没有办法这样做呢？因为都是内容 input 区域？（如果做成 UI 样式就好多了，这个未来会支持）

今天是定义 core 的时候遇到了这样的问题，如果有改动，好像除了删除从新添加，不然就需要定义三次才可以。

感觉还是等以后完善后再做吧。 @jfang137

**Comment by jfang137** [comment]
好的

**Comment by xiaoyunwu** [comment]
if we add the type of message as a field and make that struct, and then have the content of message as lang (even when there are code expression inside), would that work? @Zeng666666 @jfang137

**Comment by jfang137** [comment]
template or message type只能控制去初始化一个content，用户在language中还是可以将content改成任意的形式，其内容在初始化后是脱离template的控制的

**Comment by xiaoyunwu** [comment]
understand, so message type is not passed to code gen?

**Comment by jfang137** [comment]
> understand, so message type is not passed to code gen?

message type有传到code gen的，
![image](https://user-images.githubusercontent.com/16040960/160332912-0ac4f57a-868f-455e-846f-0c4b3626a44b.png)

**Comment by xiaoyunwu** [comment]
then let's make type struct and content lang? We can gradually add some check on the runtime side?

**Comment by jfang137** [comment]
我觉得template在language中可选的话，有一个好处就是给用户一个机会在编辑content的过程中去通过选择template去重置或修复错误的content

**Comment by jfang137** [comment]
type的在struct中定义的话，也许可以在lang中增加一个按钮去重置content

**Comment by xiaoyunwu** [comment]
but then we can not make sure the consistence between channels.  Will think
about it a bit more.

**Comment by xiaoyunwu** [comment]
wait, you seem to suggest that type and content need to be together, both
as struct or both as lang, correct?

**Comment by jfang137** [comment]
是的，选type的同时需要给content赋值为对应的template的，struct中赋值content没有意义，同时propagating也会覆盖掉中lang中原本可能定义好的content

**Comment by xiaoyunwu** [comment]
assume code gen will eventually check the match between type and template
in content, is it possible to have type be struct and content be lang? I
understand that builder can change what is in content.

**Comment by jfang137** [comment]
type in struct, content in lang，权限控制上和数据上是没问题的，code gen也不需要感知struct与lang.。
content中需要一个时机去初始化为type对应的template文本，这个时机我们怎么安排呢。 选择了type但是content=""这种表现应该不太对

**Comment by xiaoyunwu** [comment]
when content = "", we initialize the content. 
when we change type, we remind user that we will clean out all the content in language, after confirmation. 
@Zeng666666

**Comment by xiaoyunwu** [comment]
https://dev.to/brpaz/how-to-create-your-own-auto-completion-for-json-and-yaml-files-on-vs-code-with-the-help-of-json-schema-k1i we might want to figure out how do we improve json input for time being.

**Comment by Zeng666666** [comment]
感觉可以的

**Comment by jfang137** [comment]
好的。propagating 过程中，如果lang的content=“”或者lang message type != struct message type，则init content

**Comment by xiaoyunwu** [comment]
I had some experiences today try to create a test bot, and after I merged struct, the slot I created did not pushed to lang. I am wondering whether we have some solution that can reduce the kind of issues.

**Comment by jfang137** [comment]
> I had some experiences today try to create a test bot, and after I merged struct, the slot I created did not pushed to lang. I am wondering whether we have some solution that can reduce the kind of issues.

@xiaoyunwu ,给我发下你的bot地址好吗？ propagating涉及的细节确实有点多，我相信这些细节在不断的使用中在完善。让我先确定一下你碰到的问题是以前的同样原因问题没有解决，还是其他一些没有覆盖到的细节，尽管问题的表现相似，可能不是同样的原因导致的，脱离具体问题，没办法讨论方案。
