### ISSUE TITLE
[Feature Request]: prompts/vrs/replies‘ source can be shown on ‘try it now’

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Try It Now 展示 bot “回复” 出处，这样 builder 就不需要像下面这样定义，来追踪问题：

![image](https://user-images.githubusercontent.com/37056884/160100344-ca754506-ebbb-4285-b552-b94437144811.png)

### Motivation

/

### Describe alternatives you've considered

/

**Comment by yigexu** [comment]
这个场景是什么？
如果builder想知道这句话是什么（prompt还是VR），那么他也会想知道这是谁的prompt（归属于哪个slot、intent），以及在什么条件下出现的这句话（哪个condition分支导致的reply）。

我感觉这涉及到整体怎么debug的问题；短期内，也许可以把话术拆开，每个话术下面给出 DM 的状态？

**Comment by Zeng666666** [comment]
@yigexu 我觉得可以分步来看，长远看，肯定是越细致越好。

短期看，比如这个需求，就只是静态的展示定义的 source 归属/来源，即可。

**Comment by XiaoboYuan** [comment]
@Zeng666666 @xiaoyunwu 
目前会有这些tag
SlotRequest: Prompt
SlotConfirm: explicit confirm
SlotInform: implicit confirm
SlotOffer: VR list
SlotRequestMor: HasMore

还需要什么别的tag吗？如果有可以列一下

**Comment by yigexu** [comment]
我感觉 VC 和 Reply 至少需要加一下？

**Comment by XiaoboYuan** [comment]
> 我感觉 VC 和 Reply 至少需要加一下？

ok 先加这两个 剩下的还有什么以后也可以加

**Comment by XiaoboYuan** [comment]
这个完成了 可以试一试 可能会漏掉一些 发现了再加

**Comment by hisunnymay** [comment]
@XiaoboYuan Multi-Valued Prompt的 Min 和 Max Exception的tag现在是SlotValueCheck，或许为了避免和Value Check混淆，可以再换成别的吗？比如：SlotMinException, SlotMaxException

![image](https://user-images.githubusercontent.com/95261974/169784565-d1ded9d5-90c3-45f2-a0ad-2fa2617b56f5.png)

**Comment by hisunnymay** [comment]
@XiaoboYuan 对于Multi-Valued slot，它的**Prompts**目前对应的source是：`SlotRequestMore`，这和**Multi-Valued Prompts** 重复了，不能区分这两个Prompt，感觉可以改为和single value prompt一样的source：`SlotRequest`

![8swEsMM2d8](https://user-images.githubusercontent.com/95261974/170915039-e97d72a3-c35e-4018-b6d9-7f5a2db6c3ab.jpg)
