### ISSUE TITLE
[Bug]: Mention intent again in intent

### ISSUE THREAD

**Issue by yigexu** [framely/community#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user mention intent A again while intent A is not finished (include complete, end by builder, abort by user), he/she should experience intent A with all the information provided before. In other words, he/she directly continues the conversation of intent A.

Right now, the behaviour is:
- If user says intent expression "blabla...", he/she has to go through two intent A. This needs to be fixed.

(Here's how a intent with intent expression test, an int type slot, and a frame level confirmation performs)
<img width="469" alt="y" src="https://user-images.githubusercontent.com/6505755/160511759-6e97920d-757f-4468-971a-f44f3201180f.png">

- If user says intent expression "blabla $slot$ ...", he/she experiences as expected. This is correct.

More discussion: [Mention intent again in intent](https://naturali-io.feishu.cn/docs/doccnYKAp0m5tUatnxIKPWbqrbc)

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant

**Comment by yigexu** [comment]
1. 规划中会有clarification
2. 基于 @xiaoyunwu 的回复，我理解这是和设计预期不同的地方，需要先 fix bug。

**Comment by xiaoyunwu** [comment]
let's define an IntentRentry system intent, and supply some simply reply for now? "We are in the middle of ${intent.typeName()} already, let's  continue with the current process."

**Comment by XiaoboYuan** [comment]
> let's define an IntentRentry system intent, and supply some simply reply for now? "We are in the middle of ${intent.typeName()} already, let's continue with the current process."

我目前的理解是DU会直接根据expectation把expression识别为trigger IntentReentry，runtime不需要做什么修改，如果理解的不对告诉我一下
@xiaoyunwu

**Comment by yigexu** [comment]
我目前没有增加 expression，因为在这里 user 说的是某个 intent 的 expression，而不是 ResumeIntent (也就是上面 IntentRetry) 的 expression

具体设置见：https://framely.naturali.io/org/5fa0e7dcf549c817cf952edd/agent/5fa27e3f3a0e9462a4a79edb/intent/625623b6f7970446e380a220

**Comment by yigexu** [comment]
oh，我可能理解你的意思了。
如果说把 正在进行的intent expression，被识别为 trigger ResumeIntent 的 expectation 成立的话，那么应该是的。

**Comment by yigexu** [comment]
updated ResumeIntent part on requirement [Mention intent again in intent](https://naturali-io.feishu.cn/docs/doccnYKAp0m5tUatnxIKPWbqrbc)

**Comment by xiaoyunwu** [comment]
> > let's define an IntentRentry system intent, and supply some simply reply for now? "We are in the middle of ${intent.typeName()} already, let's continue with the current process."
> 
> 我目前的理解是DU会直接根据expectation把expression识别为trigger IntentReentry，runtime不需要做什么修改，如果理解的不对告诉我一下 @xiaoyunwu

@XiaoboYuan DU will return the original event for original, can we handle the conversion to ResumeIntent  in runtime? It is true that sometime DU can figure out intent is already active based on dialog expectation, but I think not all the time that information is encoded in DE.

**Comment by XiaoboYuan** [comment]
> > > let's define an IntentRentry system intent, and supply some simply reply for now? "We are in the middle of ${intent.typeName()} already, let's continue with the current process."
> > 
> > 
> > 我目前的理解是DU会直接根据expectation把expression识别为trigger IntentReentry，runtime不需要做什么修改，如果理解的不对告诉我一下 @xiaoyunwu
> 
> @XiaoboYuan DU will return the original event for original, can we handle the conversion to ResumeIntent in runtime? It is true that sometime DU can figure out intent is already active based on dialog expectation, but I think not all the time that information is encoded in DE.

好的

**Comment by XiaoboYuan** [comment]
fixed.
只要更新了core里面的ResumeIntent应该就可以了

**Comment by Zeng666666** [comment]
我这里可以了， @yigexu 你试试

**Comment by yigexu** [comment]
我这里还不行 @XiaoboYuan 现在可以测试了吗

**Comment by yigexu** [comment]
@XiaoboYuan expression with slot 应该也提示一下 ResumeIntent。只要是 user 在 intent 中 express 这个 intent，且 DM 为他决定继续当前 intent (而不是其他的行为，比如对比 start over)，我们就需要提示一下。
https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6257c618d31e3de801edb590/version
设置了 expression “test”，“test $int$”。
下面截图说 test2 之后应该也是 “We are in the middle of x already, let's continue with the current process.”
<img width="470" alt="Screen Shot 2022-04-14 at 4 13 18 PM" src="https://user-images.githubusercontent.com/6505755/163343131-208f3b96-6924-495f-be64-f872d7a5a7b7.png">

**Comment by XiaoboYuan** [comment]
这种情况DM无法区分user说的是一个slot的值还是一个intent的意图带了一个slot的值
如果需要这个feature需要DU来区分
@xiaoyunwu @yigexu

**Comment by xiaoyunwu** [comment]
u: buy a ticket
b: what movie
u: buy a starwars ticket.  (this is a normal way of reply for what movie)
to handle that case, we can not do what you suggested. So I will close this.

**Comment by yigexu** [comment]
我们有三种方式触及一个 slot
1. 通过 intent expression
2. 通过 slot update
3。在 intent 中 mention 一个 slot，并且这个 slot 的 type 在 intent 中只出现过一次

采用 #1 和 #3 的回答意味是不同的。如果 user 说的是 #1，那么他的意图就是在要求 intent。如果是 #3，那么你给的 case 才是合理的。
@xiaoyunwu

**Comment by yigexu** [comment]
不过从 bugfix 的角度，可以先这样。

**Comment by xiaoyunwu** [comment]
U r right we should handle update separately
