### ISSUE TITLE
[Feature Request]: Support UDF language control on platform

### ISSUE THREAD

**Issue by yigexu** [framely/community#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Background:
Right now, platform defined Postgres functions can only be wrote in language SQL. Since language SQL only support simple SQL statements and we need transaction (For example: Ordering needs to create and insert stuffs in a transaction.), procedural language should be supported.

Feature request:
1. Add language control on service's function declaration. (Or should we delay this to provider's function implementation?)
2. PostgresSQL support language: SQL, C, PL/pgSQL, PL/Tcl, PL/Perl, PL/Python in standard distribution. For now, we only need SQL, PLPGSQL, and the default language should be SQL.
3. Framely should set UDF's language based on builder's choice.

### Motivation

/

### Describe alternatives you've considered

Only support PLPGSQL.

**Comment by Zeng666666** [comment]
这个是 #144 不？

**Comment by yigexu** [comment]
这个是对 platform control 的 request；#144 是要求辉哥支持 plpgsql (且本来不想对 platform 增加 control)，#144 现在的问题是怎么支持 plpgsql，辉哥那边还有一些额外的操作，所以直接把 language 改成 plpgsql 是不行的。

**Comment by yigexu** [comment]
我们仍旧可以决定选择 alternative，即不增加 control。
