### ISSUE TITLE
[Bug]: test notification

### ISSUE THREAD

**Issue by yigexu** [framely/community#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

**Comment by yigexu** [comment]
test

**Comment by yigexu** [comment]
test

**Comment by Zeng666666** [comment]
what r u testing

**Comment by yigexu** [comment]
notification for myself
