### ISSUE TITLE
[Bug][DU]: NPE

### ISSUE THREAD

**Issue by yigexu** [framely/community#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Behaviour
1. Connect, enter: what kind of main dish do you offer
2. NPE
<img width="978" alt="Screen Shot 2022-03-30 at 4 26 17 PM" src="https://user-images.githubusercontent.com/6505755/160786740-8c5aaa35-fcab-4274-a3ee-bb6ef73e0410.png">

### Where to fix
1. Intent DynamicSuggestion has 
- expression: what kind of $source$ do you offer
- slot: source and target, both DishCategory type.
  - target's ask condition is `restaurantL214.getDishCategory(source!!).size != 0`
2. **NPE raised at target's condition because source is null. Source is null because DU set main dish to slot target instead of slot source**
> Du returned frame events : [FrameEvent(type=DynamicSuggestion, slots=[EntityEvent(value="MainDish", attribute=target)], frames=[], packageName=restaurant002.restaurantL214)]

### Expected Behavior

What kind of main dish do you want? We have blabla

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/intent/61f0b1826a5313c74a2df848

**Comment by yigexu** [comment]
BTW, this might relate to the fact that "main dish" has a space inside. Try "what kind of noodle do you offer" and it runs perfectly. @xiaoyunwu

**Comment by xiaoyunwu** [comment]
https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/intent/61f0b1826a5313c74a2df848
@XiaoboYuan can you take a look at this, I can not commit this one. Complain about:
unknown status code:18446744073709551517
error message:server error in compiler phase : fail to compile or write source code 
 warning: unable to find kotlin-stdlib.jar in the Kotlin home directory. Pass either '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
warning: unable to find kotlin-script-runtime.jar in the Kotlin home directory. Pass either '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
warning: unable to find kotlin-reflect.jar in the Kotlin home directory. Pass either '-no-reflect' or '-no-stdlib' to prevent adding it to the classpath, or the correct '-kotlin-home'
source_code/restaurant002_restaurantC214/restaurant002_restaurantC214.kt:402:79: error: type mismatch: inferred type is Unit but List<TypeVariable(T)> was expected
  public var _rec_spice: PagedSelectable<*> = PagedSelectable<spice>(session, {},
                                                                              ^

**Comment by XiaoboYuan** [comment]
![image](https://user-images.githubusercontent.com/4945408/161877395-66426655-59dc-4981-85ca-4854d7bf4d6b.png)
我这402行是这样的 不知道是不是你们做了改动 这是可以compile的
你那个log 402行的{}有问题
@xiaoyunwu

**Comment by xiaoyunwu** [comment]
right now, it is not compile time error, and it runtime time error. at 416. 
Failed to get reply: java.lang.NullPointerException
	at restaurant002.restaurantL214.DynamicSuggestion$annotations$3.invoke(restaurant002_restaurantL214.kt:416)
	at restaurant002.restaurantL214.DynamicSuggestion$annotations$3.invoke(restaurant002_restaurantL214.kt:366)
	at io.framely.core.LazyEvalCondition.invoke(annotation.kt:41)
	at io.framely.core.LazyEvalCondition.invoke(annotation.kt:38)
	at io.framely.core.ConditionalAsk.canEnter(annotation.kt:102)
	at io.framely.core.AnnotatedWrapperFiller.canEnter(filler.kt:719)
	at io.framely.core.AnnotatedWrapperFiller.done(filler.kt:731)
	at io.framely.core.UserSession.searchForRefocusChild(UserSession.kt:637)
	at io.framely.core.UserSession.tryToRefocus(UserSession.kt:593)
	at io.framely.core.UserSession.kernelStep(UserSession.kt:290)
	at io.framely.core.UserSession.userStep(UserSession.kt:210)
	at io.framely.core.DialogManager.response(execution.kt:94)
	at io.framely.core.DialogManager.response(execution.kt:52)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:108)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)

**Comment by xiaoyunwu** [comment]
https://github.com/framely/framely/pull/732  this should be fixed now.
