### ISSUE TITLE
[Bug]: DU seems case sensitive？DU can only understand low case

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DU 目前对大小写敏感，只能理解小写情况。即使 entity instance expression 的定义是首字母大写，也无法识别与 expression 一模一样的表达，会报错："Sorry, I did not get that."  

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/37056884/161221117-f47e07ae-c0a6-4b8b-a1be-efab2b779475.png">

<img width="1642" alt="image" src="https://user-images.githubusercontent.com/37056884/161221425-b59e5069-06a4-4280-bf07-995ec1419e9c.png">

### Expected Behavior

预期：大小写应该不会干扰 DU 理解

### Use Case

/

### Steps To Reproduce

1. commit
2. try it now, enter query：
   1. movie rec
   2. News Film

<img width="524" alt="image" src="https://user-images.githubusercontent.com/37056884/161222890-e1933701-d126-4a7f-9eb3-5ae6302d47f1.png">

### Label of org.project

tutorial.what_to_watch

### Framely Link

https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent/6242a083052fc81b030dceca

**Comment by yigexu** [comment]
#41

**Comment by Zeng666666** [comment]
@yigexu 我这里没有报错提示：connect error，也没有进入 IntentClarification，我感觉可能是不太一样的

**Comment by yigexu** [comment]
no worry. 都是case sensitive，我贴一下，可以一起看。

**Comment by xiaoyunwu** [comment]
this is fixed in https://github.com/framely/framely/pull/730.
