### ISSUE TITLE
[Bug]: compile error

### ISSUE THREAD

**Issue by yigexu** [framely/community#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

compile error目前在平台的报错如下
<img width="2560" alt="Screen Shot 2022-02-22 at 2 20 49 PM" src="https://user-images.githubusercontent.com/6505755/155087076-9b603e12-fe63-43e0-a7bd-08475e7142ac.png">

debug时希望
1. 信息保持原来的格式 
2. 显式所有这个bot的error
3. 一次commit，error可以被反复查看

其中 <1> 是 debug 的先决条件，因为日志格式中蕴涵了错误位置的信息。
所以希望能先对error message的格式进行一些处理，详见下面xiaoyunwu的comment。

<2><3>暂时还没有讨论完全，可以先不管。

### Expected Behavior

/

### Current Behavior

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/frame/620ca46d6fee3e8aaeb46144

**Comment by xiaoyunwu** [comment]
@jfang137 I think the issue is, we are currently removing new line, and also we are centering it. We should change that for error message.

**Comment by Zeng666666** [comment]
> @jfang137 I think the issue is, we are currently removing new line, and also we are centering it. We should change that for error message.

这个可能有的难度，因为“全局提示：**顶部居中显示并自动消失，是一种不打断用户操作的轻量级提示方式**。”  如果是@yigexu  期望的这种撑满一屏的提示不应该用这个组件；感觉 link 可以满足⬆️的需求。

**Comment by Zeng666666** [comment]
@yigexu “ 显式所有这个bot的error” 是指什么？当程序出错会中止执行并返回报错提示，改好了这个问题，程序会继续执行，所有 bot 的 error 就是当前的报错？

**Comment by yigexu** [comment]
所有是指 commit时compiler给出多少错误就显示多少错误。
过去平台只会给出一条错误内容，或者直接提示commit失败

**Comment by Zeng666666** [comment]
@yigexu 这个可以 close 了吗？
