### ISSUE TITLE
[Bug]: MV SEP 追问 end-user say no 后，不应该进入 confirmation 和 response

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#204]
### Discussed in https://github.com/framely/community/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **Zeng666666** March 12, 2022</sup>
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Agreement

SEP explicit confirmation, 在 SV、MV x <= min 时，default strategy 都是 exit intent
  
  
## Current Behavior

现在好像还不行，test case：MV SEP 空值填槽https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6228443a068261d652db7e64/test_case
<img width="481" alt="image" src="https://user-images.githubusercontent.com/37056884/161376836-1b21c960-2aeb-46ff-8be6-2d1e2184a8d1.png">

  

## History

1. MV SEP 追问 explicit confirm 后，如果 end-user say no，则会带着空值直接进入 confirmation 和 response：

![image](https://user-images.githubusercontent.com/37056884/158011199-9315e20f-a339-49c1-810f-992b7b8514c9.png)

2. MV SEP 追问 implicit confirm 后，如果 end-user say no，则会带着空值直接进入 confirmation 和 response：

![image](https://user-images.githubusercontent.com/37056884/158011805-effaa5a2-2be4-4d75-9627-5b5707c10815.png)

### Expected Behavior

【提议 1 】MV SEP 只有 Explicit Confirm

1. 我们对于 implicit 与 explicit 已有明确的定义，目前的处理方式会让 builder 产生 implicit 定义不一致的困惑；
2. 从实际场景出发，MV 进入 SEP 时，builder 只能定义 explicit confirm，既可以给 end-user 一个特别的提示，也可以不因 implicit 的定义进入无限循环，还能保证 implicit 一致性。

【提议 2 】MV SEP 追问，end-user 直接 say no，应 follow ZEP default strategy：exit。

### Use Case

Test Case：https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622adde22fb46d1befee2232/test_case

![image](https://user-images.githubusercontent.com/37056884/158011911-daa0bcd2-d33e-472b-9b5f-d84cfc513810.png)

### Steps To Reproduce

see test case

### Label of org.project

test001.test_zep

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622adde22fb46d1befee2232/intent/622addfa2fb46d1befee223a/slot/622addff2fb46d1befee223e

### Additional information

_No response_</div>

**Comment by XiaoboYuan** [comment]
"SEP explicit confirmation, 在 SV、MV x <= min 时，default strategy 都是 exit intent"
我理解的是: sv或者mv x < min时exit intent
runtime目前是认为x == min是一个合理的值，x < min才不合理
@Zeng666666 @xiaoyunwu

**Comment by xiaoyunwu** [comment]
X == min should be considered as good.

**Comment by XiaoboYuan** [comment]
@Zeng666666 
那么这个issue里描述的可以认为是合理的了对吧？
如果min=1的话应该会exit intent

**Comment by Zeng666666** [comment]
目前的表现是不恰当的，我理解无论如何也不能空值填槽，而是应该 exit intent。

我又仔细看了一下，这里似乎有一个 gap：Min/Max 控制的范围是哪里？从 Platform 前端的定义展示，Min/Max 是定义在了 MV-Prompt 上。目前这个 case 是在回答 Prompt 的追问时进入 SEP，还没有进入到 MV-Prompt。我理解进入 MV-Prompt 后才会开始 Min/Max 这个范围限制？不知这里理解的对不对？

如果不对的话，感觉 Platform Min/max 的定义位置应该有所修改。这个场景的表现也应当重新考虑一下：

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/37056884/162358600-589b5ab7-73fc-48fd-9c9c-740a564ed18b.png">

**Comment by xiaoyunwu** [comment]
我理解进入 MV-Prompt 后才会开始 Min/Max 这个范围限制？不知这里理解的对不对？ i think it is correct

**Comment by Zeng666666** [comment]
我知道了，这里面我有一个理解是不对的。。。我过去一直认为 slot 必须有值才会进入下一个 slot，原来“多值的 slot“ 不填也是可以继续往下走的。这个理解是对的吗？

如果是对的，那我这里的定义就不对了，我现在把 Min 改成了 1，然后还是按照这样的顺序，现在是会循环追问，这个表现是对的吗？ @XiaoboYuan @xiaoyunwu 

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/37056884/162371240-b90ccfb5-0f81-4646-8b34-03981592dd0b.png">

**Comment by xiaoyunwu** [comment]
@XiaoboYuan this is a bug ?

**Comment by XiaoboYuan** [comment]
@xiaoyunwu @Zeng666666 
图里面的这个表现是个bug，这个bug是因为DU在expectation存在hasmore和confirmation的情况下给了hasmore的No
如果要拒绝mv，这个表现就是对的，因为mv没有达到min会循环问
如果拒绝confirmation，DU给一个confirmation的No，那么runtime会abort intent

**Comment by XiaoboYuan** [comment]
> 我理解进入 MV-Prompt 后才会开始 Min/Max 这个范围限制？不知这里理解的对不对？ i think it is correct

这个是对的？这个跟我之前的理解不一样，我之前是认为mv这个slot整个适用于min/max限制，因而空list是合理的值
@xiaoyunwu

**Comment by XiaoboYuan** [comment]
我一直是把prompt和mv prompt当作一个概念处理的，我感觉空list也许是一个合理的需求

**Comment by yigexu** [comment]
minmax应该作用在整个 mv 上，我一直是这么理解的，以及（可能是由于我这个理解导致的）我们存在一些情况需要 mv.size == 0，比如购物车的某个 upsale 单元  (对应 maindish、sidedish slot) 什么都不选。

如果这个地方有很大的歧义能不能考虑一下通过交互设计解决？

**Comment by yigexu** [comment]
@xiaoyunwu 我记得我问过这个问题，在 discussion 中你选的是：考虑 SEP + explicit confirm，这里的问题是 user 的 no 是什么 no => SEP confirmation 的 no

> @xiaoyunwu @Zeng666666 图里面的这个表现是个bug，这个bug是因为DU在expectation存在hasmore和confirmation的情况下给了hasmore的No 如果要拒绝mv，这个表现就是对的，因为mv没有达到min会循环问 如果拒绝confirmation，DU给一个confirmation的No，那么runtime会abort intent

**Comment by Zeng666666** [comment]
是的呢，如果 Min/Max 是作用在整个 MV 上的话，交互确实是需要修改的，应该把 Min/Max 单独提出来，而不是定义在 MV-Prompts 上，这个交互的表达是非常有歧义的 @xiaoyunwu
