### ISSUE TITLE
[Bug]: Implicit behavior is not consistent 

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

关联 Discussion #131 把 Implicit 的问题单独提出来

现在 【 MV Hard SEP 】 时，Implicit SEP 表现如下，导致：
1. 从 platform 视角：implicit 表现不一致，我们没有办法告诉 builder 什么是 implicit;
2. 从 builder 视角：定义了 SEP 却没有展示出来；
3. 从体验来看，这里的 expectation 是什么呢？

![image](https://user-images.githubusercontent.com/37056884/161377116-532062d0-9ab0-4ee3-9530-b1a0531e833d.png)

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/37056884/161377952-3414cf18-a087-4558-9b7e-6836fa88793e.png">

### Expected Behavior

【预期】保证 implicit 一致性。

【提议】似乎可以先前端限制在 MV 场景定义 implicit SEP，这样 MV 场景 SEP 时总是会进行 explicit SEP。

### Use Case

/

### Steps To Reproduce

Test Case：mv-sep-implicit

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/37056884/161377870-a5e3eb77-4495-4547-8f81-a528e1df259b.png">

### Label of org.project

test001.test_sep_mv_copy0402

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/624819990b113cc1064f4015/test_case

**Comment by Zeng666666** [comment]
根据对 MV 的最新认知，MV 场景下似乎是不应当有 Implicit SEP 的：

首先，SEP 指 single entry prompt，即 Hard VR resultset 只有一个条目时的表现。

其次，Single Value 时，我们认为 slot 必须 pick 一个 value 才可以，否则 exit。因此，end-user 别无他选，必须选择或退出，Implicit 由此而来。

但 Multi Value 就不是这样了，MV 根据 Min 来判断最小值，可以从 0 开始取值：
- 若 Min 设定为 0，则 SEP implicit 没有任何意义；
- 若 Min 设定为 1，则 SEP implicit 意义同 SV；
- 若 Min 设定为 n，则 SEP implicit 不一定合理，因为 list 必须填满 n 个 value，否则 exit。但 value 是否满足条件取决于 builder 业务逻辑，在 VR 里似乎不应该有这类判断。

**Comment by xiaoyunwu** [comment]
@jfang137 can you hide the implicit confirmation on the platform only for now? Just frontend hiding.

**Comment by jfang137** [comment]
好的

**Comment by xiaoyunwu** [comment]
@jfang137 you hide the right thing?

**Comment by jfang137** [comment]
我隐藏了confirmation中的implicit,我revert一下
