### ISSUE TITLE
[Feature Request]: try-it-now on readonly chatbot

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now, we can view the public chatbot, but we can only try it by clone it to our org first. It is wasteful both for builder and ourselves. Can you enable try master version on the read only (or master equivalent) by all users instead having to create instance in dev (springboot) environment before builder can try it?

### Motivation

reduce the effort for builder to experience something.

### Describe alternatives you've considered

n/a

**Comment by jfang137** [comment]
可以放开public bot try-it-now. lang上的merge行为会更新这个实例，struct的propagating理论上也应该更新该实例，我们得考虑下propagating的过程如果出现lang instance 的compiling error该是怎样的反馈？单纯的抛错，或者回滚struct的merge操作？

**Comment by xiaoyunwu** [comment]
I think we should just remember the compiled chatbot linking to last merged version, and use that directly.

**Comment by jfang137** [comment]
@XiaoboYuan  有个疑问，同一个chatbot, A user在A的分支上提测，B user在B分支上提测，更新到try-it-now的内容现在是不是会相互覆盖的？我看调code gen时没有哪个参数是用来区分user的?

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/161916275-5b083ded-6842-4e2c-9122-eb31a0aebfdb.png)
是不是可以用这个字段？
