### ISSUE TITLE
[Bug]: Sometimes language branch disappears

### ISSUE THREAD

**Issue by yigexu** [framely/community#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 之前遇到过这种问题： @hisunnymay 发链接给我，打开语言分支消失。但是过了一段时间点进去又可以了，
2. 这次是在entity spice 的 en 切换到 struct 后发生的。
2.1 中间弹了几个窗
<img width="1026" alt="Screen Shot 2022-04-06 at 9 27 33 AM" src="https://user-images.githubusercontent.com/6505755/161877355-0ae066ce-840f-4e79-ab89-49a43655b3f3.png">
2.2 然后页面语言状态消失
<img width="1484" alt="Screen Shot 2022-04-06 at 9 25 30 AM" src="https://user-images.githubusercontent.com/6505755/161877401-79c5c87f-0458-4e8b-9160-958a96ce7851.png">
2.3 下面的 entity 列表中应该有 spice，也没显式出来（但是 <1> 的时候页面看起来大致正常，所以不是很确定这两件事是不是一个问题引起的，尽管看起来很像）

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b806ff5c77cdfc256ce4/entity

**Comment by jfang137** [comment]
做了token失效自动返回登录页面的处理
