### ISSUE TITLE
[Bug]: AbortIntent response does not work that well

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

io.framely.core 中的 AbortIntent Response 有如下定义：

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/37056884/161981369-544f390c-d51d-485c-926e-f51aac6f9b06.png">

其中 $alias$ 应该在过去也不 work，因为它其实是在引用 AbortIntent 的 alias，而不是 slot intent 的 alias：

<img width="529" alt="image" src="https://user-images.githubusercontent.com/37056884/161982162-e545380c-4f50-48da-9b11-0a9b32e1991b.png">

但目前好像没有 function 可以直接使用去引用 slot intent 的 alias，我们应该创建一个 native function 吗？

### Expected Behavior

AbortIntent 的 response 可以引用 slot intent 的 alias

关联 issue #75 

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/37056884/161982912-a1d9cbd5-859b-40ff-afcf-66d503b22b79.png">

**Comment by xiaoyunwu** [comment]
@XiaoboYuan @Zeng666666  how do we refer the type of the intent, what we really want to render is the name of type of intent.

**Comment by XiaoboYuan** [comment]
fixed

**Comment by Zeng666666** [comment]
checked
