### ISSUE TITLE
[Bug]: Change sv~mv, condition operator shows code

### ISSUE THREAD

**Issue by yigexu** [framely/community#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

表现
1. 声明一个 slot， sv 或者 mv
2. 为这个 slot 配置 confirmation condition，选择好 operator
3. 将 slot type 改成 mv 或者 sv
4. confirmation condition 显式数字，看起来是 operator 的 code(?)

预期
1. 如果是相同的 operator，比如 sv、mv 都支持 not empty，最好能直接生效
2. 如果是一者有另一者没有的，比如 mv 不支持比大小，可以考虑和找不到 slot 时一样，定义成 NameMissing (我们有更好的choice吗？)

https://user-images.githubusercontent.com/6505755/162136294-54cbbd33-0669-45dc-92b4-b7b0ae6977a6.mov

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

会修改，不一定还有confirm的设置：https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/622019f92b38932409a18edd/intent/624d52410521bff0a23bc863?tab=3

**Comment by Zeng666666** [comment]
NameMissing 本身也是不太恰当的表现，所以并不应该当作一种合理的体验。
如果是不支持的，感觉可以考虑清空让 builder 重新定义。

**Comment by jfang137** [comment]
sv 和 mv的 not empty是两个不同的operation.

**Comment by jfang137** [comment]
> NameMissing 本身也是不太恰当的表现，所以并不应该当作一种合理的体验。 如果是不支持的，感觉可以考虑清空让 builder 重新定义。

清空行为应该是builder主动触发的。最好是以某种途径展示operator无效

**Comment by Zeng666666** [comment]
@jfang137 在修改 是否为多值 的时候，可以给 builder 一些提示吗？还是在 confirmation 处提示？

**Comment by yigexu** [comment]
@jfang137 我知道是两个不同的 operator，但是它们都用的是一种表达 （not empty），并且也确实都可以说是在检查有没有值。有办法在 sv 的时候去检查 null，在 mv 的时候去检查 isEmpty() 吗？
我感觉让 builder 切换一次，对他对系统的理解要求有点高。他要有是不是null的概念，还要有sv和mv实现是null和collection的概念。我感觉选 function invocation 的模式，应该尽量不让他们知道这么多

**Comment by jfang137** [comment]
> @jfang137 在修改 是否为多值 的时候，可以给 builder 一些提示吗？还是在 confirmation 处提示？

修改为多值时检查大量数据，性能上损失太大了

**Comment by jfang137** [comment]
有办法在 sv 的时候去检查 null，在 mv 的时候去检查 isEmpty() 吗？这句我没太懂。
