### ISSUE TITLE
[Feature Request] refine condition

### ISSUE THREAD

**Issue by yigexu** [framely/community#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. 目前 uncertain value 没有定义。应该考虑隐藏掉

2. operator 是 is type of 时，value 显示的是下拉菜单，且没有选项。应该显示该 bot 定义过的所有类型。（还有一种方案是显示文本编辑框，预期 builder 填一个 type 的 code expression）
<img width="2093" alt="Screen Shot 2022-04-07 at 9 17 12 AM" src="https://user-images.githubusercontent.com/6505755/162100802-72fe6e47-54aa-4ab3-a187-ebca16ac61dc.png">

3. conditions 选择 frame slot 作为一个整体时，operator 应该只能选到 not empty、is type of，如果想要比较 frame 内的某些 slot，应该选择 code expression 模式。
<img width="2121" alt="Screen Shot 2022-04-07 at 3 02 03 PM" src="https://user-images.githubusercontent.com/6505755/162139702-5b5bd7ed-2a5a-4a1b-a620-b451c16bc81f.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by yigexu** [comment]
@xiaoyunwu what do you think?

**Comment by jfang137** [comment]
#2 目前的选项应该是前面变量类型的子类，你添加子类试一下 @yigexu

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/162144858-98296e45-d633-4834-9848-54f9287fa33a.png)
![image](https://user-images.githubusercontent.com/16040960/162144920-0a17b15f-54a1-4191-bd8e-79f0de635bdc.png)

**Comment by yigexu** [comment]
get

**Comment by Zeng666666** [comment]
@yigexu condition 会应用在很多地方，比如 confirmation、state update、response，这里指的是 confirmation 吗？

**Comment by yigexu** [comment]
指所有地方

**Comment by Zeng666666** [comment]
@yigexu 那就需要全盘考虑一下了，已经支持的操作，一定都是有原因的

**Comment by yigexu** [comment]
@Zeng666666 有支持的case可以提，或者当初#1、#3本来是支持什么场景？

**Comment by Zeng666666** [comment]
@yigexu  uncertain value 是早期的处理，后来咱们做了 dont care 这个应该就失效了，我记得你和 xiaoyun 讨论过这方面的内容：https://naturali-io.feishu.cn/docs/doccnRejjGEiQ7NuPM7njbo6FKg

**Comment by xiaoyunwu** [comment]
for #3, do we have to disable things to make code expression work?

**Comment by yigexu** [comment]
这不是提 #3 的原因。
#3 希望禁止对frame整体比较（包括==,!=, >, <, >=, <=, in, !in, 全等）是因为这个事情不太合理。frame中可能有任何东西，包括entity、再嵌套一个frame。如果 condition 是 frame，operator 是 equal （或者其他比较操作）应该怎么比较？需要builder自己定义吧？

**Comment by xiaoyunwu** [comment]
Understood now. SGTM.

**Comment by yigexu** [comment]
#1 呢？uncertain value 过去指的是什么？

**Comment by xiaoyunwu** [comment]
we should remove #1, that is don't care.

**Comment by yigexu** [comment]
@jfang137 那这个应该可以了。
For 1. 去掉/隐藏掉 uncertain value
For 3. 当 condition 选择的 slot type 是 frame 的时候，隐藏掉除了 not empty, is type of 之外的操作符 (也就是==,!=, >, <, >=, <=, in, !in, 全等)。

**Comment by jfang137** [comment]
好的
