### ISSUE TITLE
[issue]: Should we support entity inheritance

### ISSUE THREAD

**Issue by yigexu** [framely/community#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Issue
目前 entity 采用的是将 child 的 instance 增加到 parent 下，也就是说在实现层面它们没有继承关系。
然而我们日常沟通中，不少人都会把它当做存在继承关系来思考，包括：
1. restaurant [解决方案](https://naturali-io.feishu.cn/mindnotes/bmncnMiw7UzCApl8NiUxw0rs7xf)  的设计
2. condition 中可以选择两个 entity 的继承关系，然而 compile 会抛错：
```
error: incompatible types: Child and Parent
      parent!! is playground.test0406.Child -> _confirm_this_0
```
3. #214 的讨论

parent 和 child entity 之间的关系到底应该怎么理解？有？无？还是 builder 感知不到的等价？
我们可否支持 entity 继承？

## Alternative / If not support
1. 把 <2> 当做 bug 修了，也就是禁止平台上 entity 类型选到 is type of

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
condition 中可以选择两个 entity 的继承关系，然而 compile 会抛错： what do you mean? @yigexu

**Comment by yigexu** [comment]
1. 创建 entity：Child、Parent，让 Parent 是 Child 的 parent entity
2. 创建 intent/frame，has a slot named parent，type Parent
3. 找一个 condition，选择 operator is type of, 左操作数 slot parent，右操作数 Parent
@xiaoyunwu
