### ISSUE TITLE
[Bug]: Change 'Condition undefined' to True

### ISSUE THREAD

**Issue by yigexu** [framely/community#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当平台上增加condition，但是没有选择任何内容时，会显示为 condition undefined。
但是我们实际是增加了一条在平台和runtime都可以正常使用的 condition，它的结果为 True。
因此需要将 condition undefined 显示为 True。

<img width="1371" alt="Screen Shot 2022-04-08 at 9 26 18 AM" src="https://user-images.githubusercontent.com/6505755/162345259-b349cf2a-d3e3-4e2f-967e-42d4bcbcf9ac.png">
<img width="1448" alt="Screen Shot 2022-04-08 at 9 26 10 AM" src="https://user-images.githubusercontent.com/6505755/162345232-3798b370-a63b-44ef-8e32-f8ed260f523e.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant

**Comment by Zeng666666** [comment]
这里大概需要确定一下，是否可以有一个“没有条件”的条目存在：
- 如果可以，那 undefined 可以命名为 Default，且列表页只能有一个 Default 条目（目前是不是只有 confirmation 涉及这个问题呢？）
- 如果不可以，就需要强制 builder 选择 condition，即点击 SAVE 的时候，出提示信息。

**Comment by jfang137** [comment]
没法强制，实体在定义condition之前就心经被创建了

**Comment by yigexu** [comment]
1. 是针对所有 condition
2. 显示 True 比较合适，因为其他的地方显示的都是 condition (boolean expression)。

**Comment by Zeng666666** [comment]
@jfang137 截图的例子是弹窗，按理说应该没有被创建？

@yigexu 所有的 condition 不太适合，response branching 中的 condition 必须被定义才有意义，ask condition 中的 condition 同理。

**Comment by jfang137** [comment]
弹窗的case确实没有，response/state update这种跳转之后就已经被创建了

**Comment by Zeng666666** [comment]
嗯，response/state update 这种确实是个问题，不过我目前也没有想到什么太好的想法，不过这个在见人之前肯定是要看看怎么优化一下

**Comment by yigexu** [comment]
可以针对 ask condition 和 branching 限制不能创建；如果创建的话，就要显示成 True，不管是什么位置的condition。
我主要关心的是创建之后，因为有时候没想好怎么设计会先点一个branch之类的东西占个位置，还有的时候会用来debug。

对于限不限制我都可以。

**Comment by xiaoyunwu** [comment]
I think we should just change the messaging to be: Condition
undefined(default to true) instead of  Condition undefined.
There is not very little gain to touch it. We should focus on make thing
works and update messaging.

**Comment by yigexu** [comment]
@jfang137 

> I think we should just change the messaging to be: Condition undefined(default to true) instead of Condition undefined. There is not very little gain to touch it. We should focus on make thing works and update messaging.
