### ISSUE TITLE
[Feature Request]: Support adding agents through Chatwoot

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary
1. 允许Chatwoot admin在Chatwoot中手动添加agent
2. 目前仅为Framely Org owner创建在chatwoot的administrator账号

#### 现状
1. 目前chatwoot的agent只能从`Framely-org-Internal Members`中自动导入，无法在chatwoot中手动添加agent（手动添加即：点击下图所示的`Add Agent`）
2. 目前我们会为所有的Internal Members创建在chatwoot的administrator的账号

![image](https://user-images.githubusercontent.com/95261974/162382258-c033d7f6-8b8a-457b-83f7-e6b40110ee32.png)

#### 分析
考虑到builder和人工客服是两种不同的角色
- builder负责build chatbot/component/provider
- 人工客服负责在chatwoot上回答end-user的问题

`Internal Members`包含的应该只是builder角色，`Chatwoot-agents`包含的是人工客服的角色，所以为了明确各个平台的分工和管理，人工客服应该是在chatwoot中手动添加的，而不是通过`Internal Members`导入的。

除此之外，role为`member`的Internal Members不应该有chatwoot的admin的权限，所以不应该为所有的`Internal Members`创建在chatwoot的administrator的账号。对于`member`应该由chatwoot-admin导入，或者创建agent(非admin)的账号。

![image](https://user-images.githubusercontent.com/95261974/162383182-6707092c-2f30-4872-a06c-784a0488b459.png)

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
Make sure you are the org owner or have correct permission.

**Comment by hisunnymay** [comment]
@xiaoyunwu 
> 1. you are the org owner

No, I am not the org owner

目前创建Chatwoot的时候默认的org owner是：BotAgent1。如果你说的是Chatwoot里的org owner，那么我们目前没有用Framley org owner的账号去创建Chatwoot org owner


> 2. have correct permission

Yes, I have correct permission

Chatwoot agent有两种role：
- agent：只能访问它所在的inbox和team的会话
- administrator：能访问所有的inbox和team中的会话，能修改所有inbox和team的设置，能修改org中除了自己以外所有agent的role

因为我们是为Framely Org owner创建在chatwoot的administrator账号，所以我认为我们为builder提供了correct permission

**Comment by Zeng666666** [comment]
这个是修好了吗？现在可以添加的

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/37056884/163801186-ca875e6b-5c63-4c26-8ff4-3ddb22b52f37.png">

**Comment by hisunnymay** [comment]
@Zeng666666  补充：#1的background

目前在chatwoot中添加agent，在chatbot中开启chatwoot会报错：`https://chatwoot.naturali.io/platform/api/v1/users/10 401 Unauthorized`

1. Add an agent in chatwoot

![origin_img_v2_c5c5f974-f1c8-4889-8e10-51570e1e913g](https://user-images.githubusercontent.com/95261974/163904330-2560fad2-7962-4e4c-bfad-27ad539b8c50.jpg)

2. Enable chatwoot in a new chatbot

![origin_img_v2_e6f9e737-b6d3-416d-b15d-e66a0132a86g](https://user-images.githubusercontent.com/95261974/163904360-b5f6e744-07bc-4cea-9d68-e85a7a41a559.jpg)

**Comment by Zeng666666** [comment]
> @Zeng666666 补充：#1的background
> 
> 目前在chatwoot中添加agent，在chatbot中开启chatwoot会报错：`https://chatwoot.naturali.io/platform/api/v1/users/10 401 Unauthorized`
> 
> 1. Add an agent in chatwoot
> 
> ![origin_img_v2_c5c5f974-f1c8-4889-8e10-51570e1e913g](https://user-images.githubusercontent.com/95261974/163904330-2560fad2-7962-4e4c-bfad-27ad539b8c50.jpg)
> 
> 2. Enable chatwoot in a new chatbot
> 
> ![origin_img_v2_e6f9e737-b6d3-416d-b15d-e66a0132a86g](https://user-images.githubusercontent.com/95261974/163904360-b5f6e744-07bc-4cea-9d68-e85a7a41a559.jpg)

明白了，复现了。之前是因为 toturial org 的 chatbot 都开启了 chatwoot，所以始终没有触发这个报错。现在新创建了一个，确实是这样。

**Comment by hisunnymay** [comment]
Checked.
