### ISSUE TITLE
[Bug]: Why can I clone chatbot in test001

### ISSUE THREAD

**Issue by yigexu** [framely/community#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 我没有 test001 的权限
<img width="370" alt="Screen Shot 2022-04-11 at 5 19 11 PM" src="https://user-images.githubusercontent.com/6505755/162707634-3f944afd-fc81-413a-b953-118326bca27c.png">

2. 我也没有 chatbot 的权限
https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622adde22fb46d1befee2232/intent/622addfa2fb46d1befee223a/slot/622addff2fb46d1befee223e
<img width="1814" alt="Screen Shot 2022-04-11 at 5 20 10 PM" src="https://user-images.githubusercontent.com/6505755/162708057-5aa993ed-3986-4a3f-a734-5b7239fa30c9.png">

3. 【问题一】但是我可以看到 chatbot、也可以 clone 到我自己的 org
4. 【问题二】当我第一次 clone 到某个 org 的时候 （就是这个 org 范围内从来没有被 clone 过这个bot）会出现；第二次就没有问题了。
https://user-images.githubusercontent.com/6505755/162708610-9804e3c1-0d9f-4582-87e8-fd76efc9c3a9.mov

预期
问题一：我认为我应该看不到、也无法 clone 这个chatbot
问题二：如果 fix 问题一 就不存在了，但是为什么会发生这个还是比较奇怪

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

test001

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622adde22fb46d1befee2232/intent/622addfa2fb46d1befee223a/slot/622addff2fb46d1befee223e

**Comment by yigexu** [comment]
@Zeng666666 你知道我在 test001 的权限是什么吗？是我看到的这样吗

**Comment by Zeng666666** [comment]
问题二，我也遇到了，clone 后，language 会显示 id，切换会有报错提示，刷新后会变正常 @jfang137 

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/37056884/162711032-817cb41e-7512-4322-b142-d6a5d0347133.png">

**Comment by jfang137** [comment]
好的

**Comment by jfang137** [comment]
问题二有什么必现的路径吗。我clone了很多次，没办法复现
@yigexu @Zeng666666

**Comment by yigexu** [comment]
我感觉关键的就是 被 clone 去的那个 org，之前要没有 clone 过这个 bot

**Comment by yigexu** [comment]
@Zeng666666 你还可以复现吗，我似乎不行了...

**Comment by Zeng666666** [comment]
找到了，就是得找一个没有 clone 过的，有没有权限的 org 都可以复现。

可以用我的账号，去 clone Demo org 中的 chatbot（我试过最后一个，是下面这个图的情况，还有前两个 chatbot 可以测试）

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/37056884/163095076-e8fa6f66-8c02-470f-b550-ead55e77d5cf.png">

**Comment by Zeng666666** [comment]
补充，应该是用我的账号，clone Demo org 中前两个 chatbot 到 test001 org 内

**Comment by jfang137** [comment]
按照你说的还是没有复现，我找了怀疑的点进行了优化，稍后可以看看还会不会复现

**Comment by Zeng666666** [comment]
好的

**Comment by Zeng666666** [comment]
最近的 clone 没再出现这个问题了，先 close 了
