### ISSUE TITLE
[Bug]: Sidebar disappears

### ISSUE THREAD

**Issue by yigexu** [framely/community#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 从某处复制 chatbot 链接
> like 我从浏览器地址栏复制了一下：https://framely.naturali.io/org/625632e6f7970446e380ad98/agent/62563448f7970446e380ad9b/intent?page=0&imported=false&search=
2. 点击，进入对应的页面，但是 sidebar 没有被加载
<img width="1082" alt="Screen Shot 2022-04-13 at 3 20 22 PM" src="https://user-images.githubusercontent.com/6505755/163121648-947c9e34-0fba-4213-8c68-881df6026461.png">

### Expected Behavior

完整加载整个页面

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant

**Comment by jfang137** [comment]
@yigexu 看看还有问题没
