### ISSUE TITLE
[Bug]: clone provider, deploy returns status code 500

### ISSUE THREAD

**Issue by yigexu** [framely/community#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. clone restaurant002/restaurantP214 为 restaurant002/clone
2. deploy
3. 
前端显示：Request failed with status code 500
network 抓到：msg: "runtime error: invalid memory address or nil pointer dereference"

### Expected Behavior

不知道我有没有漏掉什么，如果没有应该能正常 deploy

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /clone 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/62568966f7970446e3810636/frame?page=0&imported=false&search=

**Comment by jfang137** [comment]
修了一个指针错误，后面还提示了sql语句的错误

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/163138623-60a203c9-2818-49c3-b3e1-4ed650d2a444.png)

**Comment by yigexu** [comment]
这个报错是因为 db 那边没有把真正的函数声明（平台上的 function query）写进去。你现在看到的都是 @hcheng13 生成的模版。
![163138623-60a203c9-2818-49c3-b3e1-4ed650d2a444](https://user-images.githubusercontent.com/6505755/163297719-c418b985-695f-4f31-82c2-e28dc6c22839.png)

**Comment by yigexu** [comment]
截图的报错实际上应该是：
``` sql
CREATE OR REPLACE FUNCTION "clone"."getDish"(locate_param text) RETURNS TABLE(data json) 
    SET search_path="restaurantP214"
AS $BODY$
    SELECT row_to_json(data) from (select target from "CategoryDish" where source = locate_param) as data;
$BODY$;
LANGUAGE SQL;
```
对应平台上的 function query
<img width="598" alt="Screen Shot 2022-04-14 at 9 53 36 AM" src="https://user-images.githubusercontent.com/6505755/163298443-94578e65-269f-4da6-9d96-cc4c3a02f8a1.png">

可以看一下是不是真的把 query 传给 db 那边了
