### ISSUE TITLE
[Bug]: Omnichannel login every session？

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题：创建 Omnichannel chatbot，第一次绑定手机之后，每次对话都需要先绑定手机号，才能对话：

<img width="743" alt="image" src="https://user-images.githubusercontent.com/37056884/163135618-d67310e9-21d9-46a8-abd3-d9dbb81cd5d5.png">

### Expected Behavior

Omnichannel：

end-user 与 channel 对话时，chatbot 根据 channelType、userID、channelLabel 可以唯一确定一个 end-user 是谁，因此：
- 若 end-user 没有绑定过手机号，需要进行绑定；
- 若 end-user 绑定过，则可以直接对话，不需要再次绑定；

end-user 的“多个 channel”或“同一 channel 的不同 label”可以绑定在同一个手机号上，并识别为同一个用户。

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62568336f7970446e380f036/intent?page=0&imported=false&search=

**Comment by Zeng666666** [comment]
【问题】End-user 第一次绑定手机号后，之后的每一次都能绑不同的手机号，且可以成功。

【预期】从逻辑讲，Omnichannel 时，end-user 需要把不同的 channel 绑定在同一个手机号上，这样系统才能知道这些用户是同一个用户。我们现在暂时不需要支持修改手机号这类逻辑，但是需要确保绑定过的 end-user 下一次登录时输入的是已绑定的号码。

<img width="715" alt="image" src="https://user-images.githubusercontent.com/37056884/163308811-71a4197b-5c2a-4d5d-9876-5662b418dc50.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/37056884/163308871-1f6361b2-9aca-43aa-9109-6c6fd0ff4a15.png">

**Comment by hisunnymay** [comment]
@Zeng666666 出现这种情况的原因应该是：我们对于Channel：Wechat official account（WPA）没有支持redis，目前存储方式是用的缓存，因此过一定的时间后，缓存被清除后，end-user之前的绑定信息会丢失，所以这时end-user需要重新绑定手机。

要实现Expected Behavior的话，可能需要 @hcheng13 为WPA支持redis

**Comment by Zeng666666** [comment]
那其他 channel 有支持 redis 吗？
现在没有过一定时间，是只要 close session，就需要重新登录。

**Comment by hisunnymay** [comment]
@Zeng666666 try it now有支持，但try it now 不支持测试绑定账户的功能

我理解的Omnichannel的设计是基于session的：绑定同一个账号的end-user会接入同一个session，当session结束后，账号不会被保留。因此session结束之后，end-user再给channel发消息的时候，会创建新的session，end-user需要重新绑定账户。

**Comment by hisunnymay** [comment]
基于这个理解的话，Omnichannel确实需要login every session

**Comment by Zeng666666** [comment]
我感觉 Omnichannel 如果是 非 web 的 channel 时不应该基于 session，web channel 可以 debate。GUI 也如此，另好比我们在 facebook 和其他的 chatbot 对话，每次对话，他都知道是我

**Comment by hisunnymay** [comment]
@Zeng666666 “每次对话，他都知道是我”这或许和建立用户系统有关系，在Single channel也可以支持“每次对话，他都知道是我”。比如：每次我用同一个淘宝账号和客服聊天，客服都知道是我

所以“每次对话...”不是在Omnichannel特有的功能，我们不该在Omnichannel的层面来支持的，应该是在类似于用户系统的层面支持？

**Comment by Zeng666666** [comment]
这个 issue 有两个问题：
1. Omnichannel 不应该是 per session login
2. 如果 end-user 绑定过手机号，之后的每一次不能绑定不同的手机号（如果不允许修改的话）。

**Comment by hisunnymay** [comment]
@Zeng666666 我问了一下kui，Omnichannel的IUserProfile是存储在session中的，如果session被close，那么user填写的IUserProfile就没有了。如果我们要处理issue的那两个问题，我们可能需要把IUserProfile存储在redis中。

我们需要支持把IUserProfile存储在redis中吗？

**Comment by Zeng666666** [comment]
@hisunnymay 先走通 chatwoot 端到端体验，再弄这个吧。chatwoot 优先级最高，我们可以先把 multichannel 的体验做对，再做这个。

**Comment by hisunnymay** [comment]
@Zeng666666 好的👌

**Comment by xiaoyunwu** [comment]
For now, let's assume omni channel behavior is a application level construct, we will close this for now. If there are emerging feature request to runtime/platform, we will come back to it again. @Zeng666666 @hisunnymay
