### ISSUE TITLE
[Bug]: Click save should only save once

### ISSUE THREAD

**Issue by yigexu** [framely/community#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题：
frame level confirmation，点击 save
我点击的时候应该是手抖了一下，结果创建出多条

预期：
一个窗口无论怎么点 save 都应该只 save 一条

https://user-images.githubusercontent.com/6505755/163505347-bf21082f-0b57-4877-93ba-e4ad77ff747c.mov

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

playground / SlotUpdate

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6258ce21d31e3de801ee07ac/intent/6258ce2fd31e3de801ee07b1?tab=3

**Comment by jfang137** [comment]
这个修了。一会我再过一下，看看哪些遗漏了

**Comment by yigexu** [comment]
@jfang137 ok，如果你觉得好了可以在这里回复一下

**Comment by jfang137** [comment]
这个已经修复了

**Comment by yigexu** [comment]
@jfang137 
https://user-images.githubusercontent.com/6505755/165876995-3a3a3997-4545-456d-a043-d54fe482e252.mp4

**Comment by xiaoyunwu** [comment]
@***@***.*** ***@***.***> Did you refresh?

**Comment by yigexu** [comment]
目前 chrome 和 safari 都表现正常，微信自带的浏览器会有一些 peculiar 的表现，但是考虑到它要求用户每次打开页面重新登录，很可能不会被用于正式使用，因此暂时关闭。我们也可以等到需要系统测试不同浏览器的表现时在 reopen 这一问题。
