### ISSUE TITLE
[Bug]: Missing frame after import

### ISSUE THREAD

**Issue by yigexu** [framely/community#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. [order_service](https://framely.naturali.io/org/60ed2ee7e80bdfd60aaa7057/agent/61ea65bcdca23d9c7fd31c16/frame?page=0&imported=false&search=) 存在 frame RowContainerInt
<img width="576" alt="Screen Shot 2022-04-19 at 9 20 14 AM" src="https://user-images.githubusercontent.com/6505755/163901279-d80367f2-7f2f-47a6-b2e1-251dc9dc42e5.png">

2. [restaurantL214](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d0ff5c77cdfc255d0d/frame?page=0&imported=false&search=row) import 后，能看到成功 import 了 RowContainerString，但是缺失了 RowContainerInt。且不知道为什么能在 diff 中看到 local 的 RowContainerInt。
<img width="684" alt="Screen Shot 2022-04-19 at 9 21 19 AM" src="https://user-images.githubusercontent.com/6505755/163901377-333935e1-fdb6-4ecc-a6f4-660bbdda9fda.png">

3. 其他信息：
- order_service pr 过
- restaurantL214 在改只能在我的账号上看到
 

### Expected Behavior

能在 frame 列表中看到 RowContainerInt，且能被作为类型使用

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantL214 

### Framely Link

见上

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/163903496-bd5fd4bf-16a3-449e-b47e-e9917b64d5f5.png)
为啥我能看到。。

**Comment by jfang137** [comment]
local里面的RowContainerString好像就是本地的，跟imported那条id不同

**Comment by yigexu** [comment]
@jfang137 ok，前面没问题了；那我的问题应该是：在 intent FoodOrdering 的 native function createAndInsertOrder 的 return type 中，选择不到 o18811639611 的 imported frame。

[restaurant002/restaurantL214 ](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d0ff5c77cdfc255d0d/intent/61d52d9e31c6ed847d5940f1)
<img width="1786" alt="Screen Shot 2022-04-19 at 9 52 44 AM" src="https://user-images.githubusercontent.com/6505755/163904451-5c2ea5bb-7b01-4ad4-b06e-a5dbfce5bce4.png">

**Comment by yigexu** [comment]
cache 问题，目前无法复现，close。
