### ISSUE TITLE
[Bug]: try-it-now on readonly chatbot doesn't work

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

根据 [[Feature Request]: try-it-now on readonly chatbot](https://github.com/framely/community/issues/210#)，我在Chatbot：[what_to_watch](https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent) （这是Lu的org：[tutorial](https://framely.naturali.io/org/60741b6733676cd2b36dd460/component_agent)里的chatbot，我只有read only的权限）点击 `try-it-now` 应该能直接测试这个chatbot，但目前我点击 `try-it-now` 之后，再点击 `connect` 会报错：` Session Not Found + java.lang.NullPointerException`

![image](https://user-images.githubusercontent.com/95261974/163923746-5d07cf07-bfb5-4f72-a13e-bad03a8ad64b.png)

我尝试了clone该chatbot到我的org，命名为[what_to_watch_copy_0419](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/625e208cd31e3de801ef496e/intent)，然后点击 `try-it-now` 之后，再点击 `connect` ，没有报错，能测试该chatbot

其他测试：
1. @Zeng666666 在她的org下，本地尝试了`commmit - try it now - connect` ,然后没有报错
2. 我尝试了在该org下的另一个chatbot：[testChannel](https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62568337f7970446e380f039/intent)，点击 `try-it-now` 之后，再点击 `connect` ，没有报错

### Expected Behavior

我在Chatbot：[what_to_watch](https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent)中，点击 `try-it-now` 应该能直接测试这个chatbot

我的账号：18810675122

### Framely Link

https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent?page=0&imported=false&search=

**Comment by jfang137** [comment]
4月7日才发布的新feature：language chatbot在merge后,会创建try-it-now实例，之后user branch如果相对于master没有修改，则try-it-now默认与master实例通信。[what_to_watch](https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent)最后merge的时间是4月1号，那时的merge没有创建实例的操作。你再merge一些新的修改试一下 @hisunnymay

**Comment by hisunnymay** [comment]
@jfang137 好的，试了一下，确实有新的merge就可以了
