### ISSUE TITLE
[Bug]: MismatchedInputException

### ISSUE THREAD

**Issue by yigexu** [framely/community#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1507" alt="Screen Shot 2022-04-19 at 4 36 43 PM" src="https://user-images.githubusercontent.com/6505755/163961162-fb63f042-8483-4b6f-bbfd-cc5c8837af93.png">

### Expected Behavior

询问想要什么 What kind of main dish's item do you prefer? 1. noodle 2. rice

### Use Case

/

### Steps To Reproduce

connect，输入 i want to order some food

### Label of org.project

restaurantC214

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/intent

### Additional information

related to the change of #144

**Comment by XiaoboYuan** [comment]
@yigexu 能把我加入到这个org里吗

**Comment by XiaoboYuan** [comment]
@yigexu 
没事了 我在这个org 只是跳转过去只抛错没提示我重新登录

**Comment by XiaoboYuan** [comment]
修复了 包括那个nullpointer的json deserialization的问题  可以试一下 需要commit
我还真不在这个org里 不能commit
@yigexu @xiaoyunwu

**Comment by yigexu** [comment]
@XiaoboYuan
我试一下；
但是我之前把你加进去了，包括 org 和 chatbot
