### ISSUE TITLE
[Feature]: How to deal with builder branch data when permission downgraded 

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 背景
tutorial.what_to_watch 是 public 的，今天（0419） struct 与 lang 都有最新 merge：
- FEI 是 owner；
- xiaoyun 是 guest；

### 问题
用 FEI 的账号看，master 的 Main 的 slot 是 skills：

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/37056884/163975206-8d9ef04f-aa07-479e-91e0-9107d852ba3a.png">

现在用同一个浏览器退出 FEI 的账号、登录 xiaoyun 的账号看，master 的 Main 的 slot 是 skill：

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/37056884/163975482-abd83e28-b9f0-480e-aa80-7d562b98b292.png">

但 xiaoyun 的账号，切换到 struct-agent，master 的 Main 的 slot 是 skills：

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/37056884/163975814-6dc34ed2-8338-4e52-8c9b-fe80604a982d.png">

### Expected Behavior

不同账户看到的 master 应当是一致的

### Use Case

/

### Steps To Reproduce

登录 xiaoyun 账号，看 skill slot：
https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent/5f55a66bb5875cc6c8b5a46e

### Label of org.project

tutorial.what_to_watch

### Framely Link

https://framely.naturali.io/org/60741b6733676cd2b36dd460/agent/62415125b883426466b121b6/intent/5f55a66bb5875cc6c8b5a46e

**Comment by jfang137** [comment]
@Zeng666666

**Comment by Zeng666666** [comment]
https://naturali-io.feishu.cn/docs/doccnF98ks3H971hGLmcKxJoiNe
分析了一下，若 Account 访问 Agent 的权限发生变化，应删除所涉及 agent 的 branch data。
