### ISSUE TITLE
[Bug]: Condition performs wrongly

### ISSUE THREAD

**Issue by yigexu** [framely/community#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

# Overview
1. connect, 输入 i want to order some food, no, no
2. 目前表现：Looks like you didn't choose anything. We will close the ordering process for now.
3. 预期表现：不是这句话，应该会 raise NPE。

# 相关说明
## 设置：
1. response branch
<img width="951" alt="Screen Shot 2022-04-24 at 9 11 44 AM" src="https://user-images.githubusercontent.com/6505755/164951456-6b74af9c-19d3-4f3e-abba-3dea6435119a.png">
2. 第一个 branch 话术
<img width="1317" alt="Screen Shot 2022-04-24 at 9 12 10 AM" src="https://user-images.githubusercontent.com/6505755/164951471-844c73e9-4368-4c20-b2d3-e58ebe4cf602.png">
3. 第二个 branch 话术
<img width="1316" alt="Screen Shot 2022-04-24 at 9 12 19 AM" src="https://user-images.githubusercontent.com/6505755/164951477-36cf5bf4-bf24-4c2b-9068-fc3c9d7f2001.png">

### 解释
1. 考虑到 第一个条件是 true，所以应该永远不会出现第二个 branch 的话术。
2. 第1个 branch 是 true （且预期 NPE）是因为，在上一个版本中只有 第2、3个 branch。然后为了 debug 增加了 condition = true 的branch，并且将它设置为顺序上的第一个 branch。

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/intent/61d52d9e31c6ed847d5940f1?tab=2

**Comment by Zeng666666** [comment]
第一个 branch 没有定义 condition

**Comment by yigexu** [comment]
没有定义 condition 就是 true

**Comment by yigexu** [comment]
我 fix 了一个 bug，所以这里的预期是：不是这句话 (应该不会 raise NPE 了)。

**Comment by Zeng666666** [comment]
不是的，在 response 中不是这样的，response 已经区分了 if else，这是设计时就是这样设计的，因此 response 不能有两个分支是相同 condition 或都没有 condition 的情况，这个需要 builder 自己来保证，目前 platform 没有限制：

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/37056884/164953064-7e9b7866-f516-43f7-8e41-8cf87237e52b.png">

在 issue #233 中也提到过：

<img width="917" alt="image" src="https://user-images.githubusercontent.com/37056884/164953148-629212aa-7062-4811-a1dc-731fe3a44777.png">

**Comment by yigexu** [comment]
这是两个层面的问题。
实现层面，平台没有限制，基于现在的实现就这应该是这种表现。我创建过一个 testbot，同样的设置表现如我所说的预期。所以我猜这里大概率是 condition 的顺序出了问题（和内容无关），且只和这个 bot 相关。

设计层面，我们可以理解为 condition true 没有意义，也可以 argue 它可以存在（正如同编译器会告诉你这样不好但不会要求非要改掉一样），我觉得目前这点不太重要，所以我可以接受最终暴露给 builder 的设计是 condition 没有 true。
我在备注里写了这是一个临时的 debug，如果为了 debug 改设计再改回来太多琐碎的细节了。

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/164953671-1568dfaa-2b89-4e20-80c0-444433fd8419.png)
这是给到compiler的顺序，看上去没啥问题

**Comment by yigexu** [comment]
ok，那先到这里。
