### ISSUE TITLE
[Feature Request]: make database int consistent

### ISSUE THREAD

**Issue by yigexu** [framely/community#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

目前：
1. 在平台上选择 kotlin.int 作为类型，db 会将其默认为 postgres bigint
2. 在平台上开启 storage annotation 的 frame，db 会为其生成一张 table，并为默认增加一列 id，type integer 

问题：
id 是默认主键，builder 有时需要将它暴露给 user （e.g. id 作为订单编号)。
由于 db 对 int 的默认类型不一致，有时时 bigint、有时是 integer，导致 builder 需要额外学习 + 在 SQL 中进行类型转换。

Proposal：
统一 db 对 int 的默认类型，将 #2 中 id 的类型设置为 bigint。

其他：
优先级：P2，不重要不紧急

### Motivation

/

### Describe alternatives you've considered

/

**Comment by hisunnymay** [comment]
@xiaoyunwu @yigexu @Zeng666666 想问一下 我需要在 function implementation 文档里面说明 _“SELECT id 时需要用 `::BIGINT` 转换”_ 吗？还是 我们之后会将 id 的type 改为 `BIGINT`，就不用告知 builder 需要做转换了

目前 builder 不知道 id 对应的 type 是 integer ，如果 _select id_ 但不做转换的话，会报错：
```
ERROR:  structure of query does not match function result type
DETAIL:  Returned type integer does not match expected type bigint in column 1.
CONTEXT:  PL/pgSQL function "_getInfo"(text) line 3 at RETURN QUERY
```

补充：目前 Reservation 的 function 有用到 _select id_

**Comment by hisunnymay** [comment]
@yigexu 我试了一下，我这边可以了，现在生成的 id 是 bigint

![image](https://user-images.githubusercontent.com/95261974/180173888-2c56ca56-af15-4bc2-8bd0-836ade485742.png)

**Comment by xiaoyunwu** [comment]
File an issue to Hui, let's change id the type to BIGINT.
