### ISSUE TITLE
[Bug]: In try it now, when user enters one sentence and hit "enter" for multiple times

### ISSUE THREAD

**Issue by yigexu** [framely/community#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前 try it now 对话过程会比较慢。
有一种情况是：user 输入一句话、键入回车，由于 try it now 需要一段时间反应，这句话会一直停留在输入框中，看起来像是没发出去。这时 user 可能会重复键入回车。
然后会导致 runtime 随机错误。

(视频里面我输入了多次回车，但是看不到)

https://user-images.githubusercontent.com/6505755/165026301-c3253241-bd9e-4f1e-921d-1dfcd6cb4599.mov

### Expected Behavior

对同一条 utterance，不管用户键入多少次 enter，bot 应该稳定地回复一次，内容和用户键入一次 enter 时一样

我不太确定这里具体发生了什么，如果有需要我们可以再讨论一下

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b806ff5c77cdfc256ce4/intent/5f55a66bb5875cc6c8b5a46e

**Comment by jfang137** [comment]
我在前端加了请求过程中重复请求的拦截
