### ISSUE TITLE
[Bug]: Multi-Valued Prompt for "skills" is not displayed on the platform

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前前端的 `Main.skill` 的定义页面没有显示它的 `Multi-Valued Prompt` ，但实际上导出的代码里是有 `Multi-Valued Prompt` ：What else can I do for you。实际测试中，也会输出这句话

1. 前端界面

![image](https://user-images.githubusercontent.com/95261974/165038454-5d9b8961-b956-4613-a59a-7a61aaf4253d.png)

2. 导出代码

![image](https://user-images.githubusercontent.com/95261974/165038641-984a17d8-677e-4bf3-ba6a-c082e8c1d6ef.png)

3. 实际测试

![image](https://user-images.githubusercontent.com/95261974/165038798-5fece61d-efd9-4ac5-b657-7520c478837f.png)

- 补充：
我印象中3月8日左右有看到前端的 `Main.skill` 的定义页面有显示它的 `Multi-Valued Prompt`，但今天yige想改话术的时候发现[DefaultApplication](https://framely.naturali.io/org/600faced6ef4d6d82c040ecd/agent/600fad036ef4d6d82c040ecf/intent)中 `Main.skill` 没有显示它的 `Multi-Valued Prompt` ，其他能输出 `Multi-Valued Prompt` 的bot也都没有显示  `Main.skill` 的 `Multi-Valued Prompt`

### Expected Behavior

如果chatbot能输出`Main.skill` 的 `Multi-Valued Prompt` ，那么前端界面应该能看到它的定义

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6266456a132e5d9cbc15301d/intent?page=0&imported=false&search=

**Comment by hisunnymay** [comment]
@jfang137 上面链接中的Chatbot：[MultichannelApp_copy](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6266456a132e5d9cbc15301d/intent) 的skills有Multi-Valued Prompt了，不过重新创建的Chatbot：[issue_skillsMvPrompt](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/628af10e4c2df962e2c64791/intent) 没有Multi-Valued Prompt
1. Chatbot：[MultichannelApp_copy](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6266456a132e5d9cbc15301d/intent)

![image](https://user-images.githubusercontent.com/95261974/169732590-90b16559-327b-4897-b24b-6a0bb74cf3d3.png)

2. Chatbot：[issue_skillsMvPrompt](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/628af10e4c2df962e2c64791/intent)

![image](https://user-images.githubusercontent.com/95261974/169732315-b69c3725-f870-46a3-84a8-6a2baf8d87bb.png)

**Comment by jfang137** [comment]
是template的数据比较旧，存在问句却没有开启mv prompt模块。 刚加了限制，没有开启mv prompt的话，问句不会传给compiler,稍候试一下

**Comment by hisunnymay** [comment]
Checked, 目前的表现是：如果没有开启mv prompt，对于Multi-valued slot的第二次询问会输出空语句

![image](https://user-images.githubusercontent.com/95261974/169749985-affbfedb-c3de-4388-b729-51a309540d54.png)
