### ISSUE TITLE
[Bug]: Conversation history is shown in two chatbots

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 在chatbot：[hoursApp_0424](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6264c139cc1fede3bc4cff38/intent)中的对话结果会显示到Chatbot：[t_DUDate](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/626630bc132e5d9cbc14cec0/intent)中

![image](https://user-images.githubusercontent.com/95261974/165047966-32f5332d-9551-4818-b7b7-663e0e11e92f.png)

2. 在Chatbot：[t_DUDate](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/626630bc132e5d9cbc14cec0/intent)中的对话结果会显示到Chatbot：[hoursApp_0424](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6264c139cc1fede3bc4cff38/intent)中

![image](https://user-images.githubusercontent.com/95261974/165048078-6a2c5755-f378-410e-b3eb-335d22599ec3.png)

背景：

下午测试的时候，出现了这样的现象：在[hoursApp_0424](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62651616132e5d9cbc1315a1/intent)中测试，先测试了一个intent：HoursWeek，能work，然后将改会话保存在了`Test Case` 中。之后再测试，出现了下面的对话：
> U：周一营业吗
> B：不好意思，我好像没能理解
> U：你好
> B：不好意思，我好像没能理解

后来将添加的 `Test Case` merge到master之后（中间还有创建别的chatbot并测试的操作，不知道会不会有影响），再测试，Bot才能听懂。由于没有对改Bot进行任何关于对话交互对改动，所以感觉像是：用了别的chatbot的定义的内容。
尝试复现当时的现象，但无法复现，在尝试复现的过程中出现了本issue描述的问题。

### Expected Behavior

在一个chatbot中测试的对话内容不会在别的chatbot中显示。

### Steps To Reproduce

1. 分别Commit两个Chatbot：A和Chatbot：B
2. 在Chatbot：A中点击 `Try it now` ，发送消息
3. 刷新Chatbot：B的页面，再点击 `Try it now` ，就能看到Chatbot：A中的刚才的对话内容

### Framely Link

https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/62665ea3132e5d9cbc156aec/intent?page=0&imported=false&search=

**Comment by hisunnymay** [comment]
之前 @yigexu 有发过类似的issue：[[Bug]: sometimes, it need to compile twice](https://github.com/framely/community/issues/132#)

**Comment by jfang137** [comment]
@hisunnymay  你是同时开启了两个页面是吗？

**Comment by hisunnymay** [comment]
@jfang137 是的

**Comment by jfang137** [comment]
@xiaoyunwu @XiaoboYuan 现在try-it-now传的session是user id.就出现了这同一个user同时测试两个bot时session混乱的问题，这里我能不能把session id改成传user id + agent id?

**Comment by hisunnymay** [comment]
Checked, fixed.

**Comment by xiaoyunwu** [comment]
for sure.
