### ISSUE TITLE
[Bug]: Unable to remove component in provider

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在Provider：[reservationProvider_0425](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/626670b3132e5d9cbc15b3d2/service_schema)中尝试删除Component：[reservation_2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622eae8e5dc1a2ba24cf315c/service_schema)，报错：

> skill [MakeReservation] - response [else_branch] references this object skill [MakeReservation] - response [621486ff33a75aab15928220_1646192052303] references this object

![image](https://user-images.githubusercontent.com/95261974/165199762-8951f26a-ba5c-43c6-bf45-743203875661.png)

### Expected Behavior

在Provider的页面中没有显示 `Intents`，builder不知道Provider中存在 `Intent.skill` 。因此当builder尝试在provider中删除component的时候，报错提示说 “`Intent.skill` 中有用到这个component，所以不能删除” ，感觉有点不太合理。

如果builder没有在  `Service` , `Frames` , ` Entity` 中用到这个component，是不是应该允许builder删除这个component？

### Use Case

Builder想要更新component，但是为了能保留原来的版本，所以选择了clone该component和与之对应的provider，然后需要更换provider中的component为新的component

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/626670b3132e5d9cbc15b3d2/library

**Comment by hisunnymay** [comment]
@Zeng666666 发现clone的provider和原来的provider用的是同一个id，可能和这个原因有关系？

![origin_img_v2_5ce43e83-9799-4ba8-bd37-da77ccb235eg](https://user-images.githubusercontent.com/95261974/165205349-ad4c1cc3-f165-4086-93cd-5886aa031e9d.jpg)

**Comment by jfang137** [comment]
是的,这种操作产生的问题目前没办法解决，clone的agent是通过id来维持agent 内部的引用依赖关系的，没法生成一套新的id

**Comment by Zeng666666** [comment]
如果把 agent_id 也作为其中一部分，似乎可以区分，那这样会有什么影响吗？

**Comment by xiaoyunwu** [comment]
clone should cut the connection, so there is no reason to have same id any more.

**Comment by jfang137** [comment]
从我们当前的实现暂时问题。  agent A中，对象b与c与以及其他对象的依赖和引用关系靠id_b与id_c记录，如果要到 cloned agent A'中， b' 与 c'等对象保持同样的引用依赖关系，他们不会生成id_b'与id_c'，而是仍然为id_b,id_c。  这种对id的引用存在于继承/function/slot/expression等等。生成新的id将使引用方失效。

**Comment by hisunnymay** [comment]
@jfang137 哈喽，这个issue 现在有什么好的解决方案吗？因为我需要 clone yige 的 component 和 provider，所以又遇到这个问题了

**Comment by jfang137** [comment]
没有，基于当前的实现的架构确实很难有什么办法

**Comment by jfang137** [comment]
@hisunnymay @Zeng666666 如果clone agent替换新id的重构没bug的话，这个issue应该也解决了

**Comment by hisunnymay** [comment]
@jfang137 试了一下，现在删除 [orderProvider_copy](https://build.framely.ai/org/615fa4282cc41400665536e3/agent/62fde4891470af39572048a5/service_schema) 中原来 import 的 component：order 会有提示："skill [FoodOrdering2]...."，然后删除之后想在 service 中 implement clone 的 component：[order_copy](https://build.framely.ai/org/615fa4282cc41400665536e3/agent/62fde46e1470af3957203ea2/service_schema) 会报错：“Info has been deleted”

1. remove component：order，提示："skill [FoodOrdering2]...."

![image](https://user-images.githubusercontent.com/95261974/185348799-5ad95e54-6200-4b07-93f8-7a5e8989fb55.png)

2. 切换到 service，报错：“Info has been deleted”

![image](https://user-images.githubusercontent.com/95261974/185350040-2e11b304-a0f1-4f13-b9db-6ee915e0eca5.png)

**Comment by hisunnymay** [comment]
⬆️ 这个问题，需要先把 service 中 implement 的 旧的 frame(即 component service) 删除掉，不然即使 import 了新的 component，在 service 中也不能 implement component 对应的 service

因为这个属于 builder 的不安全操作，所以需要 builder 自己负责，平台仅做提示

> From @Zeng666666 :
这里应该加一些提示语句：比如这个操作有可能会破坏 provider 的完整性，使其无法工作，请确认你是否 remove 且自行承担后果。据不完全排查，有如下引用：
