### ISSUE TITLE
[Bug]: Imported Items which are language independent are editable in Lang

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前，在被导入的component的语言分支(lang agent)中,和语言无关部分目前是可以编辑的。

1. 比如：在**imported** intent中，confirmation - contidition在EN下是可以编辑的

![image](https://user-images.githubusercontent.com/95261974/165889856-1c624933-be08-452a-8346-6d8364f0c38d.png)
 
2. 但是在**local** intent中，confirmation - contidition在EN下是不可以编辑的

![image](https://user-images.githubusercontent.com/95261974/165889944-38cec504-04f4-475e-9095-bdedae74f734.png)

### Expected Behavior

在被导入的component的语言分支中,和语言无关部分应该是不可以编辑的。

**Comment by jfang137** [comment]
旧数据有问题，按重构后的流程导入或更新lib以后数据被修复了

**Comment by hisunnymay** [comment]
Checked, it's fixed.
