### ISSUE TITLE
[Bug]: Failed to delete Chatbots

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

尝试删除Org：[o18810675122](https://framely.naturali.io/org/615fa4282cc41400665536e3/component_agent) 中的Component：[reservation](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6214832d33a75aab159263e5/service_schema) 和 [hours_service](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/61c95b76043349f7ae0d2a18/service_schema)，但是删不掉

1. 点击删除时候的界面

![image](https://user-images.githubusercontent.com/95261974/167246758-b037dbec-58bd-48f8-9253-26cbb63b6b8c.png)

2. 当#1界面无变化时，刷新页面重新点击删除，大约过30s之后会显示下图提示

![image](https://user-images.githubusercontent.com/95261974/167246822-35f2e439-e383-4203-b557-1d7fa09db3f6.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6214832d33a75aab159263e5/setting

**Comment by jfang137** [comment]
似乎是某些错误数据导致的操作超时，我延长了超时时间，agent被删除了，但是没找到数据的异常原因。后面有类似的问题我们再追踪吧

**Comment by hisunnymay** [comment]
试了一下，之前不能删除的一些chatbot现在可以删除了。
