### ISSUE TITLE
[Bug]: Flashing editbox when using structure after connect

### ISSUE THREAD

**Issue by yigexu** [framely/community#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/6505755/167536991-9456f385-a560-4d1e-924a-835bdd3e93ec.mov

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

should be irrelevant

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6278adb26a4467792de7fb00/intent?page=0&imported=false&search=

**Comment by jfang137** [comment]
我这里没有复现，尝试把drawer组件的scrollbar隐藏了，可以试试看还会不会复现

**Comment by yigexu** [comment]
@jfang137 这个我目前还是会有，但是昨天在家是 ok 的。可能需要你用我的环境看一下了
