### ISSUE TITLE
[Feature Request]: 为 chatbot 添加 TimeZone

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

PRD: https://naturali-io.feishu.cn/docs/doccnJPYkM8CmUFHned3oB0gs5m

### Motivation

对于 Global Business，会有 TimeZone 的概念，会出现 end-user 与 service 所在时区不同、显示时间不同的情况

Analysis & Use case & Proposal: https://naturali-io.feishu.cn/docs/doccnXVHPkyijzBeDAlnggDrRzc

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
@jfang137 how is the passed to code gen?

**Comment by jfang137** [comment]
@xiaoyunwu 
![image](https://user-images.githubusercontent.com/16040960/161881400-1a75efdc-28a6-46e8-b0ed-b486a80ebe25.png)
agent上有timezone字段

**Comment by xiaoyunwu** [comment]
@XiaoboYuan did u process this in code gen yet ?

**Comment by xiaoyunwu** [comment]
@XiaoboYuan what about the code gen, did you generate this
