### ISSUE TITLE
[Bug]: Boolean gate language part should be editable under lang

### ISSUE THREAD

**Issue by yigexu** [framely/community#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="2548" alt="Screen Shot 2022-05-10 at 3 12 31 PM" src="https://user-images.githubusercontent.com/6505755/167570510-42ac2267-99ee-4b26-9306-ff6116e1e144.png">

如图，这三个文本框都是用来填语言的，需要能在 lang 下面编辑。

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

should be irrelevant

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/627a07b1b1e9463c25083125/intent/627a07b6b1e9463c25083127/slot/627a0da4b1e9463c25083136

**Comment by yigexu** [comment]
@jfang137 方便的话，能先把这个改一下吗？

**Comment by jfang137** [comment]
好的

**Comment by jfang137** [comment]
改过了，试一下 @yigexu

**Comment by yigexu** [comment]
可以了，多谢
