### ISSUE TITLE
[Improvement] Show/Print FrameEvent in try-it-now conversation history

### ISSUE THREAD

**Issue by yigexu** [framely/community#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="458" alt="Screen Shot 2022-05-10 at 5 02 05 PM" src="https://user-images.githubusercontent.com/6505755/167591807-f0744c17-c965-4ef1-85a9-4ca71503d245.png">

目前通过 structure 的 FrameEvent 向 try it now 输入，会默认不将其显示在对话历史中。
我希望显示出来，原因是：
- try it now 本来就是 builder 用来测试 bot 的，既然他们输入了 FrameEvent，那么 FrameEvent 对他们来说就有意义 （可以接受的）。
- 如果不显示 FrameEvent 的话，对话是不全的。直观上，好像 bot 自己连着说了两个 turn；使用上，无论是 builder 和其 team member 交流，还是隔一段时间看 saved testcase，都会无法理解。

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant

**Comment by yigexu** [comment]
Note: structure 包括 connect 之前、之后。

**Comment by yigexu** [comment]
@jfang137 这个好改吗？
我这两天和晓波对 SlotUpdateV1，（由于 DU 有问题，都需要先用 FrameEvent 作为输入），看不到 FrameEvent 描述起来非常复杂...

**Comment by jfang137** [comment]
之前没支持展示，我先看下

**Comment by yigexu** [comment]
好；
还有一件事是，我之间通过 query 直接输入 FrameEvent 展示出来过，我发现 FrameEvent 很长的时候展示不会自动转到下一行，如果可以你也一起看一下

**Comment by jfang137** [comment]
好的

**Comment by yigexu** [comment]
可以了，谢谢
