### ISSUE TITLE
[Bug]: automatic return in native function?

### ISSUE THREAD

**Issue by yigexu** [framely/community#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 问题描述

Native function

1. 
```
return listOf(City("beijing"),City("shenzhen"),City("shanghai"),City("chengdu"))
```
2. 
```
return listOf(City("beijing"),City("shenzhen"),City("shanghai"),City("chengdu"),
City("london"),City("edinburgh"),City("bristol"),City("nottingham"))
```
3. 
```
return listOf(City("beijing"),City("shenzhen"),City("shanghai"),City("chengdu"),City("london"),City("edinburgh"),City("bristol"),City("nottingham"))
```

### 表现
1、2 可以 compile，3 不可以 compile；预期是应该都可以 compile
3 的具体报错：
```
source_code/playground_testSlotUpdate/playground_testSlotUpdate.kt:514:5: error: this function must return a value of type List<City>
    return
    ^
```

### 问题
从这个表现看，应该是从 function 定义 到 runtime 使用的过程中有不正确的换行。

### 其他
现在函数的是 3，如果需要可以修改 [getter](https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/627b5f12b0abf826f66db49c/intent/6278ae586a4467792de7fb1b) 
<img width="1441" alt="Screen Shot 2022-05-11 at 2 56 32 PM" src="https://user-images.githubusercontent.com/6505755/167787871-bdbee8b2-c126-4771-aafa-24f2e9bc26d3.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

playground /testSlotUpdate_copy

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/627b5f12b0abf826f66db49c/intent/6278ae586a4467792de7fb1b

**Comment by XiaoboYuan** [comment]
fixed
