### ISSUE TITLE
VC: state update and annotation V2

### ISSUE THREAD

**Issue by yigexu** [framely/community#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

/

### Motivation

# 问题定义
业务定义一组条件，framely 根据查询满足限制的结果。如果结果的 result list size (从非 0 减少) 为 0，则 user has to be asked to do something，否则业务没办法继续。

# Typical case
- C1 输入手机号 / 1301301301 / 输入验证码 / 123456 / 验证码验证失败，请重新输入手机号
- C2 你想要什么日期？/ 周五 / 什么时间 / 11点 / 什么桌位大小 / 大桌 / 大桌没了， (* 业务认为桌位为硬性需求，用户无法 adapt，所以重头问日期；这个 case 可以拓展成，业务希望先问时间，目前不考虑)
- C3 你想要什么日期？/ 周五 / 什么时间 / 11点 / 什么桌位大小 / 大桌 / 大桌没了，重新选一个桌位大小
- C4 你想订什么日期 / 周五 / 什么时间 / 11点 / 什么桌位大小 / 大桌 / 确定吗 / 我想改成13点 / 周五13点大桌没了，重新选一个时间 (用户改主意了)

# Solution candidates
## 方案一：VC + 策略
platform 在 VC annotation add function 时增加选择策略的 control
- Clear all：VC fail 后，清理 function 涉及到的全部 slot，从未被填槽的第一个 slot 开始询问；对应 #C1, #C2 
- Clear one: VC fail 后，清理导致 fail 发生的 slot (也就是最后一次填槽的槽位，它导致 result list size 从非 0 变为 0)；对应 #C3, #C4

### 细节一
如果多个 VC function 同时 fail，应该如何表现：
以前写过场景分析 [[discussion] 多个VC表现的顺序](https://naturali-io.feishu.cn/docs/doccntDheAy1A86KnRRaZg50Pwd) 
1. 按照 platform VC function 声明的顺序 (显式)
2. 从 VC function 中分析 slot order (基于部分逻辑分析的隐式)
  - 只有策略1：选择有着最靠前 slot 的 那个 VC function ```重头问越早开始越好```
  - 只有策略2：随意 ```清理1个 slot 在对话逻辑上无差，prompt 本质是 inform 不满足选择不满足业务需求和 VC 导致的状态变化，信息量应该没有区别```
  - 同时存在策略1 & 2：优先策略2 ```如果策略2需要清理的 slot 属于策略1需要清理的 slot combination，那么后者就是强条件，应该放在后面；具体考虑 #C1，其实应该先怀疑验证码输入错误，再怀疑手机号输入错误```
3. 从 VC function 中分析 slot，并根据 slot 数量决定 (proposed in # 27)

Note：全部执行在对话逻辑上行不通，VC prompts 会一口气全部被说出来。
我感觉 <2> 可能比较好一些，<1> 涉及到对对话顺序的把控，<3> 没完全利用上策略所 embed 的信息

## 方案二：VC + action
platform 为 VC annotation add function 时增加 action sequence，当 VC fail 后，执行 action sequence 而非采用原来 VC 的默认策略。(conditional action is not required but nice to have, since 这个方案定义在 VC annotation entry 上)
component action 包括：
- slot level (ClearSlot, FillSlot)
- reply；

不包括：
- intent level (intent start、intent end)

### 细节一
如何在 platform 上 slot level action reference 到导致 VC 失败的那个 slot：
1. 为 Clear Slot 和 Fill Slot 内部增加 dynamic 和 static 的单选
2. 为 Clear Slot 和 Fill Slot 的下拉菜单中增加 this/self 的选项

其中，dynamic 或 this/self 代表导致 VC 失败的那个 slot。
Note：当 dynamic 计算的 slot 和预先定义的 static slot 相同时，按顺序执行即可。e.g. ClearSlot(this) 和 ClearSlot(A) turns out to be ClearSlot(A) 和 ClearSlot(A))

### 细节二
runtime 在每个 VC function 中 action sequence 被执行完后，和 refocus 的关系
1. 不refocus
2. refocus slot order 最靠前的那个 slot
3. 让 builder 去选

仅考虑现在的 case，我觉得可以先选 <2>

### 细节三
如果多个 VC function 同时 fail，应该如何表现：
1. execute the one that has the minimal slot order
2. execute the one that has the least/most change in action definition. 
3. execute the one that has the least/most number of slots in corresponding check function

(2,3 proposed in # 27)
action level 没办法推测 builder 的策略，但我认为2/3都应该选 least/弱条件的情况。

## 方案三：VC + SU (state update) 
platform 为 state update (SU) 增加 ValueCheckFail state、conditional actions。
target slot + ValueCheckFail + conditional actions 选择的 function 共同决定对哪个 VC function customize。
当 VC function 被 customize 后，认为 VC annotation 只用于定义哪些 function 会被执行，而不再定义 function 被如何执行、VC fail会做什么 (包括prompt)。

### 细节一
需求要求 VC 完成一定要有 refocus 的能力。让 SU refocus 的方向大致有：
1. expose refocus
2. SU annotation-level default strategy，包括：每次 clear/fill 后 refocus、一组 action sequence 完成后 refocus 等
3. SU 局部 default strategy：为 state 为 ValueCheckFail 的 action sequence，在action sequence 结束后，做一次 refocus

### 细节二
**这个方案无论对 builder 还是对 runtime 都很别扭，因为 VC annotation 是 slot combination 构成的 function view，SU 是以 target slot 为轴心、function 为延展的 slot view。目前很难设计成 closure 的方案，会存在大量 undefined 行为。**

假设 VC annotation 定义function f(B, C), f(B), f(A)

builder 在 target slot B 的 conditional action 中选择 condition = f(B, C)，且没有在 target slot C 的 conditional action 中选择 condition = f(B, C)，这时：
1. 认为 customize level 是 slot，因此如果是 B 导致的 VC fail，就采用 SU custom 的策略；如果是 C 导致的 VC fail，仍旧执行 VC annotation 默认策略
2. 认为 customize level 是 function，因此当作 C 和这个 VC 没有关系

从 platform 设计上，应该选择<1>，因为 SU 是 slot-level。
<br/>
builder 在 target slot B 的 conditional action 中选择 condition =  f(D)，这时：
1. 没有特殊处理，按照 SU 的规则来
2. 前端限制，不允许看到/选到，因为原来 VC 是不支持这种情况的

可以将 VC 能力扩充成 <1>
<br/>
builder 在 target slot B 的 conditional action 中根本没有选择 condition，这时：
1. customize 和 target slot B 相关的 VC function，需要 runtime 分析支持
2. customize 所有 VC function
3. 不 customize VC function

### 细节三
如果多个 VC function 同时 fail，应该如何表现：
转换成 function view，同方案二

### 细节四
target slot 选择 frame slot 后，可以
1. 考虑对应未来的aggregation mode，现在行为 undefined
2. 把 frame 作为选择 frame 下所有 slot 的shortcut

### Describe alternatives you've considered

/

### Additional context

Relate discussion:
#31 
#27 comment

**Comment by Zeng666666** [comment]
### 写在前面

1. Platform 不应左右业务逻辑。

2. C1 在这里不成立，因为有手机号才可能会有验证码。


### 业务场景

1. 看电影，唯一决定一张电影票的因素：时间、影院、片名、座位号（几厅几号）；

2. 看演出：城市、艺人、场馆、日期、价位；

3. 订座：日期、时段、余位数量；


### 一些顾虑

value check 的默认表现，是我们预期 end-user 有意愿去完成一件事情，比如买电影票、买演唱会门票、订位。因此，当 value check  fail 时，不满足他的意愿，他会主动表达，即我们会通过 update 机制来帮助 end-user。

platform 不应该左右业务逻辑，因为 platform 不知道对于 builder 和 end-user 什么是重要的。比如：

- 订位场景：
  - 对于上班族来说，他就只能选择下班以后的时间比如 19:00，至于周一他可能没有偏好；
  - 对于企业来说，团队聚餐通常在中午或傍晚，日期也基本是固定的，这家不行就订另外一家；
  - 对于约会而言，各种纪念日都是固定的，日期基本是不变的，变的是时间。

- 买票场景：
  - 粉丝，选择固定的艺人，其他条件怎么变都行；
  - 普通观众，
    - 如果约会，则更看重时间；
    - 如果旅游，则看重地点和时间；
    - 其他情况，不同的目的，有不同的抉择。

因此，无论 end-user 面对什么，只要他有诉求，他都会主动去改。而这个主动，应该掌握在 end-user 手中。就像我们在 GUI 做筛选，未找到结果时，是不会自动清空所有条件，而是我们手动去改变我们想改的条件。比如，当我们在大众点评、猫眼筛选条件时，没有结果就自动清空筛选，那体验就比较不好了。

如果让 builder 仔细定义怎么 clear slot，似乎是想要求 builder 遍历每一种 condition，否则当 vc fail 时，表现可能永远一样，那么 end-user 会进入无法理解的循环中。对于 end-user，好的体验肯定是：知道此刻处于什么状态、遇到什么问题、应该做什么。

记得之前有提及过 no value 的需求，不知是不是在这类场景下帮助 end-user 到达他想去的方向？
