### ISSUE TITLE
[Bug]: Provider Type 应该有 Webhook/Restful 选项

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PRD：https://naturali-io.feishu.cn/docs/doccnEbTD4Zrj6SEnZe0UclogQo

虽然 PM 目前主要在使用 Postgres，且 Postgres 为默认选项，但 Webhook 平台没有移除，应当还是可以被选择的。
且可以根据 provide type 的不同，展示与之相对应的配置页面。

![image](https://user-images.githubusercontent.com/37056884/156150267-abe30386-36eb-4ac5-8218-5ddf563aebdd.png)

### Expected Behavior

Provider Type 如果选择了 Webhook 选项，agent 中应展示与之相对应的配置页面，比如：

- Function

![origin_img_v2_b994f883-0d9f-4082-b20a-cc857f390b9g](https://user-images.githubusercontent.com/37056884/156150503-36a70128-12f2-488d-b5ac-a96770b3d2dc.png)

- Config

![origin_img_v2_5faea1ad-ad24-42e2-a104-cce5625e99cg](https://user-images.githubusercontent.com/37056884/156150420-0a386c5f-a228-4fd5-8a9f-07ce87a1f0ca.png)

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

**Comment by jfang137** [comment]
deploy mode那里选择private才会有restful provider type选项, framely部署的provider目前只有postgres

**Comment by xiaoyunwu** [comment]
restful should be enabled for framely deploy as well, since it is just
forward the call to existing service, we do not have to much here. @Yi Fang
***@***.***>

**Comment by Zeng666666** [comment]
@xiaoyunwu 想起来了，我们是有这个限制，提 issue 的时候忘记了。
那现在 Framely-host 时，也可以选择 restful 吗？

**Comment by jfang137** [comment]
好的，我把选项放出来

**Comment by Zeng666666** [comment]
done
