### ISSUE TITLE
[Bug]: imported frame and entity cannot be selected as frame slot type, if not refresh from org list

### ISSUE THREAD

**Issue by yigexu** [framely/community#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- 创建一个新的 provider，import library restaurantL516
- 创建 frame [CategoryCategory](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6281e0d9421785aec8b19774/frame/6281e16a421785aec8b1a0c5),想为其增加 frame slot，type imported entity DishCategory
- 目前 frame 和 entity 都选择不到 imported 的内容。（截图用的是 frame，因为可以选择到 system.java 和 kotlin 下面的 entity，所以 entity 有很多选项，不方便展示。）
- 刷新页面还是如截图；切换到 org 页面再进去就可以。

<img width="1440" alt="Screen Shot 2022-05-16 at 1 32 01 PM" src="https://user-images.githubusercontent.com/6505755/168525796-56bbf679-5f3a-4e08-b788-e10b5d985da7.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantP516 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6281e0d9421785aec8b19774/frame/6281e16a421785aec8b1a0c5

**Comment by jfang137** [comment]
import好像是发生在另一个网页的，host agent的所在的网页无法感知到缓存需要更新

**Comment by yigexu** [comment]
@jfang137 这个我还是不行
