### ISSUE TITLE
[Bug]: io.framely.core is not sync to chatbot

### ISSUE THREAD

**Issue by yigexu** [framely/community#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 在[我的chatbot 的 io.framely.core.ValueClarification 的 target](https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6278adb26a4467792de7fb00/frame/60ed22bbe80bdfd60aaa6b63/slot/60ed23d2e80bdfd60aaa6b72) (Note ${targetSlotAlias()} 后面没有空格)
<img width="1428" alt="Screen Shot 2022-05-16 at 4 59 41 PM" src="https://user-images.githubusercontent.com/6505755/168557350-01d815f2-14c3-4d72-9978-b6c06020f92e.png">

2. 在[io.framely.core 的 ValueClarification 的 target](https://framely.naturali.io/org/5fa0e7dcf549c817cf952edd/agent/5fa2608c22714e8c5b7b9e22/frame/60ed22bbe80bdfd60aaa6b63/slot/60ed23d2e80bdfd60aaa6b72) (Note ${targetSlotAlias()} 后面有空格)
<img width="1434" alt="Screen Shot 2022-05-16 at 5 00 05 PM" src="https://user-images.githubusercontent.com/6505755/168558169-17529492-a51f-48c9-bb19-3bbf9bc171a7.png">

预期是应该有空格。

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

playground /testSlotUpdate 

### Framely Link

见上面的链接

**Comment by Zeng666666** [comment]
在 struct-agent 上 update 一下 library，commit 传播到 lang 就一样了

**Comment by yigexu** [comment]
我昨天应该是更过了，但是不知道为什么不行，今天早上打开可以了。

**Comment by jfang137** [comment]
昨天下午修了先发布了一下，代码刚刚merge
