### ISSUE TITLE
[Bug]: testcase lastest test time

### ISSUE THREAD

**Issue by yigexu** [framely/community#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1404" alt="Screen Shot 2022-05-16 at 5 34 25 PM" src="https://user-images.githubusercontent.com/6505755/168563694-4ad9c10b-d4ce-4c1c-949e-d5fa6ba7eb44.png">

### Expected Behavior

应该是最近一次测试的时间

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6278adb26a4467792de7fb00/test_case

### Test Case

/

**Comment by jfang137** [comment]
<img width="829" alt="image" src="https://user-images.githubusercontent.com/16040960/168567728-4687a24c-9f2a-4d02-917f-c53b13d509f9.png">
没有复现啊，浏览器问题？

**Comment by yigexu** [comment]
昨天在家用的 safari，感觉好几个地方都有问题。我用公司的电脑 safari 也还是不行
