### ISSUE TITLE
[Feature Request]: Integration 应在 struct level 操作

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## 优化方向

Integrations：service provider、channels、support 应为 structure 内容，因此：
1. 支持 support 在 struct-agent 定义；（Chatwoot 相关，关联 #11 ）
2. 移除 lang-agent 中的 Integrations 页面。

## 页面优化

1. support 在 struct-agent 定义；

2. 通过下拉菜单进行选择，目前一个 chatbot 只能选择一个 support（下拉菜单可以把不需要的备选项隐藏起来）
   - 添加后，点击该条目，弹出配置弹窗；

![image](https://user-images.githubusercontent.com/37056884/156165249-9cb0316b-f42f-4eb1-8b37-32b837cea1b4.png)

或样式如下：

![image](https://user-images.githubusercontent.com/37056884/156168352-a4c48454-cfa3-4301-a7b5-4ae193866ce4.png)

3. 移除 lang-agent 中的 Integrations 页面：

![image](https://user-images.githubusercontent.com/37056884/156166936-8e15968f-2f64-4894-8cbe-352cf5e7288a.png)

### Motivation

关于 chatwoot 相关，可见 #11 

### Describe alternatives you've considered

目前 Lark 是可以用的，还是应该 remove 的？

**Comment by xiaoyunwu** [comment]
This should only change the platform behavior, the way we pass the
information to codegen should stay the same.

**Comment by Zeng666666** [comment]
一些补充：

1. 移除 lang-agent 中 settings Integrations Tab：

![image](https://user-images.githubusercontent.com/37056884/156754304-7d67bf6d-2cf6-460c-b527-5b6ecd6e5c42.png)

2. 模块间的间距，预期是一致的：

![image](https://user-images.githubusercontent.com/37056884/156754514-20014ec3-822e-48e1-bb51-017b595afc89.png)

- 可参考 Schema Tab：

![image](https://user-images.githubusercontent.com/37056884/156754740-4fa15715-2889-40b8-9520-b850c8459c9b.png)
