### ISSUE TITLE
[Bug]: Value Check doesn't work when slot is multi-valued

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

对于sv slot，value check能work，但是对于mv slot，value check不能正常输出value check prompt

1. sv slot 能输出value check prompt

![image](https://user-images.githubusercontent.com/95261974/169789781-8aa80ffc-e0a3-43da-86a4-a8d79eb0e11e.png)

2. mv slot 不能输出value check prompt

![image](https://user-images.githubusercontent.com/95261974/169789312-c0c9bf3d-3a92-4dc0-a682-8d82b630d70e.png)

### Expected Behavior

对于mv slot，value check能正常输出value check prompt

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/628b46e662bd75402fdc4c2d/test_case

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
Checked, it's fixed.
