### ISSUE TITLE
[Feature Request]: in the channel configuration, append /lang to the channel url we serve. 

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

since we move to different default lang for channel, let make it explicit by append lang to end of channel url. 

### Motivation

We need this information. otherwise, we have get it in a strange way. 

### Describe alternatives you've considered

We are try to get this information from agent, but it need to load agent twice, not efficient.

**Comment by hisunnymay** [comment]
@jfang137 我们能在微信公众号的Callback URL末尾加上default language的信息吗？

e.g. https://api-vs.naturali.io/org/o18810675122/bot/channelDefaultLang_0513/c/wechatpa/v1/channelDefaultLang_0513/en

![image](https://user-images.githubusercontent.com/95261974/170156516-6bcdbdf2-ea41-4122-8044-e1b929a8f28c.png)

**Comment by jfang137** [comment]
@hisunnymay 是所有channel type还是仅仅微信公众号?

**Comment by hisunnymay** [comment]
@jfang137 可以先加微信公众号的，因为目前是在测试微信公众号。不过我看xiaoyun把其他channel的url也改了，以后应该也要改其他channel的
