### ISSUE TITLE
Entailment expression

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Introduce an entailment expression for intent. These expression will be used the same as regular intent expression for DU, but training will use them differently for maximal reuse across different builders. 
The encoding of this will be the same as the regular expression for frame, except that the label should be assgined with a value of "entailment". 

### Motivation

There are two different ways that user might inform us that they want to order some food:
1. I like to order some food. 
2. I am hungry
While these two sentences might mean the same thing under certain use case (restaurant chatbot), they do not always equals (for home speaker, this might result in food cooking).

### Describe alternatives you've considered

n/a

**Comment by Zeng666666** [comment]
![image](https://user-images.githubusercontent.com/37056884/155325740-6c3298bb-e578-417a-af0a-805c24404642.png)
\n

platform is ready
