### ISSUE TITLE
[Bug]: DU should not be case sensitive (Originally: connect error)

### ISSUE THREAD

**Issue by yigexu** [framely/community#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1206" alt="Screen Shot 2022-03-02 at 10 55 53 AM" src="https://user-images.githubusercontent.com/6505755/156286193-7423899e-48bc-44fe-a94d-3cf2108d4bae.png">

### Expected Behavior

DU听懂
我记得intent clarification 并没有好，apart from that，我不能理解为什么需要澄清

### Use Case

/

### Steps To Reproduce

I want to order some food
![Screen Shot 2022-03-02 at 10 54 20 AM](https://user-images.githubusercontent.com/6505755/156286043-c94defeb-7b88-4aa1-ae4e-7d082d4d6599.png)

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/intent/61d52d9e31c6ed847d5940f1?tab=4

**Comment by yigexu** [comment]
<img width="587" alt="Screen Shot 2022-03-02 at 3 28 40 PM" src="https://user-images.githubusercontent.com/6505755/156314887-f63424ea-4656-47f4-b526-57eadec15c90.png">
我手动更新成最新版本了

**Comment by yigexu** [comment]
@xiaoyunwu 今天大小写问题 "I/i want to order some food" 的 issue 是这个。好了在这里 comment 就行

**Comment by xiaoyunwu** [comment]
this should be fixed.
