### ISSUE TITLE
[Feature Request]: Change Function to Conditions in Value Check

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

将Value Check中的 `Function` 改为 `Conditions`, 对应的提示文本改为 Enter code expression

1. 期望的界面
![uE3geCU36D](https://user-images.githubusercontent.com/95261974/170913585-d04211fa-0937-444f-a80e-791a45dd731d.png)

2. 目前的界面
![image](https://user-images.githubusercontent.com/95261974/170915382-fb9c1891-51ed-46d3-ac9b-f7d22d11a9fc.png)

### Motivation

之前vc设计的出发点是function failed，（即 function返回值为false），但我实际使用的场景不只是“function failed”，还会有条件判断（即condition）。所以如果我们介绍vc的时候用“condition作为判断条件”，和“用function返回false作为判断条件”相比，前者的自由度更高，因为前者意味着builder不只能填入function，还能填写表达式。而且也便于向builder解释vc的用法：当condition为false时，会触发vc输出prompt（类似于confirmation的condition为true时，触发输出它的prompt）

### Describe alternatives you've considered

/

### Additional context

/

**Comment by xiaoyunwu** [comment]
@Yi Fang ***@***.***> please.

**Comment by hisunnymay** [comment]
Checked.
