### ISSUE TITLE
[Bug]: Body of native function disapears after clicking save

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

填写完native function点击 `Save` 后，再重新点击进入native function，之前body中定义的内容被清空了，但是点击commit后，native function的body如果定义有问题，还是会报错

### Expected Behavior

填写完native function点击 `Save` 后，再重新点击进入native function，之前body中定义的内容应该还在

### Steps To Reproduce

1. 填写native function，然后点击 `Save`
![image](https://user-images.githubusercontent.com/95261974/170923310-6765122c-9d36-4f22-8024-5f510e5c1b90.png)

2. 提示保存成功，再点击进入native function，body为空
![image](https://user-images.githubusercontent.com/95261974/170923467-6d620840-e07e-4006-b8a1-dbd5b6a95a9d.png)

3. 点击 `Commit`，报错

![image](https://user-images.githubusercontent.com/95261974/170923791-164f0356-be03-45d8-b5ab-7db145cd09c0.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6294356d8aaab7cc1673dda8/intent/6294525b8aaab7cc1673f91c

**Comment by jfang137** [comment]
@hisunnymay 保存后显示的问题解决了，你可以把body再改回去，至于commit抛错还是要xiaobo帮忙看

**Comment by hisunnymay** [comment]
@jfang137 好的，试了一下没问题了。commit抛错是我写错的，是想确认body的数据是保存下来了的。

Checked, it's fixed.
