### ISSUE TITLE
[Improvement]: remove media reply

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

目前 action 中除了 simple reply、list reply 还有 media reply，而 simple reply 中已经支持了 rich card，因此不再需要单独的 media reply 了，需要 remove media reply：
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/37056884/171088510-b8f0b8e1-83c9-44e2-9ba4-15e5adaeae4d.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by jfang137** [comment]
@Zeng666666 是不是external event fill里面的media reply也不要了？

**Comment by Zeng666666** [comment]
@jfang137 是的，media reply 都不要了，以后就直接用 simple reply 中的 rich 了

**Comment by Zeng666666** [comment]
checked
