### ISSUE TITLE
[Bug]: 返回 org list 页面时，有报错提示

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

从任意 agent 返回 org list 页面，会有以下报错提示，但目前并不影响其他操作：

![image](https://user-images.githubusercontent.com/37056884/156300116-26659f0a-2a17-4323-9a16-523f11b22958.png)

浏览器里是这个提示：

![image](https://user-images.githubusercontent.com/37056884/156300564-916aa843-de47-4c0e-948e-8a84ae69c3e5.png)

### Expected Behavior

应当没有报错

### Use Case

/

### Steps To Reproduce

1. 进入任何 agent 的任何页面；
2. 点击顶栏 “logo” 或 “Organizations”；
3. 页面返回 org list 页面的同时，出现报错提示。

### Label of org.project

/

### Framely Link

/

**Comment by jfang137** [comment]
这个应该是之前就修过了

**Comment by Zeng666666** [comment]
正常了
