### ISSUE TITLE
[Feature Request]: Hide ValueCheckFail in Transition's State

### ISSUE THREAD

**Issue by yigexu** [framely/community#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For now, let's hide ValueCheckFail in Transition's State

<img width="721" alt="Screen Shot 2022-06-01 at 9 51 24 AM" src="https://user-images.githubusercontent.com/6505755/171312102-7486c11e-6971-444a-ba94-40c8a94511f9.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
can you give a reason? So that people are on the same page.

**Comment by yigexu** [comment]
For two reason:
1. This is one of the solutions that we discussed, we never really use / test this out.
2. Since we move Value Check to slot-level now, customize it in Transition seems won't bring us a lot of gain. 
3. We don't have a case use this.
We can bring this back anytime when we have a solid case.

**Comment by yigexu** [comment]
@xiaoyunwu 这个你还有问题吗

**Comment by xiaoyunwu** [comment]
nope, I think we should do this.

**Comment by jfang137** [comment]
@Zeng666666 @yigexu 这个选项是从core的 Fill State (entity)里面拉取的，需要更新core

**Comment by jfang137** [comment]
我这里不用动的
