### ISSUE TITLE
[Bug]: after updating libraries, error info: msg.compiler.wrong.confirm.id

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

update libraries之前，commit成功，confirm能正常work
之后update libraries，再点击commit，弹窗error info：msg.compiler.wrong.confirm.id

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/620b7e1c0df75223acbc9d3b/test_case

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/156713124-c1f6074e-4470-4762-8543-6fa1002c7e6d.png)
这些原来是叫Status,什么时候改名的后端代码也需要同步的 @Zeng666666 @hisunnymay

**Comment by Zeng666666** [comment]
后端代码也要同步？

**Comment by jfang137** [comment]
core相关的内容有些是hard code,改名之类的就可能导致hard code失效

**Comment by yigexu** [comment]
应该要让 runtime 改一下。 @XiaoboYuan

**Comment by Zeng666666** [comment]
那现在有哪些是 hard code 的？

**Comment by Zeng666666** [comment]
> 应该要让 runtime 改一下。 @XiaoboYuan

不是，这个是 @xiaoyunwu 改的。。。

**Comment by jfang137** [comment]
![image](https://user-images.githubusercontent.com/16040960/156714428-6d73b6ab-d0c3-4276-859c-d1b979ad04ca.png)

**Comment by hisunnymay** [comment]
Fixed
