### ISSUE TITLE
[Bug][Transition]: extra text reply

### ISSUE THREAD

**Issue by yigexu** [framely/community#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### 配置
Intent Test1
- slota, int
- slotb, boolean
- transition: when slota == 1, text reply "when slota=1"
- _因为 DU 目前有点问题，所以 slota 设置了 implicit sep，会将 slota 自动填为 1_

### 表现
输入 test1 开启对话（没有其他 query），已知 slota 应该被设置为 1，所以
- 预期对话是
```
[TextReply] when slota == 1
[SlotRequest] ask bool
```
- 实际对话是
```
[TextReply] when slota == 1
[TextReply] when slota == 1
[SlotRequest] ask bool
```
问题在于多了一轮 transition reply

### 相关说明
应该和 implicit SEP 有关，如果删除 VR，换为 FrameEvent 回答 1，表现会符合预期

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

playground /testTransition

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/62a04fb731de56451af74271

### Test Case

T1

**Comment by XiaoboYuan** [comment]
fixed
