### ISSUE TITLE
VC annotation for runtime

### ISSUE THREAD

**Issue by yigexu** [framely/community#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

improve VC

### Motivation

VC fail 后
1. 默认 strategy
1.1 clean function parameters 中最后一个被填槽的 slot value，且输出 vc prompt
1.2 重新与 user 对这个 slot 进行交互
1.3 user 应该体验到 clean 和 vc prompt 在重新交互之前，但对 clean 和 vc prompt 之间的顺序无感知；后面也是同样的要求，不再重复

2. customize strategy
2.1 当 builder 在 platform VC recovery strategy 下定义一组 clean slot 后
2.2 clean 所有被 clean slot specified 的 slots value，选择其中 slot order 最靠前的那个开始与 user 进行交互，且输出 vc prompt
runtime 可以选择合适的实现方案。如果实现需要，可以暂时要求 builder delicately manipulate clean slot 的order。如果 runtime 没有明确偏向，则不对 builder 做限制更好。

3. 多个 VC fail 时，将 perform 全部表现
3.1 多个 default strategy fail：同 1.1
3.2 多个 custom strategy fail：同2.2，“所有” 指代的范畴从 2.2 中的 1 个 function 扩增为 3.2 中的多个 function
3.2 多个 default strategy 和 custom strategy fail：runtime 可以选择实现更容易的方案。如果 runtime 没有明确偏向，则优先选择 default strategy。

### Describe alternatives you've considered

#35 
#31
#27
https://naturali-io.feishu.cn/docs/doccnlwW1xSDsaH4pOrCxzQb1Rh

**Comment by XiaoboYuan** [comment]
2.2 不对builder做限制
3.2 选择default strategy是什么意思，忽略所有custom strategy？

**Comment by XiaoboYuan** [comment]
优先选择是不是忽略custom

**Comment by yigexu** [comment]
是。

FYI，我考虑
从逻辑上：default strategy 条件应该更弱。
从体验上：
default strategy：check(验证码), prompt 请重新输入验证码
custom strategy：check(手机号、验证码)，clean 手机号、验证码，prompt 请重新输入手机号
对话体验：输入手机号 / 1301301301 / 输入验证码 / 123456 / 先怀疑输错验证码，而不是先怀疑输错手机号。

但我这个是单点的 case，没什么太大的代表性。

**Comment by XiaoboYuan** [comment]
像只有一类strategy那样把所有的都perform呢？我倾向这样

**Comment by yigexu** [comment]
ok，那就是：
当多个 customize fail 时，无论同时有没有 default strategy fail
都执行所有的 strategy，且交互回到 slot order 最小的那个

**Comment by XiaoboYuan** [comment]
@yigexu @xiaoyunwu @hisunnymay 
VC发布了

**Comment by yigexu** [comment]
checked
