### ISSUE TITLE
[issue]: Init frame-typed slot

### ISSUE THREAD

**Issue by yigexu** [framely/community#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

#### 当前设置
1. Frame1 有两个 int slot：slota、slotb
2. Intent Test3FrameSlotInit 有一个 frame-typed slot frame1，另设置一个 transition 为 frame1 整体 SlotInit。SlotInit 下的 code expression 为 native function initFrame1 （大致是调用无参的 constructor、再单独为成员变量slota赋值）
3. 以上 slot frame1、slota、slotb 全部都是 always ask

#### 当前表现
1. 从 response 中能看到，init 没有为 frame slot 赋值
2. 但是 slota、slotb 作为 always ask 也没有被问。
<img width="280" alt="Screen Shot 2022-06-09 at 5 16 06 PM" src="https://user-images.githubusercontent.com/6505755/172811930-f94a931e-2ec7-4b38-af04-45c2a85b226b.png">

#### 总体预期
对于 init（transition init、及马上要做的 slot-level annotation initialization），我们需要支持 frame-typed slot。
它的表现应当是：
1. 允许 builder 对 frame slot 只提供部分 inner slot value。
2. 如果 builder 提供了 value，就使用它，否则向用户询问。
3. Fill Strategy (never ask) 的规则优先级更高，因此如果 never ask 时 builder 没有提供 value，不向用户询问。
4. 如果最终没有 value（包括非 never ask 询问用户后还是没有 value、never ask builder 没有提供 value），那么由此可能产生的 exception 是合理的、应当由 builder 负责。

我不确定这个部分对于 runtime 而言是新需求，还是 bug，目前的表现似乎介于二者之间。

#### 当前预期
1. 询问 slotb，因为 init 只给 slota 赋值 了
2. 回答 slotb 一个 int 后，进入 response。response 应该输出 slota 是 1，slotb 是刚才输入的那个 int

### Use Case

/

#### 得到当前表现
1. 输入 test

#### 测试预期表现
1. 输入 test
2. 问 slotb 的时候输入随便一个 int

### Label of org.project

playground /testTransition

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/62a04fb731de56451af74271

### Test Case

T3

**Comment by XiaoboYuan** [comment]
fixed.

不过目前的效果是slota会被赋值，slotb不会，直接进入response

因为transition的fill目前是一种directfill，这个case中会直接整体fill frame1，然后就认为frame1交互完成。
