### ISSUE TITLE
Improvement: VC function return

### ISSUE THREAD

**Issue by yigexu** [framely/community#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Background
目前 platform 要求 VC function 必须返回 MV，runtime 根据 MV.size 是否为 0 决定 VC 是否 fail

# Scenario
IUserProfile中，需要验证 ```userInputCode``` 和 ```业务根据 phone 发给 user 的 code``` 是否相同，如果不同则清空 phone 和 userInputCode，提示 user 验证失败，请重新输入手机号。
> Chang's design doc of IUserProfile：https://naturali-io.feishu.cn/docs/doccnmMlGDzVPsyaTvOVstSEnHd#RRkh45 

# Analysis
1. 这个场景应该用 VC 做吗？
我觉得应该，因为这里的策略是：根据一组业务条件进行验证，失败希望清理一些槽位，让用户重填。
2. 验证的 function ```verify(phone, UserInputCode)``` 应该定义成 MV 吗？
我觉得从 builder 的视角看，这个场景只需要验证一条信息/数据，因此 verify 应该返回 SV。

# Proposal
Base on the analysis upon，我们有几种方式支持这个需求：
### 现在的方案
VC 默认 function return 为 MV，builder 用 code expression 将 SV 按结果组装 MV
Something like: ```if(verify() != null) [""] else []```

### twisted方案一
VC 默认 function return 为 boolean
对原来的场景 builder 在 platform 通过 condition 组件定义 MV.isNotEmpty 是否为空来实现

Need support
- platform：VC function source 改成 condition 形式，不再对 VC function return 进行 MV 的限制
- runtime：直接将 builder 给的内容当作判定 VC 的 condition，不再增加 isEmpty 的隐式判定

### twisted方案二
VC 兼容两种 function return，MV 时检查是否为空，SV 时当作 condition 去判定

Need support
- platform：不对 VC function return 进行限制 
- runtime：遇到 MV 不变；遇到 SV 时，将builder 给的内容当作判定 VC 的 condition

# Preference
我个人认为：twisted方案一 > 现在的方案 > twisted方案二
1. 本质上 VC 判断的是一组条件是否满足业务要求，业务计算的结果应该是二维的是 **additional assumption**。
放宽它我们能让 VC 支持更多的场景，也更能容易让 builder 理解。
2. 现在的方案的问题是：用 code expression wrap SV 为 MV，除了 VC 要求这么做，很难解释的通；另外 code expression 比 GUI 选择 condition 增加了额外难度。

### Motivation

/

### Describe alternatives you've considered

/

### Additional context

/

**Comment by xiaoyunwu** [comment]
another thing we can do it use the assisted mode for condition, that way builder can express arbitrary boolean meaning.

**Comment by xiaoyunwu** [comment]
per value (not per slot) value check works?

**Comment by yigexu** [comment]
没有支持过 per value。VC 是在 R-Fill 之后的，没必要设计 per value。
另一个角度看，如果支持 per value VC，intuitively 也应该支持 per value confirmation。当然我们可以设计的 hybrid 一点，让 per value 到 VC 就结束，但是我感觉这个对 conceptual model 影响多了一些，最好等它变成 MUST HAVE 再考虑...

**Comment by yigexu** [comment]
@xiaoyunwu 
right now VC use
<img width="1614" alt="Screen Shot 2022-03-04 at 9 37 43 AM" src="https://user-images.githubusercontent.com/6505755/156682544-36d2d3c0-2af2-4419-b330-c3803b2fe4f2.png">

我感觉我们可以用 condition 组件去替代它，since condition 组件 implies the outcome should be enum (unfortunately still slightly stronger than boolean)。然后我理解 condition 组建自带了 assisted mode 和 raw input mode。
<img width="1805" alt="Screen Shot 2022-03-04 at 9 28 47 AM" src="https://user-images.githubusercontent.com/6505755/156682622-83ea247f-2671-41e3-886f-a1568b244a8b.png">

不过这个主要是交互层面的设计，可以看看 @Zeng666666 对`twisted方案一`前提下，platform 怎么表达有什么想法。

**Comment by Zeng666666** [comment]
可以把 value check 样式替换成 condition 样式，来满足 boolean expression。

不过现在的 value check 也是可以直接用 code expression 来定义 boolean expression 的，code expression 存在的作用就是当 UI 不满足时，不阻挡 builder 的定义。

![image](https://user-images.githubusercontent.com/37056884/156684776-b61e156b-31f6-4559-8ed6-6ce9af7adc76.png)

@yigexu 可以先用 code expression 定义。

**Comment by Zeng666666** [comment]
value check 加 condition 可能没有那么快，因为这里目前要改的话，可能整体涉及弹窗变页面的情况。如果是这样，目前在 UI 组件上定义的内容都会失效，建议全部先使用 code expression。

我需要仔细考虑一下 @xiaoyunwu @yigexu

**Comment by xiaoyunwu** [comment]
@***@***.*** ***@***.***> then can we consider you guys are unblocked
on this? We will fix the UI/UX side later.

**Comment by yigexu** [comment]
@xiaoyunwu 还有一件事需要决定，runtime 的改动需要等 UI 变动后再变吗？
我这么问是因为：现在 VC function source 支持 code expression。Builder can either return [] or boolean, and code expression already allow us to return boolean.

**Comment by Zeng666666** [comment]
这个场景下，function return type 本身是 boolean：

![image](https://user-images.githubusercontent.com/37056884/156686644-f04b4308-56d3-47e5-b400-1680d68fc05f.png)

**Comment by xiaoyunwu** [comment]
We produce issue, and specify the expectation in term of priority, but when
it is worked on should be decided by a different process that pick out from
all the things that we need to work on. So @***@***.*** ***@***.***> your
question should not change how we work. And it is not a question for me.

**Comment by yigexu** [comment]
@XiaoboYuan 你看看`twisted方案一`。builder 现在就可以通过 code expression 向 runtime VC 最终返回 boolean，我想知道如果 runtime 现在调整为预期 VC 最终返回 boolean，那么稍后 UI/UX 稍后改动对你有影响吗？
如果没有，我给你 file a feature request。

**Comment by hisunnymay** [comment]
@XiaoboYuan 这个返回值应该还没有改成boolean，尝试用返回值为boolean的function作为VC fucntion，报错：ValueCheck = ValueCheck(session, {returnFalse(num_1)!!.isNotEmpty()},

bot地址：https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/intent/62302e940171eb6ab6d257a4/slot/62302ebb0171eb6ab6d257aa

**Comment by XiaoboYuan** [comment]
@hisunnymay @yigexu @xiaoyunwu @Zeng666666 
现在的预期是什么？
1. 如果function invocation
 1.1 返回mv，codegen添加isNotEmpty()形成一个Boolean
 1.2 返回Boolean，codegen不修改直接使用返回值
 1.3 返回别的呢？string什么的，禁止？
2. 如果code expression，codegen不修改直接使用返回值，builder保证返回Boolean

**Comment by Zeng666666** [comment]
@XiaoboYuan 根据 #88 的提议，预期应当是优先 code expression，builder 确保返回 boolean。

@hisunnymay 现在应当是在 #1.2 这个场景，这个目前可以正常 work 吗？还是也需要作改动？

**Comment by XiaoboYuan** [comment]
@Zeng666666 需要改动，目前并没有完全满足我写的预期，我是确认一下预期是什么

**Comment by Zeng666666** [comment]
@XiaoboYuan 好的，明白了。
目前是确保 code expression 能够 work。
function invocation 有可能会被隐藏，暂时不需要考虑那么多。

**Comment by XiaoboYuan** [comment]
@hisunnymay 
fixed. 
不过这些vc里面好像还有一些nullable相关的东西需要builder修改，code expression需要builder对nullable负责，包括function返回nullable的时候用到VC中需要!!

**Comment by hisunnymay** [comment]
@yigexu @XiaoboYuan checked.

- 如果function invocation
   - 返回mv，codegen添加isNotEmpty()形成一个Boolean -> [Return mv - Function invocation](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/test_case)
   - 返回Boolean，codegen不修改直接使用返回值 -> [Return boolean - Function invocation](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/test_case)

- 如果code expression，codegen不修改直接使用返回值，builder保证返回Boolean -> [Return boolean - Code expression](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622034282b38932409a2582f/test_case)
   - 注：如果function是nullable, code expression需要添加`!!`，以确保返回值是`boolean`，而不是`boolean？`
