### ISSUE TITLE
[Bug]: Failed to add a column when its type is concrete frame

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#453]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前如果 Provider - frame 中, slot 类型为 concrete frame (implement interface frame) ，那么 deploy 该 provider后，生成的table 不会包含 这个slot。

- Frame (table) 的设置

![image](https://user-images.githubusercontent.com/95261974/173302100-6b9309c1-f405-4ffb-8693-a8328c343bae.png)

- 生成的table

![image](https://user-images.githubusercontent.com/95261974/173302238-aa120c61-35ed-4443-9715-04745f2652c7.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62a6d99fd18c9da435994cf3/frame/62a6d9a9d18c9da435994cf7

**Comment by yigexu** [comment]
@xiaoyunwu 我们之前没有明确要求过 nested concrete frame， (只要求过作为 function return 的 concrete frame 会被视作 composite type)，所以我觉得这里在存储上应该是一个 composite type。

**Comment by hisunnymay** [comment]
目前没有这个 use case 先 close 了
