### ISSUE TITLE
Smooth the GAP in State update

### ISSUE THREAD

**Issue by yigexu** [framely/community#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Background
Right now，我们不同人之间对 state update condition mode 中 condition check 的时机理解不同。

# Terms
1. R- stands for concept of runtime
2. P- stands for concept on platform
根据大家的理解，我发现有：
3. R-Fill: 交互上 user 已经给出一个 slot value (i.e. from VR candidate, user-response to prompt)
4. R-Done: slot 的全部交互已经完成
5. P-Candidate: 对应 R-Fill
6. P-Fill：对应 R-Done

# Expectation
condition check 应该在 P-Fill，而不是 P-Candidate。
如果有需要，我们可以展开讨论。

# Behaviour right now
<img width="260" alt="Screen Shot 2022-03-02 at 5 54 04 PM" src="https://user-images.githubusercontent.com/6505755/156338381-932a3dbe-0b66-436d-b8de-82fdfc7f3638.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
Do you think we should wait a bit until we have some ideal on how composite
action works out, I feel we have more info then.

**Comment by yigexu** [comment]
我主要想 raise the issue to stakeholders，runtime暂时可以wait。
这个 gap 在设计 bot 时影响挺大的，所以需要 @xiaoyunwu @yigexu 我们两个先达成一致，应该把它视作 P-candidate 还是 P-fill。

**Comment by yigexu** [comment]
@xiaoyunwu 那先按照现在的表现，也就是P-candidate / R-Fill去考虑？

**Comment by xiaoyunwu** [comment]
ok.
