### ISSUE TITLE
[Bug]: Deployment error after setting unique keys

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前如果前端添加了 unique key 后，deploy 会报错：

> sql:CREATE UNIQUE INDEX "idx_6962747eeea5fdbeeaa0c80bcac6744c" on "t_0617"."TestUnique"(**""int_1""**, ""int_2"");
 err:pq: zero-length delimited identifier at or near """"

在pgAdmin中，去掉一对引号，不会报错
> CREATE UNIQUE INDEX "idx_6962747eeea5fdbeeaa0c80bcac6744c" on "t_0617"."TestUnique"(**"int_1"**, "int_2");

![image](https://user-images.githubusercontent.com/95261974/174229863-ea11a3d9-9b14-491f-9d16-bb93f62894aa.png)

### Expected Behavior

如果builder定义的内容没有问题，添加了 unique key 后应该能正常deploy

### Steps To Reproduce

在 [t_0613](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62abdf82baf18c28a3004a4e/version) 中点击 Deploy

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62abdf82baf18c28a3004a4e/frame/62abf263b7dc0992f419ec1a

**Comment by yigexu** [comment]
<img width="933" alt="Screen Shot 2022-07-21 at 2 08 17 PM" src="https://user-images.githubusercontent.com/6505755/180145765-250ec472-d86c-4377-89a7-a78af2370918.png">
https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b87fff5c77cdfc256d41/frame/62032341a7efe61fe44fdf74
@HuiCheng 我也遇到了这个问题

**Comment by hisunnymay** [comment]
@HuiCheng 哈喽，现在修改 unque key 从 num_1 替换为 num_2 ，然后 deploy，之前添加的 unque key: num_1 的限制好像还在。

1. backoffice 报错：Key (num_1)=(1) already exists. duplicate key value violates unique constraint \"idx_2b8f5664ac4bf11141499d40edb5a5f7\

![image](https://user-images.githubusercontent.com/95261974/207768592-bda3fef1-6cdd-447b-86b8-2a28fbd26556.png)

2. 平台配置：只设置了 num_2 为 unique key

![image](https://user-images.githubusercontent.com/95261974/207768840-0e663adc-8e63-4c05-bd10-4511134bb3c0.png)

**Comment by hisunnymay** [comment]
Fixed，现在能添加一组或者多组 unique key

![image](https://user-images.githubusercontent.com/95261974/207775624-1368d6b8-8c4a-4436-ab1b-4a5342f418e4.png)
