### ISSUE TITLE
[Bug]: Skip value check and confirmation after configuring initialization

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前如果有个 slot 配置了 initialization， 那么该 slot 的 value check 和 confirmation 都会被跳过

![image](https://user-images.githubusercontent.com/95261974/174517508-9419a329-effc-47c2-8f78-9ffa76488a8e.png)

### Expected Behavior

根据 [[PRD] Initialization（22/06/10）](https://naturali-io.feishu.cn/docx/doxcnrccK602waazcooquw2tbdg) - 问题

   > 如果 builder 定义了 confirmation 和 value check，我们就认为需要走 confiramation 和 value check，如果 builder 没有定义，我们就认为这个是直接 fill 的。

所以如果有个 slot 配置了 initialization， 那么该 slot 的 value check 和 confirmation 不应该被跳过

### Steps To Reproduce

详见 [Test Cases](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ac0fc6b7dc0992f419f665/test_case) - Skip value check and confirmation - 0620

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ac0fc6b7dc0992f419f665/setting

**Comment by XiaoboYuan** [comment]
@xiaoyunwu 
我们曾经讨论过，platform上的fill slot都是directfill，这种是没有vc和confirmation的。
如果platform的fill都用interactive fill，那我这也是可以的，但是也许builder不能认为执行了fill action这个值就已经在了，有可能造成别的问题，当然也有可能没有问题
还有一种方法是platform就区分这两种fill，让builder选择
这三种我这都是没问题的，但是目前的概念是这样区分的，需要做trade off

**Comment by yigexu** [comment]
那么是不是平台上就没有direct fill了？intent start 的 assignment 也会跟着改对吗？
@XiaoboYuan @xiaoyunwu

**Comment by xiaoyunwu** [comment]
intent start need fill slot action?

**Comment by yigexu** [comment]
> 

让我重新问一下：direct fill 的改动是只针对于 fill slot 这个 action 吗，还是平台上就不会再涉及 direct fill 的 概念了呢？
@xiaoyunwu

**Comment by xiaoyunwu** [comment]
@Yige, My proposal is the change the behavior for fill slot action on the
platform, not the remove direc fill function.
@XiaoboYuan

**Comment by XiaoboYuan** [comment]
@xiaoyunwu @yigexu 
应该是所有使用fill action的地方会变成interactive fill吧，intent start的assignment因为不是fill action，所以可以是direct fill

**Comment by xiaoyunwu** [comment]
right, just change semantic on fill slot action itself. Not removing direct
fill functionality.

**Comment by yigexu** [comment]
get；那么我们 agree 对 mv slot 的预期是：先通过 initialization 或者 prompt 把 slot 填到 commit，然后再整体 value check、confirmation，对吗？

**Comment by yigexu** [comment]
那么 mv 对 init 的预期是什么呢 @XiaoboYuan

**Comment by hisunnymay** [comment]
@XiaoboYuan 试了一下，现在没有skip Confirmation 了，但如果对 Confirmation 的回答是 no，好像会跳过 prompt，而继续用 associate 的值 interactive fill slot。
同理，如果value check failed，好像也是会跳过prompt，最后的现象是：输入test 后会报错

![image](https://user-images.githubusercontent.com/95261974/174756955-29e6e33b-02af-4584-8256-5e033f9bfc02.png)

**Comment by XiaoboYuan** [comment]
这个目前是预期的结果，因为vc或者confirm清除掉slot的值之后，slot不保留任何状态，再次来到这个slot的时候，仍然会init这个值，所以又到confirmation了
@xiaoyunwu @yigexu 可以研究一下这个体验

**Comment by Zeng666666** [comment]
init 应当只在第一次的时候使用。如果 vc failed、confirm no 表示初始值不满足当前业务逻辑或用户需求，所以逻辑上讲应当 prompt 追问，因为再 init 是没有意义的，会锁死循环

**Comment by XiaoboYuan** [comment]
@hisunnymay 修复了，可以再试一下

**Comment by hisunnymay** [comment]
Checked, 现在不会跳过confirmation和value check了。

目前对于 Confirmation No 和 value check fails 的情况会让 user 重填那个slot，详见 [Confirmation no & Value check fails](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ac0fc6b7dc0992f419f665/test_case)

**Comment by xiaoyunwu** [comment]
We need to figure out how init works with mv slot when we have more use
cases.  @Yige
