### ISSUE TITLE
[Feature Request]: Value Check Recovering

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

需求来源：https://naturali-io.feishu.cn/docs/doccnOVxdsbrMubw9ITfFLlKzMe

PRD：https://naturali-io.feishu.cn/docs/doccn3HxUv51SFPMjDmAHmmZs7b#

### Motivation

/

### Describe alternatives you've considered

/

**Comment by XiaoboYuan** [comment]
@Zeng666666 这个应该很早就结束了 我们怎么标记完成？

**Comment by Zeng666666** [comment]
@XiaoboYuan  可以把 label 的 working 换成 waiting for review，这样就可以知道了。
