### ISSUE TITLE
[Bug]: Can't save assocation value for the first time clicking "Save" button

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前在 Initialization - Association 中输入值之后，第一次点击“Save”之后，会报错：_Association code is required!_。需要第二次点击“Save”才能保存输入的值。

看上去好像是需要将输入光标移出 code expression 输入框才能保存在输入框中输入的内容。如果在输入值之后，点击输入框外任意位置之后，再点击”Save“就能保存输入的内容。

https://user-images.githubusercontent.com/95261974/174702363-58247195-6667-4b32-be58-f89318a8b5ef.mov

### Expected Behavior

如果可以，能不能让builder第一次点击“Save”之后，自动保存code expression中输入的内容呢？

试了一下：Value check中也有code expression，在输入code expression之后直接点击“Save”可以保存上

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62a02e7b07bd1f0e0917e8d3/intent/62a2dcf965642d7091fe0cc7/slot/62abdc0cbaf18c28a300369f

**Comment by jfang137** [comment]
我这里没有复现，我给这个save的响应加了延时，过会发完后看看你那里还会不会复现

**Comment by hisunnymay** [comment]
@jfang137 你输入code expression后，是直接点击save的吗？我如果直接点接save，不点击空白处的话，我这里还是会有报错..

https://user-images.githubusercontent.com/95261974/174741744-769669be-3f5d-48b4-ae26-65a7dd1faa64.mov

**Comment by jfang137** [comment]
bug先别关，我之后再尝试吧，应该不阻塞你的事情

**Comment by hisunnymay** [comment]
@jfang137 不影响的，你有时间再看吧，不着急。

另外，我问了一下yige和lu，他们chrome的版本是：Version 102.0.5005.**61** (Official Build) (x86_64)，在他们电脑上也无法复现这个问题。我的chrome的版本是：Version 102.0.5005.**115** (Official Build) (x86_64)，不知道和这个是否有关系
![image](https://user-images.githubusercontent.com/95261974/174746638-4fc77540-f470-466b-9d00-ae2a8586c7b5.png)

**Comment by jfang137** [comment]
有可能的，这个是跟内核的失焦事件的响应次序有关

**Comment by hisunnymay** [comment]
@jfang137 好的，明白了

**Comment by hisunnymay** [comment]
重新试了一下，现在没有这个问题了
