### ISSUE TITLE
[Bug]: DU converts time "9:00" to "21:00"

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当user回答LocalTime的时候，DU会把 "9:00" 转换为"21:00"，只有“9:00 am”才会被转换为”9:00“
example is in [example - 4](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6205cc0ad980a8d37823fb8d/test_case)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6205cc0ad980a8d37823fb8d/test_case
![image](https://user-images.githubusercontent.com/95261974/156489197-6d1f0484-21db-44dd-bcbf-3fa2c713a9e9.png)

**Comment by Zeng666666** [comment]
test4 是那个 intent？这里看起来是有时区干扰

**Comment by hisunnymay** [comment]
FourthIntent

**Comment by Zeng666666** [comment]
这个确实是有问题的。从 test case 结果上看，没有加 am，9:00 就会变成 21:00，这里应该是偷偷有了一个时区的特殊处理。

在 @hisunnymay 的 agent 上输入“test4”，“now”，得到时间是“21:34:29”；在这个时间之前，就是正常的；在这个时间之后（上）的就会变化：

![image](https://user-images.githubusercontent.com/37056884/156502825-a7870dc2-c414-44b2-87eb-1ba3473e16d9.png)

LocalTime 是不是应该是中立的： https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html

![image](https://user-images.githubusercontent.com/37056884/156501922-aab4807d-d712-4793-9d42-96464bd07f5f.png)

**Comment by hisunnymay** [comment]
感觉LocalTime应该是中立的，它是不带时区的，然后duckling的示例也是默认7 -> 7:00, 7 p -> 14:00, 不知道是哪里处理的时候带上了时区
![image](https://user-images.githubusercontent.com/95261974/156504961-b986918f-90db-4adb-9bc7-704ced937955.png)

https://github.com/facebook/duckling/blob/main/Duckling/Time/EN/Corpus.hs
![image](https://user-images.githubusercontent.com/95261974/156505024-42812fe3-674a-4da8-8772-0545c247c161.png)

**Comment by xiaoyunwu** [comment]
Will take a look later.

**Comment by xiaoyunwu** [comment]
@hisunnymay can you update the bot (assisted mode) is not supported anymore.

**Comment by xiaoyunwu** [comment]
fixed.
