### ISSUE TITLE
[Bug]: Can't switch to External Event when prompt strategy is Always Ask

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前新建一个slot的 Prompt Strategy的初始值是：`Never Ask(deprecated)`, 在这个状态下可以选择 `External Event`。当选择了 `Always Ask`后，就不能再切换为 `External Event` 了。
同理，选择了 `Conditional`, `Recover Only`也是一样的效果。

![image](https://user-images.githubusercontent.com/95261974/174934979-d4590f6c-f49f-48d5-8bb6-da7efa0247be.png)

![image](https://user-images.githubusercontent.com/95261974/174934938-555dc412-2961-46b1-a861-6f8a3fb0be68.png)

### Expected Behavior

不论 Prompt Strategy 是什么，应该都可以切换为 `External Event`

### Framely Link

https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/62b194ca9b740582414d4227/intent/62b27fe79b740582414d66a8/slot/62b27fe99b740582414d66ac

**Comment by Zeng666666** [comment]
因为这里有限制是，添加了其他 annotation 就不能选择 External Event。有可能是因为每个 strategy 都自动添加了 prompt 的原因？因为有了 prompt 所以不能切换 External Event？这里似乎应该把 prompt 刨除 @jfang137

**Comment by jfang137** [comment]
好的，我把添加了prompt annotation则禁选external的限制移除

**Comment by hisunnymay** [comment]
Checked, 现在如果只有 prompt，ask strategy是可以切换为 External event
