### ISSUE TITLE
[Feature Request]: Initialization limitation：only one can be added

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

根据 issue #478 的讨论，需要前端先限制 initialization 的添加数量；目前 slot level 只允许添加 1 个 initialization，因此当 builder 添加一个条目后，置灰添加按钮（同现在 value rec 体验）

### Motivation

/

### Describe alternatives you've considered

/

**Comment by hisunnymay** [comment]
@jfang137 能顺便把value check的限制添加多条的方式也改成:添加一条之后就置灰Add 按键吗？

目前value check添加一条后，再添加会提示: _The slots are repeated._ 不太便于builder理解..

**Comment by Zeng666666** [comment]
checked，现在 value rec、value check、initialization 在 slot level 体验是一一致的，都暂时限制为只能添加一个条目。
