### ISSUE TITLE
[Bug]: EN Reply appears sometimes

### ISSUE THREAD

**Issue by yigexu** [framely/community#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

struct:
<img width="1680" alt="Screen Shot 2022-06-22 at 4 11 31 PM" src="https://user-images.githubusercontent.com/6505755/174979786-d8aa9d07-3dc2-48c2-8842-037ec7b388b6.png">

en 有时候没有 reply
<img width="1677" alt="Screen Shot 2022-06-22 at 4 11 46 PM" src="https://user-images.githubusercontent.com/6505755/174979826-97661794-81b8-4aa5-8e06-61ed2b1057e1.png">

en 有时候又有 reply
<img width="1671" alt="Screen Shot 2022-06-22 at 4 13 14 PM" src="https://user-images.githubusercontent.com/6505755/174979895-2e0f5421-9cd0-4936-949f-4e3ba4d0dffd.png">

### Expected Behavior

en 总是应该有 reply

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantL214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d1ff5c77cdfc255d0f/intent/61d52d9e31c6ed847d5940f1/response/62020200d0fb8a89a4dbdb5a

**Comment by jfang137** [comment]
https://github.com/framely/community/issues/528 根这个有可能是同一个问题

**Comment by xiaoyunwu** [comment]
close it for now.
