### ISSUE TITLE
Polish VR hard under uncooperative user

### ISSUE THREAD

**Issue by yigexu** [framely/community#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Background
过去我们仅定义了 VR hard 应该向 user 表达什么，没定义当 user 还是回答了属于 slot type，但不属于 VR candidate list 的 slot value 时，bot 应该怎么表现。
让我们把这种情况叫做 `不合格`。

# Phase1: 对话逻辑
1. DU 能听懂
2. 但runtime 应该不接受`不合格`的 slot value；也就是重复之前的预期、表现
- VR-N 重复问 prompt + VR
- SEP 重复问 SEP
- MV 重复问 MV + VR (by entry)

我觉得这是正确的对话逻辑，如果需要可以再讨论。

# Phase2: 对话体验
Phase1 提供的体验需要 user 需要根据 context 理解“绿色”`不合格`，是一种与 user 隐式的对话状态对齐。
> 你想要什么颜色？我们有红色、蓝色。
> 绿色。
> 你想要什么颜色？我们有红色、蓝色。

This will be very dangerous when it comes to MV.
> 你还想要什么颜色？我们有红色、蓝色。
> 绿色。
> 你还想要什么颜色？我们有红色、蓝色。 <== Bot 在追问`不合格`的 entry，还是询问 user 要不要再增加一个 entry？

因为我们必须增加 inform，显式地与 user 进行对话状态对齐。

### VR control 方案
- platform：为 VR hard 增加 prompt for invalid
- runtime：无论 VR-N 还是 SEP 失败，都应该先输出 prompt for invalid，然后进行 Phase-1 的对话逻辑。

### SU (State update) 方案 
- runtime：将`不合格`的 slot value 填进去，再清理掉 
- platform：SU condition 的时机是 P-Candidate / R-fill
- builder：使用 SU condition + reply，customize inform，告诉 user `不合格`

### VC 方案 `(Updated 2022/03/04)`
- runtime：
  - VR-N hard 和 soft 表现相同 (展示 function result list；当 user 选中的内容匹配到多个 candidates时展示结果，否则填槽)
  - 支持 VC per value 触发
- builder：使用 VC 检查`不合格`的 并告诉 user

#### VC for MV 现在需要分开支持 per slot 和 per value 吗？

   目前没有这样的 use case。逻辑上 per value 的最后一次一定 cover 了 per slot，体验上越快提示出问题越好。
   我觉得可以先支持 per value。

# More
1. Runtime 现在对 Phase-1 的表现是：使用`不合格`的 slot value 去 shrink list。
> 你想要什么颜色？我们有红色、蓝色。
> 绿色。
> 你想要什么颜色？我们有 (VR 没有 candidate)
> 红色。
> 你选择了红色。(预期还在color，没有变)

2. 需求来源：Chang's reservation design DOC `Case2-1` 
https://naturali-io.feishu.cn/docs/doccnTvDKN8nTG40sfR0avYC3Gb

### Motivation

/

### Describe alternatives you've considered

/

**Comment by Zeng666666** [comment]
invalid 和 value check 有什么区别吗？
那现在 vr soft 是什么表现呢？

**Comment by xiaoyunwu** [comment]
This is a very valid concern, but I think we need a bit more time to really
understand the issue here. For example, if "green" is on the next page,
when it is valid input, but if green is not possible, then we need to think
about how we capture that, and how we define the behavior.

**Comment by xiaoyunwu** [comment]
we already have per value VC (not per slot for mv), correct? will that be
enough?

**Comment by yigexu** [comment]
1. green 在第几页不影响 VR 的表现：在 candidate list 就会被 shrink 出来；不在 shrink 之后就是 []。

2. 没有 per value VC，具体解释和 major concern 在 #45 comment 中。如果想用 per value VC 去做，我觉得我们还需要 discuss 这个体验对 builder 是否合理。
Briefly 说一下我的 concern：尽管我在 DOC 中提供了用 VC 应该解释的视角，但是我不倾向于这样设计。原因是：我觉得这是在 split VR's functionality。一个 annotation 应该可以独立、完整地完成一件事，用 VC 解决的话，如果 builder 只配置 VR，不配置 VC，DOC 中的 MV case 没办法 function。

**Comment by xiaoyunwu** [comment]
I remember we have some per value things? what is that?

**Comment by xiaoyunwu** [comment]
If we consider VR as composite component, then we want to make its behavior
being composed out of other component. It is dependent on how we look at
it. The key is always can we solve a problem without new tool?

**Comment by Zeng666666** [comment]
> 

Why no need for slot value check? https://naturali-io.feishu.cn/docs/doccnFESIx99djTW4elfyeYHi8c 

是这个吗？

**Comment by Zeng666666** [comment]
另，从设计角度讲，value rec 与 value check 是两个 component，就像 prompt 与 value rec、value rec 与 confirm 的关系一样，可以分别声明，这样设计也可以更好的进行 reuse。

**Comment by Zeng666666** [comment]
从体验角度讲，platform 应该确保每一部分的独立，这样 builder 可以来决定自己的逻辑，而不是 platform 决定 builder 的逻辑。

**Comment by yigexu** [comment]
I remember we have some per value things? what is that?
@xiaoyunwu VC 没有。和 per value 有关的，要么是 mv annotation (prompt & confirm)，要么是本身 granularity 就是很小的 (比如 VR、State update 的某些情况)

**Comment by xiaoyunwu** [comment]
I remember we did something per value for MV, what is that?

**Comment by yigexu** [comment]
你说的是哪个层面的？
per value 就意味着在谈论 MV 了。
> 和 per value 有关的，要么是 mv annotation (prompt & confirm)，要么是本身 granularity 就是很小的 (比如 VR、State update 的某些情况)
这是我能回忆起来的。

**Comment by yigexu** [comment]
@xiaoyunwu 我把 VC 方案加上了，如果讨论决定这个方向，我再 validate 细节

**Comment by xiaoyunwu** [comment]
https://naturali-io.feishu.cn/docs/doccn9E1RBgzWCPjMFS5e0IAoNh

**Comment by xiaoyunwu** [comment]
If this is about verify candidate value from bot side, then it should be
handled by vc. So please.

**Comment by xiaoyunwu** [comment]
Another way to think about it is: what happens if user said this and we do
not have vr?
