### ISSUE TITLE
[Bug]: Something dark in intent return

### ISSUE THREAD

**Issue by yigexu** [framely/community#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

<img width="1469" alt="Screen Shot 2022-06-23 at 4 51 21 PM" src="https://user-images.githubusercontent.com/6505755/175258732-8129c55a-df9d-4f89-a7ca-48aee1a9e04d.png">

<img width="1469" alt="Screen Shot 2022-06-23 at 4 54 49 PM" src="https://user-images.githubusercontent.com/6505755/175259597-c352109c-4064-4d8a-8312-6e2c27ab7a91.png">

不知道是不是能看出来，框红的部分是一个黑色的填充矩形，它覆盖在了code expression的代码上。

### Expected Behavior

编辑框内不应该有遮盖

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantL214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d0ff5c77cdfc255d0d/intent/61f0b1826a5313c74a2df848

**Comment by jfang137** [comment]
这是ide一般会有的，推荐换行的宽度提示，像这样的
<img width="576" alt="image" src="https://user-images.githubusercontent.com/16040960/175261697-49c8042a-7642-42a3-8c93-3814033727d8.png">

**Comment by jfang137** [comment]
对的，竖线右边是左边的缩略。我看下关闭这个的接口
