### ISSUE TITLE
[Feature Request]: Fill Strategy: Direct Fill

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### 0806 UPDATE

Fill Strategy（原 ask strategy）还是需要一种“Never Ask”的 strategy，因此将原 Never Ask 重新归位，前端展示为 Direct Fill。

Direct Fill 只能添加 Initialization Annotation，没有 prompt，其他 annotation 不能添加。

----------

~~根据最新需求（intent return 相关）需要为 prompt strategy 添加新的 strategy：Assignment。Assignment 其实就是原来的 Never Ask，因此应当是一个前端的改动。~~

~~前端限制：当 prompt strategy 选择 Assignment 后，自动添加 initialization annotation，不可以 remove，也不可以添加其他 annotation 了。~~

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
@jfang137

**Comment by hisunnymay** [comment]
@xiaoyunwu 哈喽，我们现在能支持 Assignment 吗？

@Zeng666666 和我讨论了一下，我们觉得 Slot：cart[] 的 Ask Strategy 需要设置为 Assignment (i.e Never Ask) 

```
分析了另外两个 Ask Strategy，目前都不能实现预期的对话
```
1. Conditional：如果把 Condition 设置为 false，就无法通过 Initialization 为 cart[] 赋值
2. Recover Only：因为 cart[] 是 Multi-valued Slot，所以用 Initialization 为 cart[] 赋值后，bot 会输出 mv prompt。但是 cart 是 Frame 类型的slot，所以 user 无法直接填写 cart 的值。

**Comment by Zeng666666** [comment]
checked

**Comment by xiaoyunwu** [comment]
let's do it.
