### ISSUE TITLE
[Bug]: "get me star wars at 12:00" can not work

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

订电影票场景，需要 user 提供 movie、localTime。

- happy path 可以走通：即通过先用“qwer”触发 intent，再根据 prompt 填槽的方式，可以完成；
- 但第一句话如果有 slot value，在 expression 中定义过，value 不会填槽，会重新追问：
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/37056884/175934317-4b962d42-082d-4938-a870-27a1a9264d45.png">

根据 try it now 上的信息可以看到 DU 已经理解正确了：
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37056884/175935251-e7baf94c-5f83-4de2-b78d-f1d340762974.png">

那么按照 intent 的定义，此刻应当进入到 frame level 的 confirmation，但现在的表现是追问我想看哪部电影。但当我说完 star wars 后，localTime 的值被填进去了，且进入了 frame level 的 confirmation：

<img width="518" alt="image" src="https://user-images.githubusercontent.com/37056884/175936153-c8aea201-8905-4ae2-abdd-0410cb3d2a48.png">

### Expected Behavior

如果 user 在触发 intent 的同时，直接提供了多个 slot 的值，比如 “star wars at 12:00”、“transfer ¥600”、“buy ticket from beijing to shanghai”，那么 bot 的表现应该是什么呢？

假如 DU 都理解正确了，那么应该是拿到这些值，依次走定义在各个 slot 上的 value check、confirmation，再进行 frame level 上的 confirmation，（transition 应该是什么时候触发什么时候走）最后进入 response。而不是始终追问 user 第一个 slot 的 prompt。

### Use Case

/

### Steps To Reproduce

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/62b2d8c41d48e451a29be158/test_case

- intent：BuyTicket

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/37056884/175939409-2fcf9d30-3eba-484c-a965-5d54df8f4093.png">

- Test Case 图中红框部分

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/37056884/175939275-69cba5d3-bd20-4645-8516-bcf307fe4175.png">

### Label of org.project

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/62b2d8c41d48e451a29be158/intent?page=0&imported=false&search=

### Framely Link

test001.BuyTicket

**Comment by XiaoboYuan** [comment]
这个问题可能是这样的，自从VR增加了starting point这一概念之后，任何配置了VR的slot都会进入VR，builder有责任根据user提供的这个值使得VR结束（一种方式是配置sep使它结束）, 这个值的引用方式是 it
@Zeng666666

**Comment by Zeng666666** [comment]
@XiaoboYuan starting point 是什么？
it 是在哪里引用就可以正常 work 了呢？

**Comment by Zeng666666** [comment]
这里的体验是，end-user 一上来就对 bot 说，我想买两张八点星战的票。这个时候应该是 end-user 提供了所有的信息，按照 builder 的定义应该是一个 slot 一个 slot 去 check 或 confirm（如果定义了的话），如果都合格活没有定义就进入 response。

目前这个 case，只有 movie 设置了 value rec，体验是如果 end-user 直接提供了“星战”，但填不进不去一直追问，应该是去 value check 和 confirmation。

如果把条件判断定义在 source 中，有值就进入 sep，似乎也是和业务逻辑预期不相符的，因为并不是电影只剩下一个可选了，而是有三个备选项，end-user 主动表达了一个，然后进入了 sep，这个体验似乎和 bot 追问 end-user 回答是不一样的，但按理说应当是一样。

**Comment by Zeng666666** [comment]
@xiaoyunwu 感觉这里的体验是有问题的：

1. end-user 提供了 value，却进入了 sep，但业务逻辑本质不是 sep，我们不应该用 sep 解决问题。因为从业务逻辑讲，end-user 主动提供“星战”应当和通过 bot 追问，end-user 回答“星战”得到一致的体验才对。

2. 况且我们还有 sep 会 skip confirmation 逻辑。这样的话，end-user 主动表达，反倒还不如被动追问得到的体验好。因为 confirmation 的话术 end-user 就得不到了。

3. 具体到实际的业务逻辑，对于 end-user 主动提供 value 的判断不是 null 和 not null，是是否满足各种条件，比如 hard vr 需要在业务范围内，比如 mv vr、frame slot vr，那是不是所有的 value 都需要 builder 自己写成 function 或 if else 在 source 里先进行判断？
   - 如果 builder 需要付出这么大的工作量，才能接住主动表达的用户体验，那这个 vr 是不是 builder 默认不启用会比较好？
   - 或者 builder 手动罗列在 prompt 中，虽然 end-user 用不了 index，但 builder 的体验和 end-user 的体验相对于现在的 sep 来讲会更好（下图是 remove vr 后的体验，是预期的体验）:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/37056884/177531184-b3ccaef3-ba1b-478b-80fe-b4b1d81490fd.png">

**Comment by Zeng666666** [comment]
for example: value rec hard 的体验，就需要 builder 自己来定义了

- end-user 主动触发后，现在的 SEP 体验：

<img width="527" alt="image" src="https://user-images.githubusercontent.com/37056884/177538992-687bb24d-ebe8-4b9f-af86-27d75c546736.png">

- end-user follow bot 追问的正常 hard 体验：

<img width="521" alt="image" src="https://user-images.githubusercontent.com/37056884/177539408-ade07e16-12ee-4959-a198-16088580e4e1.png">

**Comment by Zeng666666** [comment]
感觉应该不是在 source 里写条件，应该是给 value rec annotation 加 condition，允许 builder 定义什么条件下会进入 value rec，什么条件下不进入 value rec？

**Comment by xiaoyunwu** [comment]
@XiaoboYuan what is the correct way to specify this? we can use if else, or a post filtering, it is not working yet. If user have not provided a value, how will "it" be evaluated to?

**Comment by XiaoboYuan** [comment]
> @XiaoboYuan what is the correct way to specify this? we can use if else, or a post filtering, it is not working yet. If user have not provided a value, how will "it" be evaluated to?

null

之前的假设不是builder保证这个正常work？我只能想到sep的方式，由此还讨论了多一条sep的输出暂时可以接受这件事

**Comment by Zeng666666** [comment]
明白了，就是这样设计的，因此不是 bug，closed

**Comment by Zeng666666** [comment]
@xiaoyunwu 补充 vr-soft 体验，soft 中没有 sep，所以无法通过 skip sep 完成体验：

1. 如果 source 定义为 function，无法跳过 vr，会继续追问：

<img width="517" alt="image" src="https://user-images.githubusercontent.com/37056884/177909216-6e2c6f1a-3ea0-402d-a586-a817240a8394.png">


2. 如果 source 定义为：`if (it != null) listOf(it) else threeMovies()` end-uuser 主动说：get me top gun at 9:00 会继续追问 end-user ：

<img width="524" alt="image" src="https://user-images.githubusercontent.com/37056884/177908883-4171575d-3b9c-4297-9289-b79bae3c6695.png">

**Comment by xiaoyunwu** [comment]
This is a good catch.

**Comment by Zeng666666** [comment]
🎉🎉🎉 checked
