### ISSUE TITLE
[Feature Request]: Transition condition trigger timing

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

PRD：https://naturali-io.feishu.cn/docx/doxcnMj6nQfetB2fBGEFSOODrUd 

### Motivation

/

### Describe alternatives you've considered

/

**Comment by XiaoboYuan** [comment]
done

**Comment by Zeng666666** [comment]
checked
