### ISSUE TITLE
[issue] Correct Initialization under MV's behaviour

### ISSUE THREAD

**Issue by yigexu** [framely/community#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

对一个 mv int slot 设置 initialization listOf(1,2,3) (假设 prompt strategy 是 always)，目前表现是：不理会 annotation 设置，即从头开始问。这样的体验难以接受。

### Expected Behavior

potential behaviour includes:
1. 直接填 1、2、3，然后问 hasMore，如果回答了 value，进行交互
2. 填 1、交互；填 2、交互；填 3、交互；问 hasMore，如果回答了 value，进行交互

Right now，(在没有场景支持二者的前提下)，从设计的一致性考虑(即 sv initialization 改为带交互是为了即时发现、反馈问题)，希望体验为 2.

### Use Case

配置
1. Case3 有 slota，type int[]，被 init 为 [1,2,3] 
2. Case3 有 transition，会不停地把 slota 的 value 打出来用于 debug
3. 其他设置，可以不用管

### Steps To Reproduce

输入 case3
- 目前：会追问 Case3.slota 的 prompt (not mv-prompt)
- 预期：如果填进去了应该问 mv-prompt

输入 1
- 目前：输出信息包括“[TextReply] slota: [1]”
- 预期：如果填进去了应该是“[TextReply] slota: [1,2,3,1]”

### Label of org.project

playground /initBug 

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/62bd337b335884334928d8a4/intent?page=0&imported=false&search=

### Additional information

history discussion: https://github.com/framely/community/issues/479#

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
Checked, 目前在 init mv slot 之后，会输出 mv prompt，最后 mv slot 的值 = init + end-user input。

详见：[Test Case - mv slot: num_2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea23001260dfedf34160ba/test_case)

![image](https://user-images.githubusercontent.com/95261974/182993046-253b8af0-0f11-4d4e-a385-a05bf607c48a.png)
