### ISSUE TITLE
[Bug]: Page loading is long, and directly switch struct and en will lose replies

### ISSUE THREAD

**Issue by yigexu** [framely/community#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

1. 选择 struct 的 response，能 load 出 replies
2. 在 response 页面切换到 en，看不到 replies
3. 从 tab bar 重新进入 response，能 load 出 replies

https://user-images.githubusercontent.com/6505755/177280309-acc64f57-21b0-481f-8df7-c485fb4e6bc6.mov

### Expected Behavior

希望 #2 可以看到 replies

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantL214

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d0ff5c77cdfc255d0d/intent/61d52d9e31c6ed847d5940f1/response/62020200d0fb8a89a4dbdb5a

### Additional information

这个问题不一定每次都能复现，但是我碰到不止一次了

**Comment by jfang137** [comment]
@Zeng666666 @hisunnymay 这个bug我复现不了，你们如果复现的话告诉我一下

**Comment by xiaoyunwu** [comment]
close it for now.
