### ISSUE TITLE
[Bug]: can not add same type slot twice

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

现在相同的 type 的 slot 没有办法加第二个，比如当 slot 列表中存在 type 是 Movie 的 slot：

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/37056884/177697345-13f35194-2f22-48a6-b09b-0b96d17c4af4.png">

如果之前没有修改过 slot name，之后就没有办法再添加新的相同 type 的 slot 了，会提示重名的报错

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/37056884/177697266-70ba2293-4394-4e8e-8809-4b9185b50182.png">

现在只能先将过去的名称改一个，然后添加新的 slot 并命名，然后再把旧的 slot 名称改回去（因为不想改其他 condition 和 function 的定义，怕有疏漏）

### Expected Behavior

预期，slot 的自动命名可以是递增的，如 movie、movie1、movie2。当添加新的相同 type 的 slot 时，如果已存在 movie，新的就变成 movie1。

### Use Case

/

### Steps To Reproduce

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/62b2d8c21d48e451a29be156/intent/62b2d9921d48e451a29be1b0

在 slot 中添加 Movie

### Label of org.project

test001.BuyTicket

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/62b2d8c21d48e451a29be156/intent/62b2d9921d48e451a29be1b0

**Comment by yigexu** [comment]
@Zeng666666 我估计是 Movie type 会默认创建一个 slot 叫 movie，然后你之前已经有一个 slot 叫 movie 了；
可以考虑创建的时候还是加个自增的后缀，让新创建的叫 moive1, movie2...

**Comment by Zeng666666** [comment]
@yigexu 是的呢

**Comment by Zeng666666** [comment]
checked
