### ISSUE TITLE
[Bug]: Displaying an incorrect Deploy Status 

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

在 Chatbot 点击 deploy，提示 _Successfully Deployed!_ 后，Deploy Status 由 Null 变为 Failure，需要刷新页面或者再点击一次 Deploy后，Deploy Status 才会显示：Success

![image](https://user-images.githubusercontent.com/95261974/177725944-00a59bc6-035b-468c-bbd6-caf710a59b53.png)

### Expected Behavior

提示 _Successfully Deployed!_ 后，Deploy Status 应该显示：Success

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62c68ff9dafbca109e5a048b/intent?page=0&imported=false&search=

**Comment by jfang137** [comment]
这个是deploy动作接口完成后拉取的deploy info接口没有立刻得到success的状态，可能是 @HuiCheng 那边状态的刷新是有延迟的

**Comment by hisunnymay** [comment]
> 这个是deploy动作接口完成后拉取的deploy info接口没有立刻得到success的状态，可能是 @HuiCheng 那边状态的刷新是有延迟的，辉哥也许可以先看下

@jfang137 好的，谢谢～ 

补充一下操作视频：

https://user-images.githubusercontent.com/95261974/177733605-460a9c7d-71e2-49f4-ad1e-cb14a288da12.mp4

**Comment by Zeng666666** [comment]
这个先 close 了，新的交互有问题再报新的 issue 吧
