### ISSUE TITLE
Improvement: VC trigger

### ISSUE THREAD

**Issue by yigexu** [framely/community#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Background

需求层面，VC 支持过两种触发时机：

1. 作为限制条件的槽位 **全部** 填满时

2. 作为限制条件的槽位 **任意** 被填上时

   

目前 runtime 的实现是 <1>，且作为限制条件的槽位是通过 function parameter来判断的。
也就是说，目前 VC 是在 function parameter 涉及到的槽位全部被填满时触发。

但需求一直要求能支持 <2>。

# Proposal

1. platform： 为 function signature 的 input parameter 增加 nullable 选择
2. runtime：当 VC function NOT nullable 的 parameter 全部被填满时触发
3. builder：将 parameter 声明为 nullable 后，则应该负责在 function handle parameter IS NULL 的情况

# More

1. 现在 platform 能支持 <2> 吗？

   可以，但是需要 builder 定义 2^n-1 个function；proposal 只需要 builder 定义 1 个 function。

2. Proposal 怎么支持 <2> 呢？
   > Concrete case 见 Chang's reservation design `case4`
   > https://naturali-io.feishu.cn/docs/doccnTvDKN8nTG40sfR0avYC3Gb

   抽象问题为：VC function 是 f(a, b, c) ，builder 希望 a，b，c 任意一个被填槽后就触发。

   配置为：function parameter a，b，c  全是 nullable

   SQL 为：

   ``` SQL
   select ... from ...
   where when a is null then colA = a else 1 = 1 end
   and when b is null then colB = b else 1 = 1 end
   and when c is null then colC = c else 1 = 1 end
   ```

3. 需求一直是需要支持 <2>，为什么现在 runtime 支持的是 <1>？

   我大概回忆了一下，GAP 可能是这么来的：

   - runtime 支持了触发方式 <2>，大致是分析 SQL 内容，移除空槽造成的限制。Note 移除限制后，<1> 和 <2> 问题等价。
   - 上线 PSQL，移除空槽限制的负责从 runtime 到转移到 PSQL，runtime 改为根据 function param去分析是否触发。GAP 产生。
   - 最后移除空槽限制的负责从 PSQL 转移回 builder。(和这个需求无关)

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
https://naturali-io.feishu.cn/docs/doccnf2VqJs5XXSbyVGlBw10l7d

**Comment by xiaoyunwu** [comment]
作为限制条件的槽位 任意 被填上时 is a bit too much. Check the document above for a more realistic setting.

**Comment by yigexu** [comment]
“任意”，因为上一版 VC function 还在定义 frame 里面，parameter 也不是现在则辉哥样子。
现在的 proposal 是：“当 VC function NOT nullable 的 parameter 全部被填满时触发”

**Comment by xiaoyunwu** [comment]
当 VC function NOT nullable 的 parameter 全部被填满时触发 what does it mean?

**Comment by yigexu** [comment]
所有在 function signature 中没有声明 nullable 参数，actual value 都被填上，然后 VC function 触发。

**Comment by xiaoyunwu** [comment]
Let's try to support <2>. But there are couple questions we need to figure out. 
1. During declaration, do we allow forma parameter to be nullable? (do we have this?)
2. Service provider takes care of nullable formal parameter in the implementation. 
3. Builder use !! to specify the actual parameter for non null formal parameter.
The rest should more or less follow the discussion of the feishu doc.

**Comment by xiaoyunwu** [comment]
I think we should ask builder to specify the nullability of the formal parameter. @Zeng666666 @yigexu what do you guys think?

**Comment by yigexu** [comment]
我希望：“platform： 为 function signature 的 input parameter 增加 nullable 选择”。因为我们已经对 function return 支持了 nullable，它们在设计上是类似的。

“Builder use !! to specify the actual parameter for non null formal parameter.” ==> code expression 可以这么要求，assisted mode 需要前端处理一下

**Comment by xiaoyunwu** [comment]
@Zeng666666 can you add nullable or not on the function signature?

**Comment by Zeng666666** [comment]
![image](https://user-images.githubusercontent.com/37056884/157160486-61c219fb-e455-4d91-9f7c-f65c2c684296.png)

![image](https://user-images.githubusercontent.com/37056884/157160622-2f29ac3d-dc43-41b5-ad18-dd467bf11cdd.png)

**Comment by Zeng666666** [comment]
@yigexu 这个好了吗？
