### ISSUE TITLE
Improvement: VC function return [runtime final version]

### ISSUE THREAD

**Issue by yigexu** [framely/community#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Background is #45 

1. runtime 对 VC function return 的预期从 MV / list 改为 boolean。

### Motivation

/

### Describe alternatives you've considered

/

**Comment by yigexu** [comment]
@XiaoboYuan 
UIUX 的设计随后需要调整，如果 runtime 和 platform 在这里有依赖关系可以推迟实现。
let me know after you finish this.

**Comment by Zeng666666** [comment]
这个需要单发一个原因是什么呢？这个不是和 #45 是一样的吗？这样其他 builder 就看不到 context 了。

**Comment by yigexu** [comment]
这个是requirement，那个是 discussion。以后 discussion 我会放在飞书。

**Comment by Zeng666666** [comment]
哦，但我理解的可能和你想的不太一样。

如果这个是 builder 提出的 feature request，那么讨论过程和最终结果应该都只在这里显示。

这样，对方可以追踪，其他 builder 也可以追踪。就像论坛跟帖一样。

假如我们每天都有 100 条新增条目，如果每条都引申出多条分支，那么这个数量是我们没法控制和管理的。builder 也无法逐个追踪。

**Comment by xiaoyunwu** [comment]
如果这个是 builder 提出的 feature request, I think it is possible that there are
document before this.
but we do want to use the same issue to track the discussion.

**Comment by xiaoyunwu** [comment]
Also, we can link there issues. This issue is based on https://github.com/framely/community/issues/45

**Comment by Zeng666666** [comment]
NO！ 这个任务的意义就是这样，我们需要在一个 issue 上保持追踪。否则 builder 不知道我们的 versionx 有什么区别，尤其是每一个 version 都有不同的更新时，builder 无法 follow 所有 issue 去看我们的变化，想想 service 1-7。没有 context 很难理解是什么。

一样的 issue 会被 bot 自动关闭的。否则每个 builder 都可以不遵从规则做事情。

![image](https://user-images.githubusercontent.com/37056884/156699099-f6d3e69c-5ec1-47fc-84e1-a904ba31d564.png)

**Comment by Zeng666666** [comment]
目前的情况是，这是同一个主题，同一个主题就要在同一个 issue 上完成。不是同一个主题，引发的多个不同的 feature。如果是一个主题引发的不同 feature，最终也是需要我们给 builder 交待：Framely 是怎么处理的，用哪些方法解决了这个问题，他可以去看哪几个 issue，给他带来了哪些影响，需要多久可以完成，怎样可以不 block 他等等。

**Comment by yigexu** [comment]
我感觉我们还在摸索 & 对齐流程。
1. discussion 放回飞书
2. github 上给 builder 看的应该是 functionality 的层面，我们并不需要暴露 design 过程和每个 product change。(granularity 可以再讨论)
3. 这个讨论我们也可以回到飞书去，这里不是很合适。
