### ISSUE TITLE
[Feature Request]: Rename label of code block in implementation field

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Provider - Service - Implementation 中的Code block label 根据 Provider 的类型 或者 Implementation 的方式，有不同的显示：
- Provider Dependent
   - Postgrest：没有 label
   - RESTful：label 显示为 **Body**
   - Google Sheets：label 显示为 **Query**
- Kotlin：没有 label

> 可参考：之前 PRD 文档中的 Implementation 的结构

- RESTful (Webhook)

![img_v2_064aa84f-be66-4f3c-b4b0-880017cc8b7g](https://user-images.githubusercontent.com/95261974/179160721-5ffa05da-d5ee-4ac9-99e3-a4157c5073ec.png)

- Postgrest 

![img_v2_5d03fd4b-0411-4be7-bb98-07b9541ca43g](https://user-images.githubusercontent.com/95261974/179161059-1d8014f7-3778-48fe-b648-e0e6bda7c0f5.png)

### Motivation

目前 Code block 的 label 都显示为 **Query**，但在除了 Google Sheets - Provider Dependent 情况下， Code block 中填写的内容不应该用  **Query** 来概括

![image](https://user-images.githubusercontent.com/95261974/179165719-346c4a66-3f9a-4c9a-ab60-f614e09fa2a8.png)

### Describe alternatives you've considered

如果差异化的 label 实现起来比较麻烦的话，也可以考虑将 **Query** 都修改为 **Body**，不过 UI 界面可能不是很美观

### Additional context

/

**Comment by hisunnymay** [comment]
@jfang137 Google Sheets 和 Restful 中，Implemention 为 Koltin 的时候能隐藏 **Query** 和 **Body** 吗？

![image](https://user-images.githubusercontent.com/95261974/179887410-351de102-5da3-4963-ad08-40cdf29098cb.png)

**Comment by jfang137** [comment]
隐藏了，稍后看看

**Comment by hisunnymay** [comment]
@jfang137 重新试了一下，可以啦

checked，label 和 Summary 中的描述一致
