### ISSUE TITLE
[Bug]: Errors in function testing

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

在 Provider：[reservationProvider_0602](https://build.framely.ai/org/615fa4282cc41400665536e3/agent/629f181edaf956ab2ad0d863/version) 使用 Function Testing 会出现以下两种情况

1. 报错：
```
"Could not find the reservationProvider_0602.getInfo() function or the reservationProvider_0602.getInfo function with a single unnamed json or jsonb parameter in the schema cache"
```
2. 没有返回值: `[]`

![页面 8](https://user-images.githubusercontent.com/95261974/179207835-833e63e4-5d85-45fb-987a-dfbf765c34c6.png)

### 补充
1. 在 pgAdmin 中直接调用 Function：getInfo() ，北美和大陆都是有返回值的
2. 这个Provider 部署了北美和大陆两个Region，会是这个导致的问题吗？

![image](https://user-images.githubusercontent.com/95261974/179208169-b1147546-f01f-4355-9783-48d530d76fa3.png)

### Expected Behavior

应该有返回值

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/629f181edaf956ab2ad0d863/provider_connection

**Comment by hisunnymay** [comment]
@xiaoyunwu 我们允许 builder 将Provider 部署到多个区域吗？如果允许，那么 Function Testing 用的是哪个区域呢？需要builder 选择吗？

**Comment by hisunnymay** [comment]
@xiaoyunwu 除此之外，由于Function Implementation 有 Kotlin 的方式了，那 Function Testing 是不是也需要支持测试 Provider 中 定义的 Kotlin Function 呢？

目前 Function Testing 中可以选择的 Function 包含了 Kotlin Function，如果我们不支持测试 Kotlin Function 的话，感觉应该不支持选择 Kotlin Function

**Comment by hisunnymay** [comment]
> @hisunnymay can you ask Yi to make kotlin function not testable?

@jfang137 哈喽，可以麻烦设置在 Function Testing 中不能选择 Kotlin Function 吗？

![image](https://user-images.githubusercontent.com/95261974/184782680-32d20427-ff2e-43ca-91a5-b312913b8515.png)

**Comment by xiaoyunwu** [comment]
just filter this out?

**Comment by hisunnymay** [comment]
checked, 现在可以 work 了

![image](https://user-images.githubusercontent.com/95261974/185044559-5ada0c66-79bb-4b5c-8249-4a9e066735af.png)
