### ISSUE TITLE
[Bug]: Failed to create a frame type for input type in Postgres function

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

- 当 Postgres function 的 input parameter 是 frame 类型的时候，在 Provider 中点击 Deploy 会报错：

```
CREATE OR REPLACE FUNCTION "t_InputFrameType_delete"."_testFunction" ("param" "t_InputFrameType_delete"."o18810675122.t_service_0715.TestFunction1") RETURNS Table ("num" bigint) 
SET SEARCH_PATH = "t_InputFrameType_delete"
AS $BODY$
BEGIN
	RETURN QUERY
    SELECT "TestFrame".num FROM "TestFrame";
END
$BODY$
LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION "t_InputFrameType_delete"."testFunction" ("param" "t_InputFrameType_delete"."o18810675122.t_service_0715.TestFunction1") RETURNS TABLE (data json) 
SET SEARCH_PATH = "t_InputFrameType_delete"
AS $BODY$
    SELECT row_to_json(data) from (select * from "t_InputFrameType_delete"."_testFunction"("param")) as data;
$BODY$
LANGUAGE SQL;
```

```
 err:pq: type t_InputFrameType_delete.o18810675122.t_service_0715.TestFunction1 does not exist
```

- Input Parameter type 是 `o18810675122.t_service_0715.TestFunction1`, retunr type 是 `o18810675122.t_service_0715.TestFunction2`，在 Postgres 中只生成了 `o18810675122.t_service_0715.TestFunction2`

![image](https://user-images.githubusercontent.com/95261974/179440470-ccb36010-376b-4736-90f7-25b68b57f747.png)

### Expected Behavior

不确定我们是否支持在 Postgres 中传入 Frame 类型的参数
- 如果支持，那在上述配置下， 点击 Deploy 应该在 Postgres 中生成对应的 Input Type
- 如果不支持，感觉我们应该在前端限制 不能选择 Frame 类型作为 Input type

### Use Case

如果支持在 Postgres 中传入 Frame 类型的参数，那么在 Cancel Reservation中，Builder就可以直接穿入 Frame：reservationInfo了

- 传入 Entity 的表达式
```
reservation_0602.cancelReservation(reservationInfo!!.date!!, reservationInfo!!.time!!, reservationInfo!!.tableType!!, reservationInfo!!.id!!) != null
```

- 传入 Frame 的表达式
```
reservation_0602.cancelReservation(reservationInfo!!) != null
```

### Steps To Reproduce

在 Provider：[t_InputFrameType_delete](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62d12ec6593b60d46cdaa718/service_schema) 点击 Deploy

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62d12ec6593b60d46cdaa718/service_schema

**Comment by hisunnymay** [comment]
@jfang137 哈喽，能麻烦看一下这个issue吗？目前 Postgres Function 中的 Output type 能在 Postgres 里面生成对应的 type，但是 Input type 不能生成对应的 type。 @HuiCheng 不确定是不是 Input type 的参数没传过去..

**Comment by jfang137** [comment]
我记得是composite type是要求只根据return type生成的

**Comment by xiaoyunwu** [comment]
should it be if a type is needed by either input or output by one function,
and it is not mapped to table, it should be composite type.

**Comment by jfang137** [comment]
所以我们是支持frame type的传参了。好的，我稍后加上

**Comment by hisunnymay** [comment]
Checked, 现在 Input 和 Output 中 的 frame 都能在 Postgres 中生成 对应的 Composite type 了。目前还无法测试传入的 Frame type 的参数是否能在 postgres 中使用，等待测试。
