### ISSUE TITLE
[Bug]: grpc error when commit template chatbot

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

新建一个chatbot：[error_0718](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62d51daa593b60d46cdb213e/intent) ，在 Struct 点击 Commit 后， 切换到 EN，点击 commit，报错：
```
grpc error code:2, message:
```

### Expected Behavior

commit template chatbot 不应该有报错

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62d51daa593b60d46cdb213e/intent?page=0&imported=false&search=

**Comment by XiaoboYuan** [comment]
是不是已经好了 我的branch是可以commit的 最近改了不少东西可以再试一下
@hisunnymay

**Comment by hisunnymay** [comment]
@XiaoboYuan 试了一下，没有报错啦，谢谢
