### ISSUE TITLE
Make prompt saved after lose focus

### ISSUE THREAD

**Issue by yigexu** [framely/community#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/6505755/156718196-aad863b7-f7a5-4230-a743-5af3b3907fb5.mov

### Expected Behavior

prompt 输入的内容失焦后可以被保存

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant

**Comment by Zeng666666** [comment]
这个是已经修了吗？我这里没有复现 🤦‍♂️
