### ISSUE TITLE
[Bug]: On imported page, change from struct to lang

### ISSUE THREAD

**Issue by yigexu** [framely/community#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

1. 在 struct 下选择 imported 页面，[example](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/62c51c3edcc575bafb6eb88e/library)
2. 切换 struct 到 en
3. 能看到尽管 en 的 sidebar 中没有 imported，但是右侧页面还是停留在 imported
<img width="1678" alt="Screen Shot 2022-07-22 at 3 37 23 PM" src="https://user-images.githubusercontent.com/6505755/180388710-cda343b4-7d71-42eb-9903-14e751287634.png">

### Expected Behavior

如果没有统一的重定向的页面，sidebar 选择 intents，右侧页面展示 intents 列表

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

比如 https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/62c51c3edcc575bafb6eb88e/library

**Comment by Zeng666666** [comment]
checked
