### ISSUE TITLE
[Bug]: Multi-Valued Confirmation (confirm by slot entry) is missing

### ISSUE THREAD

**Issue by yigexu** [framely/community#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

<img width="485" alt="Screen Shot 2022-07-25 at 9 53 43 AM" src="https://user-images.githubusercontent.com/6505755/180678246-10f1a0e3-f621-40a4-8b0e-9a925c55507d.png">

### Expected Behavior

根据配置
<img width="1360" alt="Screen Shot 2022-07-25 at 9 57 28 AM" src="https://user-images.githubusercontent.com/6505755/180678524-450e45cf-98f4-4ab3-ac1c-ca3eb12eabe1.png">

说 first 之后，bot 会先回答 Adding 1 squashed cucumber to cart.
这句话之前是有的，不知道从什么时候没了。

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214_region

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/62c51c3edcc575bafb6eb88e/intent/61d52d9e31c6ed847d5940f1/slot/62427babb883426466b1983f

### Test Case
0725

_No response_

**Comment by XiaoboYuan** [comment]
dup https://github.com/framely/community/issues/610
