### ISSUE TITLE
[Bug]: slot prompt under lang should be editable

### ISSUE THREAD

**Issue by yigexu** [framely/community#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/6505755/156725332-d509df45-256d-4393-90fe-1498284b5e09.mov

### Expected Behavior

slot prompt under lang should be editable

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

irrelevant

### Framely Link

irrelevant, but: https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/6221c88446fb4c191d4dbe7e/intent/6221c88946fb4c191d4dbe80/slot/6221c89746fb4c191d4dbe86

**Comment by Zeng666666** [comment]
prompts 和 multi-valued prompts 都不能编辑了，鼠标展示“禁止编辑”状态；测试 alias 没有发现类似问题。

好像是在某一时刻发生的。之前创建的，如果不删除所有 prompts，只在过去的基础上添加，是没有问题的；如果把 prompts 删除后，重新添加，也就不能编辑了。

![image](https://user-images.githubusercontent.com/37056884/156728442-84917ce8-2977-4ed3-81e0-ded57ac8547f.png)

**Comment by Zeng666666** [comment]
@yigexu 我这里可以了，你那里好了吗？
