### ISSUE TITLE
[Bug]: Provider related issues

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

#### 对于 Postgrest Provider
1. 在没有开启 Storage Enabled  的情况下，会显示 Provider annotation
2. Provider annotation 包含了 Prompts

- Example：[delete_postgresetProvider_0728](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e258dad5bdfadb198091c2/frame/62e258ded5bdfadb198091c5/slot/62e258e1d5bdfadb198091c7)

![image](https://user-images.githubusercontent.com/95261974/181480061-bb29df20-1c16-4a50-a0df-291e78796337.png)

#### 对于 Google Sheets Provider 和 RESTful Provider 
1. 有 Storage Enabled 的开关

- Example：[delete_Restful_0728](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e25d16d5bdfadb19809476/frame/62e25d1bd5bdfadb19809479) & [delete_sheetProvider_0728](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e1f7c2352576a555c78918/frame/62e25b14d5bdfadb19809470)

![image](https://user-images.githubusercontent.com/95261974/181479963-ad24e699-b51d-4f85-b496-fc927e744d66.png)

#### 对于 Postgrest Provider 
1. 在没有开启 Storage Enabled 的情况下，不会显示 Provider annotation
2. Provider annotation 不包含 Prompts

#### 对于 Google Sheets Provider 和 RESTful Provider 
1. 没有 Storage Enabled 的开关

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e258dad5bdfadb198091c2/frame/62e258ded5bdfadb198091c5/slot/62e258e1d5bdfadb198091c7

**Comment by jfang137** [comment]
@hisunnymay 你说的provider annotation是什么？annotation tab? 没开启storage annotation的情况下，作为普通的frame,也有annotation吧？

**Comment by hisunnymay** [comment]
@jfang137 provider annotation 是: SQL Data Type, Default Value, Allow Null, Unique, URL, Input Type。 普通的frame 的 annotation 是：init, value rec, value check , prompt等

**Comment by hisunnymay** [comment]
@jfang137 试了一下 Postgrest Provider 没有问题了。另外两个 Provider 还是有 Storage Enabled 的开关，可见：[delete_sheetProvider_0729](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e34682d5bdfadb19810b2f/frame/62e346f4d5bdfadb19810b32)

**Comment by hisunnymay** [comment]
Checked, all fixed
