### ISSUE TITLE
[Bug]: value check triggers after response

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在intent - confirmation得到肯定回答之后，trigger了Value Check `VC` ，然后当intent - response输出之后，`VC` 又被trigger了

* 这样会导致：`VC` clear slot: date, bot输出slot: date的prompt和value recommendation。
* user的体验为：在提交了预定信息后，再次被询问预定的日期。而实际上是不需要再被询问的。
* `VC` failed的原因：当user对confirmtion给出肯定回答之后，此时满足user筛选条件的桌子的quantity为1， `VC` passed, 在提交了预定信息(即：trigger response)之后，quantity变为0，导致 `VC` failed

![image](https://user-images.githubusercontent.com/95261974/156774345-de47e953-6c27-437d-abb0-ad0c07c33b7c.png)

### Expected Behavior

当intent - response输出之后，不会再trigger该intent的`VC` ，除非该intent被重新trigger

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/621c99857cb494e0d5fa3268/test_case

### Test Case

[reservationApp](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/621c99857cb494e0d5fa3268/test_case) - value check after response

**Comment by Zeng666666** [comment]
VC clear slot: date 是指？好像没有定义 Recovering ？

**Comment by hisunnymay** [comment]
因为VC: checkDateAndTime()failed, 根据现在VC默认的clear strategy, runtime会clear slot: date.

FYI, 我的VC里定义了7个function (定义在intent - native funtiom中)
1. checkDate(date)
2. checkTime(time)
3. checkTableType(tableType)
4. checkDateAndTime(date, time)
....

**Comment by yigexu** [comment]
@hisunnymay 我复现不了你这个问题
<img width="454" alt="Screen Shot 2022-03-07 at 9 21 53 AM" src="https://user-images.githubusercontent.com/6505755/156952317-15f17f4e-4b14-4bf6-9c04-02b008f4ec17.png">
<img width="406" alt="Screen Shot 2022-03-07 at 9 22 00 AM" src="https://user-images.githubusercontent.com/6505755/156952323-f856bbca-269b-4ee3-a2d5-022a563b31a6.png">

**Comment by hisunnymay** [comment]
因为只支持预定VR里面的date，我当时测试的时候2022-3-4是可以预定的，但是现在最早只能预定2022-3-9的了，你可以试试[test - 0307](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/621c99857cb494e0d5fa3268/test_case)

**Comment by yigexu** [comment]
@XiaoboYuan 
先看一个前置问题：
输入 test,2022-03-09,9:00,small，yes。
会稳定发生 concurrent 的报错
<img width="1622" alt="Screen Shot 2022-03-07 at 9 37 13 AM" src="https://user-images.githubusercontent.com/6505755/156953402-1fe1dcc3-cd79-4191-bbdb-c50ec93efd50.png">

**Comment by yigexu** [comment]
@XiaoboYuan 
1. 我对 @hisunnymay 的描述没什么问题，预期是对 frame 的交互完成后，进入 response 之后不应该再出现 VC。
2. 为了 reduce slotupdate 的影响，我用的是 test, 2022-03-09, 9:00, small，yes，这一组测试

**Comment by hisunnymay** [comment]
@XiaoboYuan 得用9:00 am，不然会转换为21:00，21:00点所在时间段的剩余桌子数目是>1的，也就是说当预定出去一个桌子时，剩余餐桌数!=0，不会导致VCfail

**Comment by hisunnymay** [comment]
@XiaoboYuan 如果value check做完了的话，能看一下这个issue吗？目前value check还是会在response和confimation之后再触发

1. 在response之后触发
![image](https://user-images.githubusercontent.com/95261974/158936976-76cbe2d2-e4b3-466a-a47f-0a84192f026f.png)

2. 在confirmation之后触发
![image](https://user-images.githubusercontent.com/95261974/158937154-fd54b640-fe88-4509-9954-3de9bb193ab0.png)

相关value check的问题： [Value check function triggered more than once #121](https://github.com/framely/community/issues/121)

**Comment by xiaoyunwu** [comment]
@XiaoboYuan what is the reason for this, do you know?

**Comment by hisunnymay** [comment]
@XiaoboYuan 刚才在[reservationApp_2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/622eb3585dc1a2ba24cf43c3/test_case)添加了slot - confirmation，发现slot - confirmation也会在response输出之后trigger，不知道是不是同一个原因导致的

1. 在response后输出slot - confirmation

![image](https://user-images.githubusercontent.com/95261974/159427725-a4d4ec63-3063-46f6-a151-83bfd06271b7.png)


2. 回应“yes”（或者"no"），都会报错：Internal Server Error

![image](https://user-images.githubusercontent.com/95261974/159427251-ab0b7a85-9c98-4b2a-a523-f1fd15f9755c.png)

3. 报错的log截图
![image](https://user-images.githubusercontent.com/95261974/159427949-d0affd42-ff8e-4f44-b629-de4bf16252e3.png)

**Comment by XiaoboYuan** [comment]
@hisunnymay 
修复了response之后slot confirmation的bug

**Comment by hisunnymay** [comment]
checked.
