### ISSUE TITLE
[Bug]: login after the a long while

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

after a while, when I try to log into framely.naturali.io, I get the following error message:
Error: request parameter error, please check the parameters and if there is access token
And even through it appears that I logged in, there is nothing, no org, no chatbots. 

### Expected Behavior

 we should direct user back to login page, if there are login issues. 

### Use Case

n/a

### Steps To Reproduce

just try to login after a long while.

### Label of org.project

n/a

### Framely Link

n/a

**Comment by Zeng666666** [comment]
等有 build.framely.ai 之后再试
