### ISSUE TITLE
[Bug]: Error: ask strategy is not supported yet

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

选择 Ask Strategy 为 Recover Only 后，commit 报错：

_unknown status code:18446744073709551517
error message:server error in generator phase : java.lang.IllegalStateException: **ask strategy is not supported yet**_

### Use Case
期望在 [Order Implementation for #1#2](https://naturali-io.feishu.cn/docx/doxcn9u28wT4k2IDP6oPRO59TNg) 中将Slot：Cart[] 设置为  Recover Only， 因为 Cart 的值不需要直接找 end-user 填写

P.S
目前可以通过将 Cart 设置为 Always Ask 来绕开当前的问题，但从 Cart 的用法的角度，它的 strategy 应该是 Recover Only

### Expected Behavior

根据 [[PRD] Prompt strategy 最新优化（22/06/21）](https://naturali-io.feishu.cn/docx/doxcnuSgM0BZloyhRPebLqQxYsh), 平台上应该支持了 Recover Only 类型的 Prompt strategy

### Steps To Reproduce

修改 Slot：[num_2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e8ddb41e8e99dc640c32e9/intent/62e8ddba1e8e99dc640c32ed/slot/62e8dded1e8e99dc640c32f7) 的 Ask Strategy 为 Recover Only，切换到 EN Agent 后，commit 就能看到报错

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e8ddb41e8e99dc640c32e9/frame?page=0&imported=false&search=

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
Checked, fixed. 现在选择 Recover Only, commit 不会报错
