### ISSUE TITLE
[Bug]: Different DM behavior in the frame implemented interface frame and the frame not implemented

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior
在 Chatbot：[demo_0802](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb01e8e99dc640c8795/intent) 中，有两个Frame，它们除了 Implemented 的部分和Frame Name，其他都相同：
1. [Dish](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/frame/62e913e81e8e99dc640c9bd7) [Implemented nothing]
2. [IMDish](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/frame/62e916e71e8e99dc640ca991) [Implemented [IDish](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/frame/62e913c11e8e99dc640c9bcd)]

![image](https://user-images.githubusercontent.com/95261974/182508102-bc6d3247-0f30-4a92-bf85-a0e16394bf41.png)

分别用这个两个 Frame 创建 2 个结构相同的Intent：[FoodOrdering](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/intent/62e913fc1e8e99dc640c9bd9) 和 [FoodOrdering2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/intent/62e917291e8e99dc640ca9fb)，在 Try it now 中测试，[对话](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/test_case)不同

![image](https://user-images.githubusercontent.com/95261974/182508308-2613ecf3-b8c6-4a36-8018-3468ddc42441.png)

### Expected Behavior

如果 Frame 的 Slot 定义是一样的话，感觉 DM 的表现应该是一样的？即：用  [IMDish](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/frame/62e916e71e8e99dc640ca991) 得到的对话体验和用 [Dish](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/frame/62e913e81e8e99dc640c9bd7) 是一样的

### Use Case

场景是：[订餐服务](https://naturali-io.feishu.cn/docx/doxcnszKMDBzREZNR9pQRJ6IYFh)

希望用 Slot：Dish[] (Implemented IDish)来保存 user 选择的菜品，用 Slot：Cart[] (Implemented IDish) 来保存对 user 选择的相同菜品进行合并后的菜品

比如：Dish 为 [{菜品A}, {菜品A}, {菜品B}], Cart 为 [{菜品A, 2}, {菜品B, 1}]

P.S.
目前可以通过在 Cart 添加和 Dish 相同的 Local slots (不使用interface frame： IDish) 来绕开当前的问题，但感觉从设计上来说 implementing interface frame：IDish 会让 component 的结构更清晰

### Steps To Reproduce

Run [Test Cases](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/test_case)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/test_case

**Comment by XiaoboYuan** [comment]
第二个如果你把id填上后面会是什么情况

**Comment by hisunnymay** [comment]
@XiaoboYuan 会询问剩余 2 个slots：name 和 price 的值，这两个值都填上之后会询问slot：id 的值

![image](https://user-images.githubusercontent.com/95261974/182535472-2e10d0f0-f5f8-49e4-9446-1cbce7ccd306.png)

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
Checked, fixed. 现在 DM 的表现是一样的，对话保存在[ FoodOrdering2 - order2 - 0804 ](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e90eb21e8e99dc640c8797/test_case)
