### ISSUE TITLE
[Bug]: Failed to trigger the 2nd value check condition

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

根据 [[Feature Request]: support multiple Value Check and Initialization](https://github.com/framely/community/issues/580#top)，Value Check(VC) 支持添加多个 condition。在 Slot：[num_2](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e9e0df65d5392be84f7916/intent/62e9e10a65d5392be84f791a/slot/62e9e11865d5392be84f7920) 中添加了 2 个 VC condition, 目前第一个 conditon 能触发，第二个不能触发。

![image](https://user-images.githubusercontent.com/95261974/182544735-595ce96e-e321-44da-a754-b3f3a958338c.png)

### Expected Behavior

在 Value Check 的 condition 中，第一个为 false 的 condition，value check 能输出对应的 value check prompt 和 clear builder 定义的 target slot

即：在上述例子中，第二个 value check 应该触发，输出：_num_2 can't be 2_

### Use Case

目前没有定义多个 Value Check condition 的 use case

### Steps To Reproduce

Run [Test Case](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e9e0e065d5392be84f7918/test_case)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e9e0e065d5392be84f7918/test_case

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
@XiaoboYuan 在chatbot：[issue_MultipleVC](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e9e0df65d5392be84f7916/intent) 中 commit 报错，重新创建一个相同的 chatbot: [issue_MultipleVC_0808](https://framely.naturali.io/org/625e2f3cd31e3de801ef5a93/agent/62f0c39f70b8ad035ce6500e/intent) ，commit 有相同的报错


> e: /data/source_code/Test_issue_MultipleVC_0808_en_666286199349972992/Test_issue_MultipleVC_0808.kt: (278, 34): Expecting ')'
> e: /data/source_code/Test_issue_MultipleVC_0808_en_666286199349972992/Test_issue_MultipleVC_0808.kt: (282, 18): Property getter or setter expected
> e: /data/source_code/Test_issue_MultipleVC_0808_en_666286199349972992/Test_issue_MultipleVC_0808.kt: (273, 61): Type mismatch: inferred type is List<List<AtomAction>> but List<Pair<() -> Boolean, List<Action>>> was expected
> e: /data/source_code/Test_issue_MultipleVC_0808_en_666286199349972992/Test_issue_MultipleVC_0808.kt: (278, 17): Unresolved reference: Pair
>

**Comment by XiaoboYuan** [comment]
fixed @hisunnymay

**Comment by hisunnymay** [comment]
Checked, it's fixed. 现在能添加多个 value check condition，详见：[Test Cases](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62e9e0e065d5392be84f7918/test_case)
