### ISSUE TITLE
[Bug]: Failed to provide slots with the value given in Initialization

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前无法用 Initialization 中定义的值为 当前slot (both sv and mv) 和 其他 slot 赋值

![image](https://user-images.githubusercontent.com/95261974/182552118-73394dc9-3c8d-43dd-b15b-a29d6d4c1fca.png)

### Expected Behavior

支持用 Initialization 中定义的值为 当前slot (both sv and mv) 和 其他 slot 赋值

### Use Case

期望在 [Order Implementation for #1#2](https://naturali-io.feishu.cn/docx/doxcn9u28wT4k2IDP6oPRO59TNg) 中利用 Initialization 对 Cart 赋值

P.S.
目前可以通过用 Trasition 为 Cart 赋值来绕开当前问题，但考虑到 Trasition 是比较 low level 的 annotation 所以希望尽量能用 high level 的 annotation：Initialization 实现

### Steps To Reproduce

Run [Test Case](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea23001260dfedf34160ba/test_case)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea23001260dfedf34160ba/test_case

**Comment by XiaoboYuan** [comment]
![image](https://user-images.githubusercontent.com/4945408/182986740-4f9e7e46-5c01-4f0d-9bb5-25cbbd992d2a.png)

@jfang137 没有赋值新的sequences字段

**Comment by hisunnymay** [comment]
@XiaoboYuan 试了一下，init 当前 slot (both sv & mv)没有问题了，不过好像不能 init 别的 slot (比如：在 num_3 中定义 init num_4)

P.S. 
1. 目前平台支持 init 别的 slot 和 添加多个 init，详见：[[Feature Request]: support multiple Value Check and Initialization](https://github.com/framely/community/issues/580#)
2. 目前没有 init 别的 slot 的 use case

![image](https://user-images.githubusercontent.com/95261974/182992472-98dc596d-9e2d-4d29-9231-a1fd997748a5.png)

**Comment by hisunnymay** [comment]
Check, fixed. 支持用 Initialization 中定义的值为 当前slot (both sv and mv) 和 其他 slot 赋值详见 [Test Initialization - test - 0808](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea23001260dfedf34160ba/test_case)
