### ISSUE TITLE
[Bug]: Failed to trigger Multi-Valued Confirmation

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

在今天创建的 [issue_mvConfirmation_0803](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea06341260dfedf340d90e/intent) 中，为 Slot：[num[]](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea06341260dfedf340d90e/intent/62ea06401260dfedf340d910/slot/62ea06431260dfedf340d914) 配置 Multi-Valued Confirmation 的 condition 为 true, user 每次提供 num 的值后，不会输出 Multi-Valued Confirmation 中定义的 Implicit Confirmation

在以前创建的 [mvConfirmation_0623](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62b3d5f51d48e451a29c8f03/intent) 中，测试 Multi-Valued Confirmation 的 效果是：user 每次提供 num 的值后，在满足 condition 的情况下，会输出 Multi-Valued Confirmation 中定义的 Implicit Confirmation

![image](https://user-images.githubusercontent.com/95261974/182559046-43e38389-41ce-4b3f-9d6a-4b63e7b6936b.png)

### Expected Behavior

在 [issue_mvConfirmation_0803](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea06341260dfedf340d90e/intent) 中能输出 Multi-Valued Confirmation

### Use Case

场景是：[订餐服务](https://naturali-io.feishu.cn/docx/doxcnszKMDBzREZNR9pQRJ6IYFh) Case 1

在 Case 1 中，菜品是 slot：Dish[]，当 end-user 选择某个菜品后，利用 Multi-Valued Confirmation 告知 end-user:
> 已将 xx 菜加入购物车中

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea06341260dfedf340d90e/test_case

**Comment by XiaoboYuan** [comment]
@jfang137 
multivalue confirmation list是空的

**Comment by hisunnymay** [comment]
Checked, fixed. 现在能输出 Multi-Valued Confirmation 了，详见 [Test Case](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ea06341260dfedf340d90e/test_case)
