### ISSUE TITLE
[Feature Request]: remove undefined condition info “default to true”

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

现在的 condition 为 code expression，无论是什么都应该由 builder 自己定义，比如 builder 可以自己定义 true 这个条件，而不是平台生成或默认是什么。且大多数场景下（如 confirmation、transition、response），platform 的预期是 builder 需要定义有意义的内容，不支持空条件，尽管在有 UI 交互的时候有这个默认表现。

因此，需要去掉 “default to true” 这个提示，没有定义 condition 就应该只提示：Condition Undefined 。

### Motivation

/

### Describe alternatives you've considered

/

**Comment by jfang137** [comment]
https://github.com/framely/platform-frontend/pull/2071

**Comment by Zeng666666** [comment]
checked
