### ISSUE TITLE
[Feature Request]: Post-fill Action Annotation

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

为 condition transition 添加一个 shortcut：
PRD：https://naturali-io.feishu.cn/docx/doxcnxKZIrDZPmWGCLQ7rZTPmed

### Motivation

/

### Describe alternatives you've considered

/

**Comment by Zeng666666** [comment]
因为 frame level 的 post-fill 有一些表现目前还不太确定，和 @xiaoyunwu 讨论了一下，咱们先把 frame level 的 post-fill 隐藏一下 @jfang137 之后有需要的 use case 时再放出来。

**Comment by jfang137** [comment]
好的

**Comment by Zeng666666** [comment]
checked
