### ISSUE TITLE
[Bug]: when switching chatbot,  test session didn't change

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

如果 try it now 进行过测试，当切换 chatbot 时，在新的 chatbot 中点开 try it now 依然是上一个 chatbot 的测试的内容。

### Expected Behavior

切换了 chatbot，try it now 的 test session 也应该重新开始

### Use Case

/

### Steps To Reproduce

1. 在 chatbot [PingPongUS](https://build.framely.ai/org/6284c6f1d3c0469ed06d423c/agent/62f4ba52b27d10fbb48b9450/intent?page=0&imported=false&search=) ，进行测试，输入 ping
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/37056884/185831760-6a482c04-1454-4d89-9c6d-a051cd0ba1d2.png">

2. 切换 chatbot 到 [orderApp_copy123](https://build.framely.ai/org/621d809561f0057d035f6437/agent/63001e9d7e621a4f49d44197/intent)，打开 try it now 依然是上一个 chatbot 的测试内容，但他们在不同的 org 内：
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/37056884/185831959-f9774150-a118-4f5f-9e75-2397dad59d56.png">

### Label of org.project

/

### Framely Link

/

**Comment by Zeng666666** [comment]
@jfang137 如果在 chatbot 测试后，再 clone 它。然后在 clone 版本 chatbot_copy 的 try it now 还会带着上一个 chatbot 的记录：

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/37056884/186105132-f012583a-d5ea-45b3-ab9e-d46e170c10aa.png">

复现方法：
1. 先在 lang-agent try it now 测试；
2. 切换到 struct-agent 进行 clone；
3. clone 后的 agent，切换至 lang-agent；
4. 打开 try it now，就会显示之前的测试记录。
 
可以试试 clone 这里面的 chatbot：https://build.framely.ai/org/6284c6f1d3c0469ed06d423c/chatbot_agent

**Comment by jfang137** [comment]
> /org/6284c6f1d3c0469ed06d423c/chatbot_agent

稍后再试试看

**Comment by Zeng666666** [comment]
好的

**Comment by Zeng666666** [comment]
试过了，现在可以了
