### ISSUE TITLE
[Bug]: Backoffice related issues

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

1. ~~No required tag when editing a row~~

![image](https://user-images.githubusercontent.com/95261974/188785691-48d0c46b-501b-4951-8612-4edf356d21f0.png)

2. ~~No content in the column whose type is boolean~~ 

![image](https://user-images.githubusercontent.com/95261974/188785831-56c62eb7-490c-4a10-ad66-abb02aaacf3a.png)

3. ~~Dropdown is not supported yet (Reference: https://naturali-io.feishu.cn/docs/doccnFeSgdp9IYqHePpOWVa5Hmd)~~

4. Can't edit column whose type is `localTime`

5. ~~Content is not displayed when editing a row sometimes~~

![image](https://user-images.githubusercontent.com/95261974/188786529-d76c44b5-2553-438a-bd0b-0b9f58b62384.png)

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

**Comment by hisunnymay** [comment]
Updated, only 1 and 4 left

**Comment by hisunnymay** [comment]
Updated issues left - 0921

1.  Can't edit column whose type is localTime
2. Can't set text value to null

![origin_img_v2_1ab48bf3-3ad3-4e98-ab3d-68512dd63cbg](https://user-images.githubusercontent.com/95261974/191145981-a99be4e4-5823-40f8-9b3b-ff345032cfb0.jpg)

3. Add `*` if the value is required in the "Create" filed

![image](https://user-images.githubusercontent.com/95261974/191400038-6d3311ba-ff7d-44bb-9f91-3f8a4df7c819.png)

4. Dropdown display 
   a. Option 1: use select component which allows clearing
   b. Option 2: add null option 

![image](https://user-images.githubusercontent.com/95261974/191401011-5583fb1a-3982-4d57-9070-2ce7266e4d2a.png)

**Comment by hisunnymay** [comment]
Updated issues left - 0921

1.  Can't edit column whose type is localTime
2. Can't set text value to null

![origin_img_v2_1ab48bf3-3ad3-4e98-ab3d-68512dd63cbg](https://user-images.githubusercontent.com/95261974/191145981-a99be4e4-5823-40f8-9b3b-ff345032cfb0.jpg)



![image](https://user-images.githubusercontent.com/95261974/191401011-5583fb1a-3982-4d57-9070-2ce7266e4d2a.png)

**Comment by xiaoyunwu** [comment]
why we need to set text value to null?

**Comment by hisunnymay** [comment]
目前支持键入 time 或者从选项框中选择，Cell 输入时是 12 小时制，Table 显示时是 24 小时制

![image](https://user-images.githubusercontent.com/95261974/192707753-2e640645-b0b3-48e0-8e3f-2f03463ee7b8.png)

**Comment by hisunnymay** [comment]
Updated issues left - 0928

1. Can't set text value to null

![origin_img_v2_1ab48bf3-3ad3-4e98-ab3d-68512dd63cbg](https://user-images.githubusercontent.com/95261974/191145981-a99be4e4-5823-40f8-9b3b-ff345032cfb0.jpg)

**Comment by hisunnymay** [comment]
目前没有 Can't set text value to null 在 restaurant 的使用场景，暂时先 close 了
