### ISSUE TITLE
[Feature Request]: Display projects by their names in ascending order

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

在 component export 的页面，对 project (component/provider/chatbot) 按照名字升序排列

![origin_img_v2_beed9345-c0f6-4377-adaa-7ead7a4de06g](https://user-images.githubusercontent.com/95261974/189092013-5f2d570f-64fd-4778-b26b-e135d75fe825.jpg)

### Motivation

目前 project 的排列好像没有什么规律，builder 需要挨个查看 project 的名称，不是很方便。如果能按照一定规律，比如按名字升序排列，builder 能更便捷地查找到他需要导入的 project

### Describe alternatives you've considered

/

### Additional context

/

**Comment by hisunnymay** [comment]
@jfang137 哈喽，目前好像有区分大小写字母，先显示的是大写字母开头的排序，然后是小写字母开头的排序。如果我们允许 builder 以大写字母开头命名 chatbot 的话，我们能不区分大小写，统一按开头字母升序排序吗？

![image](https://user-images.githubusercontent.com/95261974/190293880-86c9acf7-62a1-452f-b104-0025100f6478.png)

- Component link：https://build.framely.ai/org/615fa4282cc41400665536e3/agent/6311c7f5eae54c834e200069/service_schema

**Comment by jfang137** [comment]
可以

**Comment by hisunnymay** [comment]
Checked, 现在是没有区分大小写字母按字母升序排序的

![image](https://user-images.githubusercontent.com/95261974/190297355-57222c29-4d29-4434-916e-61fe25d48d6f.png)
