### ISSUE TITLE
[Feature Request]: In channel tab, change "RESTful" to "Universal" 

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

将 channel tab 中默认的 "RESTful" 改为 "Universal" （lang_map 中没有这个字段）：

- before
<img width="981" alt="image" src="https://user-images.githubusercontent.com/37056884/190094778-972b60dd-08a1-4ebc-9f33-a8200a1b2b3b.png">

- after
<img width="981" alt="image" src="https://user-images.githubusercontent.com/37056884/190095291-7c6bb73d-74d9-4e01-83a7-a25da09340ae.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by jfang137** [comment]
前端tab展示改着没问题，但是数据库里全是restful, 所以传给codegen的也是restful不会变 @Zeng666666

**Comment by Zeng666666** [comment]
@jfang137 好的，可以的

**Comment by Zeng666666** [comment]
checked
