### ISSUE TITLE
[Bug]: Dropdown is not disabled when switching to text from dropdown on the platform

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

目前将之前配置过 dropdown 的 slot 的 input type 改为 text 之后，重新 deploy，backoffice 中仍有 dropdown，Table：_column 里面对应的 column 的 columnType 也仍是 `select`

不确定是不是前端传的 input type 是 dropdown，因为尝试复现的时候，我创建了一个新的 table，添加了新的 slot
1. 点击 dropdown 之后，又切换回 text 
2. 点击 deploy，backoffice 中这个新的 column 也有 dropdown

![image](https://user-images.githubusercontent.com/95261974/191214364-c0de1ae0-17df-4e48-8284-15e9a9bde41f.png)

### Expected Behavior

如果 slot 的 input type 是 text，deploy之后，backoffice 中应该没有 dropdown, 对应的 columnType 不是 `select`

### Use Case

在 implement [orderProvider](https://build.framely.ai/org/615fa4282cc41400665536e3/agent/62f0a64470b8ad035ce6234b/service_schema) 的时候，点到了 dropdown 之后，切换回了 text，然后 deploy 之后，backoffice 中显示的是 dropdown，需要在 PostgreSQL 中手动修改 _column 的值，才能切换回 text 输入

### Framely Link

https://build.framely.ai/org/615fa4282cc41400665536e3/agent/631996f86f6081363ca2990c/frame/631997126f6081363ca2990f/slot/631997386f6081363ca29913

**Comment by jfang137** [comment]
@HuiCheng 我看了下这条数据，传过去的input type是text,
<img width="861" alt="image" src="https://user-images.githubusercontent.com/16040960/191391861-95be18bc-8f84-4f18-ba53-328832811b34.png">

**Comment by hisunnymay** [comment]
Checked
