### ISSUE TITLE
[Feature Request]: Move URL to input type and change it to Media

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. 将 input type 的 Radio 单选框移动到 Input Type 的右侧
2. 不再显示 URL 开关
3. 在 input type 中添加 Media 选项，显示逻辑同之前的 URL

![image](https://user-images.githubusercontent.com/95261974/191429229-088367d8-3a56-4b5b-a026-0dd3f3aec818.png)

### Motivation

当 URL annotation 开启时，在 backoffice中能上传图片，根据文档 _[backoffice annotation](https://naturali-io.feishu.cn/docs/doccnBo2UaiHIb4jA31sT8V0rR1)_ ，是属于 input type 的，所以可以移动到 Input Type 中
 
![image](https://user-images.githubusercontent.com/95261974/191426139-cc684858-85e3-4c29-9227-f93f1e07547a.png)

### Describe alternatives you've considered

/

**Comment by jfang137** [comment]
这样弄有两个问题，旧数据不兼容；当data type从text/varchar改回其他时，已经选的media就变成非法选项了。

**Comment by hisunnymay** [comment]
@jfang137 

@Zeng666666 和我这边可以不用考虑对旧数据的兼容。

当data type从text/varchar改回其他时，清空 builder 已选择的 input type，将 input type 的选择恢复到默认值

**Comment by jfang137** [comment]
我说的兼容是数据库的

**Comment by hisunnymay** [comment]
@jfang137 意思是需要先清除使用过 URL 的数据吗？

**Comment by jfang137** [comment]
算了，我刷一下看看吧

**Comment by jfang137** [comment]
@HuiCheng 这需求也得你那边的inputType支持“media”,且废弃掉isMedia字段

**Comment by hisunnymay** [comment]
Checked.

![image](https://user-images.githubusercontent.com/95261974/191669200-2238e650-b253-4021-8b19-e2f72e221a5f.png)
