### ISSUE TITLE
[Bug]: Get an error testing a postgrest function in a provider

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 postgrest provider：[reservationProvider_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cfc7efba1927bffe7a7d7/service_schema) 中使用 Function Testing，第一次点击 "Execute" 会有报错：
> Could not find the reservationProvider_v2.origin_getDates(time_param) function or the reservationProvider_v2.origin_getDates function with a single unnamed json or jsonb parameter in the schema cache

通常需要再点击一次 "Execute", 才能正常调用被测试的 function

![image](https://user-images.githubusercontent.com/95261974/199137971-a1bba8d1-6b89-434e-a3c2-95c45f98422e.png)

### Expected Behavior

第一次点击 "Execute" 时能调用被测试的 function，并返回结果

### Use Case

/

### Steps To Reproduce

1. 在 [reservationProvider_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cfc7efba1927bffe7a7d7/service_schema) 中点击 Try it now
2. 选择 orgin_getDates
3. 传入参数为 `14:00`, `small`
4. 点击 **Execute**

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cfc7efba1927bffe7a7d7/version

**Comment by jfang137** [comment]
@hisunnymay 我发现参数输入框是kotlin ide,  时时保存很难。  所以我对execute稍作延迟保证先失焦保存，你先试试看

**Comment by hisunnymay** [comment]
@jfang137 现在第一次能成功调用了，不过第二次调用的 function 的传入参数还会包含第一次调用的 function 的传入参数

**Comment by hisunnymay** [comment]
Checked, fixed.
