### ISSUE TITLE
[Bug]: on the branch that I do not have access, try it now works, but I can not view log.

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

as description.

### Expected Behavior

I do not know:
1.  whether we should stop try it now when user do not have permission.
2. make log viewable by give user a new instance,
3. make log viewable with existing instance, then it will see what other people typed. 

### Use Case

n/a

### Steps To Reproduce

n/a

### Label of org.project

me.test/abstractEntity_1007

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/633faedb28e4f04b5f845f1a/test_case

**Comment by Zeng666666** [comment]
@jfang137 最终选择方案一：当用户没有分支权限时，他不能使用 Try It Now，即不能测试 master 表现。

因为现在的实现是只要使用 try it now，就会起一个新的 instance，未来不好界定这部分谁来支付。但其实 chatbot 有 test case，没有分支权限的人可以通过 test case 了解具体表现，如果想试用可以 clone 到自己的 org 内，用自己的资源测试。

**Comment by jfang137** [comment]
我改成了如果builder没有edit权限，就隐藏try-it-now按钮

**Comment by xiaoyunwu** [comment]
closed then.
