### ISSUE TITLE
[Bug]: Got duplicate STRUCT agents

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 import component 并 commit 之后，页面上出现两个 STRUCT agent 

![image](https://user-images.githubusercontent.com/95261974/199216010-42e72e75-ab70-4deb-8cf9-3e7680e9e524.png)

### Expected Behavior

因为创建的时候添加的语言是 EN，所以应该显示一个 STRUCT 和一个 EN

### Use Case

/

### Steps To Reproduce

1. 新建一个 chatbot [duplicateStruct](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/6360f4d336e2133c1bf416a3/intent)
2. 将 component [order](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/6329288036b90caee5c733d5/service_schema) import 到该 chatbot 中
3. 切换到 chatbot 中，点击 commit
4. 再点击切换到 EN
5. EN 变为 STRUCT，并且只有一个 STRUCT 选项，没有 EN 选项

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/6360f4d336e2133c1bf416a3/intent?page=0&imported=false&search=

### Additional information
1. 目前修复的方法是：
回到 STRUCT agent，在 Setting 页面重新添加 EN，这样会导致出现 2 个 STRUCT 和 1 个 EN，然后再删除一个多余的 STRUCT agent 
2. 问题出现的时间：
10月31日 3:41 PM, John 最先遇到这个问题

**Comment by jfang137** [comment]
@hisunnymay  step2 如果仅仅是其他操作，会复现吗？

**Comment by hisunnymay** [comment]
> @hisunnymay step2 如果仅仅是其他操作，会复现吗？
稍等，我试一下呢

**Comment by hisunnymay** [comment]
Checked, fixed.
重复上述操作，没有复现多个 STRUCT 的情况
