### ISSUE TITLE
[Improvement]:  import agent 时，可以选择 agent 类型

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

import agent 时，下拉菜单先选择 org，再选择 agent。希望选择 org 后，可以先选择 agent 类型，再选择 agent：

![image](https://user-images.githubusercontent.com/37056884/157029434-71a21b3a-8ced-4675-aec0-6caa4f7ef3a9.png)

### Motivation

原因同 #47 在 import 时，无法准确找到想要导入的 agent，尤其是不好区分 component、provider、chatbot

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
there are different way of doing this, like add the type of the agent to the name, like test(component), test1(chatbot), for example,

**Comment by xiaoyunwu** [comment]
This seems should be a lower priority,. @Zeng666666

**Comment by Zeng666666** [comment]
@xiaoyunwu 是的，交互需要统一：

![image](https://user-images.githubusercontent.com/37056884/157455495-63268c15-d63e-435c-82e4-31de5b26a885.png)

![image](https://user-images.githubusercontent.com/37056884/157455642-ba6e5371-9a8c-482e-9a67-b930f4590651.png)

**Comment by Zeng666666** [comment]
reviewed
