### ISSUE TITLE
[Bug]: Failed to select a provider for a service when the provider is private deployed

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

当 [native provider](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/637b25be220b636ad0dd1565/version) 是 OpenCU-hosted 的时候，chatbot 能为 service 选择该 provider，但当该 provider 改为 private deploy 之后，chatbot 的 provider 选项中就没有这个选项了

![image](https://user-images.githubusercontent.com/95261974/202991360-2888b316-39be-40c9-bc16-0a6b6956ef9c.png)

### Expected Behavior

不论 provider 的 deploy 模式是什么，chatbot 应该都可以为 service 选择到该 provider

### Use Case

/

### Steps To Reproduce

1. 进入 chatbot：[testApp_1121](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/637b25d7220b636ad0dd156b/setting?tab=2) ，点击 Select Service
2. 选择 service 之后，点击 Select service implementation

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/637b25d7220b636ad0dd156b/setting?tab=2

**Comment by jfang137** [comment]
@hisunnymay @Zeng666666 前端加过筛选条件，provider的deploy mode要与chatbot一致，忘了具体原因，产品方面商量下，如果不需要这个条件我就去掉

**Comment by Zeng666666** [comment]
@hisunnymay 这个的确是这样设计的，因为改了 deploy mode，就说明 native provider 是 external 了，external 的是不能用在我们 hosted chatbot 上的

**Comment by hisunnymay** [comment]
@Zeng666666 明白了，找到了之前的文档（https://naturali-io.feishu.cn/docx/MOTvdGu6to6VXgx5WEScs6uCnPg）
@jfang137 那这个不用改，我 close 了
