### ISSUE TITLE
[Bug]: Failed to change project label and got an error(duplicate key)

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

尝试将 [hoursProvider_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cf3c5fba1927bffe79c86/service_schema) 修改为 **hoursProvider**，保存改修改时出现报错：_key duplicate_ 

![image](https://user-images.githubusercontent.com/95261974/204082781-aa435170-c856-4f2e-8c51-ccb2550e31e8.png)

这个 org [me.demo](https://build.opencui.io/org/622c8ff683536204fe062b55/component_agent) 之前存在 **hoursProvider** ，但 10月17日的时候已经将这个 provider 改名为了 [hoursProvider_v1](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63101e0437fed01baf0079b3/service_schema)。目前搜索 org 中的 provider 没有找到 **hoursProvider** 

![image](https://user-images.githubusercontent.com/95261974/204082754-5ccdb15e-250f-4166-ad5a-8a7e52b3dc9d.png)

### Expected Behavior

当 org 中不存在 **hoursProvider** project 时，应该可以修改 project 的 label 为 **hoursProvider**，或者创建 label 为 **hoursProvider** 的 project

### Use Case

/

### Steps To Reproduce

1. 进入 [hoursProvider_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cf3c5fba1927bffe79c86/setting)
2. 修改 **Project Label** 为 **hoursProvider**

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cf3c5fba1927bffe79c86/setting

**Comment by hisunnymay** [comment]
[hoursProvider_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cf3c5fba1927bffe79c86/service_schema) 可以修改 label 为 hoursProvider 了，但 [hoursApp_v2](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/634cf60ffba1927bffe79ff9/intent) 修改 label 后，仍有 _key duplicate_ 的报错 

![image](https://user-images.githubusercontent.com/95261974/204182794-8360fdfd-af9c-4b26-b6cf-72a4661165ef.png)

**Comment by jfang137** [comment]
@hisunnymay 因为master上确实存在重名的agent,你只是在你的分支上改成了hoursApp_v1,重名判断的是master上的数据
<img width="504" alt="image" src="https://user-images.githubusercontent.com/16040960/204185222-f6420a7d-16ea-4026-b985-722ead6d68d7.png">

**Comment by hisunnymay** [comment]
@jfang137 我这里好像没看到改名的 master 数据

![image](https://user-images.githubusercontent.com/95261974/204187364-e3ffbbe4-b7df-412d-87d5-4262c6202d0d.png)

**Comment by jfang137** [comment]
不是这个agent，同org下你有一个hoursApp_v1.你去看下那个diff

**Comment by hisunnymay** [comment]
哦哦明白了，把 hoursApp_v1 删除之后就可以了，那没问题了。
