### ISSUE TITLE
[Bug]: Failed to upload avatar

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 User Profile 中上传头像，提示上传成功，但头像没有变化

![image](https://user-images.githubusercontent.com/95261974/204176869-bb3a3ea0-ad22-46b9-9ff2-0548f47de5f3.png)

### Expected Behavior

上传成功后，应该显示上传的头像

### Use Case

/

### Steps To Reproduce

进入 [User Profile](https://build.opencui.io/account) 修改用户头像

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/account

**Comment by jfang137** [comment]
@HuiCheng 我debug 时候能正常修改，但是线上环境 上传图片的接口好像不太正常，没有返回图片的url

**Comment by jfang137** [comment]
curl 'https://build.opencui.io/api/v1/dialogflow/tools/upload_images' \
  -H 'authority: build.opencui.io' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'agentid;' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryUmQ2e6g2XBEBK67a' \
  -H 'cookie: framely-locale=en; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3Rva2VuIjoiNjY2Mjg2MTk5MzQ5OTcyOTkyIiwiZXhwIjoxNjY5Nzc2MzA5LCJpc3MiOiJuYXR1cmFsaSJ9.dH-_LUBIZBKIpk8ZehNQ_bCUUSWwDHVxNMkKzMzHKFM' \
  -H 'locale: en' \
  -H 'orgid;' \
  -H 'origin: https://build.opencui.io' \
  -H 'pragma: no-cache' \
  -H 'referer: https://build.opencui.io/account' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'userid: 666286199349972992' \
  --data-raw $'------WebKitFormBoundaryUmQ2e6g2XBEBK67a\r\nContent-Disposition: form-data; name="image"; filename="WechatIMG43.jpeg"\r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundaryUmQ2e6g2XBEBK67a--\r\n' \
  --compressed

**Comment by jfang137** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/16040960/204181413-36535f39-243d-4bb7-957f-57e3c8b32de5.png">

**Comment by hisunnymay** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/95261974/207223334-602a685e-a5cd-4c29-b3e6-cfa55af38d69.png)
