### ISSUE TITLE
[Bug]: Switch to the first tab automatically after saving changes in the second tab

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 Integration (tab=2) 界面，添加 service provider 后点击保存，页面会自动跳转到 General (tab=1) 页面

> 注： 上述情况不是每次都会发生。除了点击 save 会有上述现象，有时点击 commit 之后，也会自动切换 tab

截图：
1. 添加 service provider

![img_v2_cb0c3636-ef89-4b60-a306-6f6ce3d3acag](https://user-images.githubusercontent.com/95261974/204222664-bfff6c5b-23a6-46c3-9d86-e56fc66fcfb1.jpg)

2. 点击 Save 后，页面自动跳转到 General

![img_v2_be932dde-2be3-4b29-b9ca-8e255bfb41fg](https://user-images.githubusercontent.com/95261974/204222737-203f6f6a-457e-49c7-b9c0-e77dbbc538a6.jpg)

### Expected Behavior

在STRUCT 中，保存 builder 的修改后，tab 不应该主动变化

### Use Case

/

### Steps To Reproduce

1. 点击进入 [Integration](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/6384453401beb60ccdfa07fa/setting?tab=2)
2. 点击删除 service provider

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/6384453401beb60ccdfa07fa/setting?tab=2

**Comment by hisunnymay** [comment]
按照上述复现步骤操作没有复现该问题，但打开新的窗口，进入该 chatbot 中，添加 service provider 仍会自动跳转到 General tab。录屏如下所示。

https://user-images.githubusercontent.com/95261974/204239640-11002838-3116-4767-a657-4b3a0f743536.mp4

**Comment by jfang137** [comment]
@hisunnymay 再试试呢

**Comment by hisunnymay** [comment]
@jfang137 现在可以啦～

Check, it's fixed.
