### ISSUE TITLE
[Bug]: Time out and 404 error

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

目前 [testFunction_1206](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/638d5a3101beb60ccdfb2dbc/intent) 能 debug，但每次点击 merge 时都有报错：time out。
今天新建的 [delete_1208](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/639141d2336ee924510e95da/intent) 不能 debug，每次点击 connect 都有 404 报错：

> dispatcher request error
> request url: https://tin-3d858fe750ae51ffbbb499f9593c6e17.framely.ai/v1/tryitnow/en
> status:404 Not Found

1. 网页请求显示 deploy 成功
![image](https://user-images.githubusercontent.com/95261974/206337383-f6a9a181-437f-454c-b03f-a06f7826bdab.png)

2. 网页请求显示 review 超时
![image](https://user-images.githubusercontent.com/95261974/206337815-243746d5-7445-4fba-a3df-4fe93ddbf145.png)

3. 404 报错
![image](https://user-images.githubusercontent.com/95261974/206338244-01ef70e8-a6b0-40d5-9542-d0239fd13281.png)

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

1. time out: 在 [testFunction_1206](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/638d5a3101beb60ccdfb2dbc/intent) 点击 merge

2. 404: 在 [delete_1208](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/639141d2336ee924510e95da/intent) 点击 debug > connect 

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/638d5a3101beb60ccdfb2dbc/version

**Comment by hisunnymay** [comment]
Fixed, 目前没有这个报错了

**Comment by hisunnymay** [comment]
merge [DefaultApplication](https://build.opencui.io/org/600faced6ef4d6d82c040ecd/agent/633fadd228e4f04b5f8452c8/intent) 时，出现 timeout 的报错，重新 merge 仍有 timeout 报错


![image](https://user-images.githubusercontent.com/95261974/206354289-9ae8ecc4-e4bd-4b67-b716-a551841f41c2.png)

**Comment by hisunnymay** [comment]
重新试了一下，又能 merge 了

**Comment by hisunnymay** [comment]
@HuiCheng 哈喽，现在有 timeout 的报错了，点击了 8 次 connect，出现了 5 次 timeout。

除此之外，在多次 timeout 之后，connect 成功后，bot 输出的内容不是 branch commit 的数据，而是 master 的数据。

![GfTZoVyWwy](https://user-images.githubusercontent.com/95261974/207753802-9bbf5ca2-f82b-49cb-8df3-fdeb8a5d4bc8.jpg)

**Comment by HuiCheng** [comment]
今天新建的 [delete_1208](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/639141d2336ee924510e95da/intent) 不能 debug，每次点击 connect 都有 404 报错：

如果还是404 随意修改点response 再debug

**Comment by hisunnymay** [comment]
@HuiCheng 新建了一个 chatbot：[deleteApp_1219](https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/639ff0cec1fe5a83b614ca87/intent)

1. 第一次点击 connect 有 404，再点击 connect，能  connect 成功。
2. 修改 response，点击 connect 显示 timeout，再点击 connect，能  connect 成功，但第一次输出的回复不是当前 master 下定义的回复

![image](https://user-images.githubusercontent.com/95261974/208353126-7e3f0f50-495c-465a-bcc5-069df7a017d5.png)

**Comment by HuiCheng** [comment]
服务降级了

**Comment by hisunnymay** [comment]
目前没有 connect 404 和 time out 的报错了

![image](https://user-images.githubusercontent.com/95261974/211233922-9149c993-bfab-4724-9932-4699caf934ad.png)
