### ISSUE TITLE
[Bug]: Get an error for nonexistent function

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 chatbot：[reservationApp_v4](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/entity/63734f8420b0d2661d800415?tab=config) 中，Entity(TableType) 中已经删除了 identifier function，但 commit 后点击 connect 后仍有报错，且无法导出该 chatbot
> 报错：function identifier of TableType should be implemented

![image](https://user-images.githubusercontent.com/95261974/206341799-4567d84d-c534-4d3b-bd9a-f180cc37ef1d.png)

### Expected Behavior

如果平台上没有定义 function identifier，那么应该不需要 implement function identifier?

### Use Case

/

### Steps To Reproduce

进入 [reservationApp_v4](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/entity/63734f8420b0d2661d800415?tab=config) 后，点击 Debug > Connect

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/entity/63734f8420b0d2661d800415?tab=config

**Comment by jfang137** [comment]
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/16040960/206345965-d89495fc-2ba2-4dcf-b4ff-14a94df7ccd3.png">
provider中的imported service好像没有更新
@hisunnymay

**Comment by jfang137** [comment]
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/16040960/206346264-58411e86-355b-4976-b784-680f9711cc4c.png">

**Comment by hisunnymay** [comment]
@jfang137 哦哦看到了谢谢，修改了现在好了
