### ISSUE TITLE
[Bug]: Content overflows the box when there are two languages

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

目前当有两个语言时， chatbot settings 中的 和创建 chatbot 时的 language 内容溢出了显示框

1. Settings
![image](https://user-images.githubusercontent.com/95261974/206347000-992c176f-31a6-4537-9ac3-d0e601914dd0.png)

2. 创建 chatbot 时
![image](https://user-images.githubusercontent.com/95261974/206347030-6e08dafd-73cf-4fa3-9842-c597b5794dd4.png)

### Expected Behavior

之前好像是并排显示在同一行的？

P 了一个示意图：
![image](https://user-images.githubusercontent.com/95261974/206350810-dcb39bd2-79e4-4293-9173-aec30f4d4d48.png)

### Use Case

/

### Steps To Reproduce

点击进入 https://build.opencui.io/org/600faced6ef4d6d82c040ecd/agent/633fadd228e4f04b5f8452c8/setting 即可查看

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/600faced6ef4d6d82c040ecd/agent/633fadd228e4f04b5f8452c8/setting

**Comment by jfang137** [comment]
限制select宽度后就这样了，我把这两个select还是弄成行宽吧

**Comment by hisunnymay** [comment]
Fixed，现在两个语言能正常显示

![image](https://user-images.githubusercontent.com/95261974/206371226-384dd4de-7116-475b-94ee-13fb60c58c67.png)

![image](https://user-images.githubusercontent.com/95261974/206371276-8d42164a-b7ae-4d92-80f7-2e428b73792c.png)
