### ISSUE TITLE
[Feature Request]: Can we hide VR's showtime on platform

### ISSUE THREAD

**Issue by yigexu** [framely/community#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Since we are not designing for show time any more, can we hide it?
<img width="2115" alt="Screen Shot 2022-03-08 at 9 45 40 AM" src="https://user-images.githubusercontent.com/6505755/157149560-7d654288-8d9d-4169-a72d-528cb7f86769.png">

### Motivation

/

### Describe alternatives you've considered

/

**Comment by Zeng666666** [comment]
当然可以，这个过去提过，但说有用，就没有被隐藏，如果不需要了，可以隐藏起来。

**Comment by xiaoyunwu** [comment]
hide for now.

**Comment by yigexu** [comment]
@jfang137 when you have time.
