### ISSUE TITLE
[Feature Request]: Value Recommendation (Zero entry prompt, and hard mode exception) (Originally Change runtime part of VR hard's behaviour)

### ISSUE THREAD

**Issue by yigexu** [framely/community#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Check this: [VR (ZEP, and hard exception)](https://naturali-io.feishu.cn/docs/doccnaJQSKvCyNf5YSDUMknej1z)

<details><summary>Deprecate</summary>
<p>

Background: #50 

Requirement:
1. runtime 将 VR hard 在 N 条时的表现改为和 soft 相同，即
  - 展示 function result list
  - 当 user 选中的内容匹配到 list 中的 多个 candidates 时，展示匹配到的结果
  - 当 user 选中的内容匹配到 list 中的 1个 candidates 时，选中填槽
  - 当 user 选中的内容匹配到 list 中的 0个 candidates 时，选中填槽
2. builder 需要对上面 “user 选中内容匹配到 0个 candidates” 的情况自行使用 VC 检查，并告知 user 选中内容不合格

Note:
1. 目前没有 VC 在 MV 下的具体场景，因此对 per value VC 的情况不做设计。但 runtime 现有的设计应该/可以保证 per slot 的 VC 在 MV 时正确表现。

</p>
</details>

 

### Motivation

/

### Describe alternatives you've considered

/

**Comment by xiaoyunwu** [comment]
what? Why not jusr hide hard vr then ?

**Comment by xiaoyunwu** [comment]
Or have builder use soft

**Comment by yigexu** [comment]
SEP 和 ZEP 不一样

**Comment by yigexu** [comment]
Or have builder use soft： #50 里面有 hard VR-N 现在的表现，那个表现是不可接受的

**Comment by yigexu** [comment]
@xiaoyunwu 我以为你对#50 VC方案没什么问题了；
如果 revert 到还在讨论方案的阶段，我们还有一个 choice 是在 platform 把 hard/soft downgrade 成 SEP/ZEP 发挥作用。（不过它跟 runtime 的实现可能是 parallel decision。)

**Comment by xiaoyunwu** [comment]
LGTM.

**Comment by Zeng666666** [comment]
by design

![image](https://user-images.githubusercontent.com/37056884/157171243-bf49d6c6-db72-4d56-b4d1-c7385bb785c2.png)

https://naturali-io.feishu.cn/docs/doccn7QgZ5MoRGsMAIXYfBSzSBJ

**Comment by Zeng666666** [comment]
我好像没有 get 目前遇到了什么问题，hard VR-N 不可接受的表现是什么呢？我在 #50 中没有找到，里面有好几个

**Comment by xiaoyunwu** [comment]
I remember it is from one of Chang's writing.

**Comment by yigexu** [comment]
@Zeng666666 
<img width="592" alt="Screen Shot 2022-03-08 at 1 37 56 PM" src="https://user-images.githubusercontent.com/6505755/157173318-91b7d47b-a83b-4642-b01e-0a6dcebb18eb.png">

**Comment by Zeng666666** [comment]
有这个 agent 的地址吗？还是我定义一个就可以复现了？

**Comment by Zeng666666** [comment]
@yigexu 这个截图是指，VR 在选择 soft 和 hard 的时候，这个 case 的表现是不同的是吗？

![image](https://user-images.githubusercontent.com/37056884/157174736-a91b5420-09b4-4894-b8be-55a0568fb39d.png)

**Comment by hisunnymay** [comment]
@Zeng666666 可以看[example_2_user_none_one_of_the_vr_but_one_from_entity](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6205cc0ad980a8d37823fb8d/test_case)

1. hard表现：让user重新选择，但是不输出vr-body
2. soft表现：直接填槽，user不用重新选择

![image](https://user-images.githubusercontent.com/95261974/157177547-2249dc1e-a39c-4f17-bffd-34d0d3974395.png)

**Comment by Zeng666666** [comment]
明白了。我理解这里的问题是：

**VR-Hard 时，没有填槽，bot 重新追问时，应当有 prompt + VR（header+body+footer），现在 VR 返回了 header 和 footer，却缺失了 body，这里应该是个 bug**：

![image](https://user-images.githubusercontent.com/37056884/157180902-241670eb-7e5e-412f-8bc0-d760f60c566f.png)

VR-soft 和 VR-hard 从定义角度时不同的：

  1. Hard: all the legal candidates will be returned by function. 

  2. Soft: only some legal candidates will be returned by function. 

因此预期表现应当是不一致的！
Hard 是认为所有合法 candidate 都 return 了，因此超出范围是没有被填进去的。
Soft 认为没有都展示，因此符合 type 的都认为是合法的，所以填进去了。

我理解这里是不同的，因此不应该改 soft 与 hard 的设计。

@yigexu @hisunnymay @xiaoyunwu

**Comment by Zeng666666** [comment]
我 copy 了一个 agent，加了几个字段的定义：

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6205cc0ad980a8d37823fb8d/intent/6205cc33d980a8d37823fb97

Testcase 见：test75

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6205cc0ad980a8d37823fb8d/test_case

**Comment by yigexu** [comment]
1- hard/soft定义的是 VR 推荐什么（推荐的是function返回的candidates，这一点现在也没变），不定义 user 可以填什么。
2- user 填上不合格的结果之后，runtime怎么表现之前没设计过。所以不是 bug。

**Comment by Zeng666666** [comment]
可以看一下这个文档：https://naturali-io.feishu.cn/docs/doccn7QgZ5MoRGsMAIXYfBSzSBJ

1. 退一步说，无论怎样理解或解读，VR 的 header、body、footer 是一个整体，在 {} 内，不应该出现遗失 body 的情况，这里肯定是一个 bug；

2. Hard 与 Soft 经测试体验是如下，除了 bug 外我理解预期是这样：

Hard 表现：

![image](https://user-images.githubusercontent.com/37056884/157187673-b8ebd1da-d00c-467e-93fd-ad7195bdc90b.png)

Soft 表现：

![image](https://user-images.githubusercontent.com/37056884/157188999-93f1f473-0b71-42b1-98c8-46184ed2db27.png)

**Comment by yigexu** [comment]
目前的表现是你截图这样，但是vr body为空（空行）的体验是没办法被接受的：
我们提供给builder一个annotation，他按照我们的要求去定义了，然后user说了一句话，对话体验成了“你想选择哪天？我们有：请选择。”
这个需求就是定义对runtime的预期以不出现这种体验。

**Comment by Zeng666666** [comment]
嗯嗯，需要看一下这个“空 body”是什么原因，所以我上面说是“缺失 body 的 bug”

**Comment by Zeng666666** [comment]
预期：

1. 修复 VR Hard 时，未得到 value 再次追问时，VR 只输出 header、footer 未输出 body 的 bug；

2. 为 VR Hard 增加，因超出 resultset 导致再次追问的异常提示信息“Outlier Prompts”；

详情见文档：https://naturali-io.feishu.cn/docs/doccnNQPx4qOBD8W14n42zowxuh#

**Comment by xiaoyunwu** [comment]
https://naturali-io.feishu.cn/docs/doccnaJQSKvCyNf5YSDUMknej1z

**Comment by Zeng666666** [comment]
测试了一下，目前体验上有这 3 个问题：

1. 【问题】当 Hard ZEP 的时候，预期回复 ZEP 并退出 intent。目前回复 ZEP 后，就没有其他提示了，也没有追问 what else can I do for you？就好像暂停了，end-user 不知道此时的状态以及该做什么。
  
   - 【预期】退出 intent 可以有一个系统回复。比如，执行“AbortIntent”的 response，然后按照流程再接“What else can I do for you?” 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/37056884/161370223-c361a4c5-fc36-49e4-9d3a-512946baf8f9.png">

2. 【问题】在 Hard SEP Explicit 时，end-user 选择了在 slot type 范围内，但不在 function result set 中的 value，没有执行 BadCandidate intent。

   - 【预期】Hard SEP Explicit 时，超出范围应当先执行 BadCandidate intent 再重复追问 SEP。
   - 【Test Case】SEP-out-of-scope https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6231b689a2f5156952d59211/test_case

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/37056884/161370892-d7fa5fb4-b454-40af-8fa6-f2b18c5e2b59.png">

3. 【问题】在 MV Hard SEP 时，end-user 选择了在 slot type 范围内，但不在 function result set 中的 value，会填槽进去。

   - 【预期】MV Hard SEP Explicit 时，超出范围应当先执行 BadCandidate intent 再重复追问 SEP。
   - 【Test Case】MV-SEP-hard-out-of-scope https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6228443a068261d652db7e64/test_case
   
<img width="531" alt="image" src="https://user-images.githubusercontent.com/37056884/161375380-ae65efa5-bf9d-4ddd-b416-22d65f4a2686.png">

**Comment by XiaoboYuan** [comment]
@Zeng666666 @xiaoyunwu 
关于问题1确认两个事情
1. Main的List<IIntent> slot是叫skill还是叫skills？runtime在搜索target intent（比如在abort intent）过程中对Main做了特殊处理，所以这个是不能随意修改的，需要确定一个
2. 这里是确定要执行abort intent的response吗？

**Comment by xiaoyunwu** [comment]
Should we move to skills? Both platform and runtime ?

**Comment by xiaoyunwu** [comment]
And abort is good for hard zep as default strategy

**Comment by XiaoboYuan** [comment]
问题1修复了
需要把Main的skill修改为skills
另外AbortIntent的response可能不太对，这是abort intent的问题，我之前在别的地方comment过，可以再开一个issue讨论abort intent

**Comment by Zeng666666** [comment]
好的

**Comment by XiaoboYuan** [comment]
修复了问题2和3

**Comment by Zeng666666** [comment]
checked
