### ISSUE TITLE
[Bug]: No result after clicking the "RUN" button

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

选择 [reservationApp_v4](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/test_case) 中的一个 test case
1. 点击 RUN 按键，进度条一直显示 0%，等待 50s 之后，没有消息提示，又重新出现 RUN 按键，Test Case 没有结果

![image](https://user-images.githubusercontent.com/95261974/207516380-75dd6ab7-15b7-4d0e-9d06-5cdd9f0b3cd5.png)

2. 再一次点击 RUN 按键，进度条有变化，提示 Passed，Test Case 有结果

![image](https://user-images.githubusercontent.com/95261974/207516835-6c3f80ed-78dc-4005-8e71-1ce9fb15bad3.png)

### Expected Behavior

第一次点击 RUN 按键，应该有结果

### Use Case

/

### Steps To Reproduce

1. 在 [reservationApp_v4](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/test_case) 中添加新的 test case
2. pr 之后 merge 到 master
3. Run 刚才添加到 test case

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63734f1920b0d2661d80040f/test_case

**Comment by jfang137** [comment]
@HuiCheng 好像隔一两次部署就会timeout一次

**Comment by hisunnymay** [comment]
@jfang137 可以了，现在可以抛出错误了。Repen 了 和 timeout 相关的 issue #732 ，这个 issue 已经解决了。

![image](https://user-images.githubusercontent.com/95261974/207753486-ebcb7ab9-4063-42cb-8c6c-1e82e9623f2c.png)
