### ISSUE TITLE
[Bug]: testcase cannot be seen

### ISSUE THREAD

**Issue by yigexu** [framely/community#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.Lu 在 https://framely.naturali.io/org/621d809561f0057d035f6437/agent/6205cc0ad980a8d37823fb8d/test_case 提交了 testcase test75
<img width="1675" alt="Screen Shot 2022-03-08 at 3 22 07 PM" src="https://user-images.githubusercontent.com/6505755/157186938-d43c3020-3664-4998-806d-b5b94f3f2f9e.png">
2. Yige 看不到
<img width="1672" alt="Screen Shot 2022-03-08 at 3 21 58 PM" src="https://user-images.githubusercontent.com/6505755/157187081-06b01037-65f4-4392-8481-3b7f7738c3c3.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

/

**Comment by yigexu** [comment]
<img width="1677" alt="Screen Shot 2022-03-08 at 3 24 30 PM" src="https://user-images.githubusercontent.com/6505755/157187267-4e863dab-2091-4b40-8982-f5ec63565ef2.png">

**Comment by jfang137** [comment]
@Zeng666666 yige没有这个agent的权限，你加一下呢？

**Comment by Zeng666666** [comment]
但理论上讲，这个 agent 是 meichang 的，yige 应该有权限 

我加一下，不过，我 org 里面的就不是这个 agent 了

**Comment by Zeng666666** [comment]
https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6205cc0ad980a8d37823fb8d/test_case @yigexu 只有 agent 是 6205cc0ad980a8d37823fb8d 才有，地址可以任意写

**Comment by jfang137** [comment]
那先别加了，我回头先调调看

**Comment by Zeng666666** [comment]
这里有一个问题。

org owner 有最高权限。那么，我在我的 org 内，通过地址栏，复制粘贴了一个 agent id（org agent 我都没有任何权限），组成了一个“假” agent。于是，相当于我可以间接的查看、修改他人的定义。。。

![image](https://user-images.githubusercontent.com/37056884/157199473-010782e3-2c56-4d67-8e4a-d3a2dcfdc4f3.png)

**Comment by jfang137** [comment]
这个后面优化想办法优化吧，数据安全需要一步步完善

**Comment by Zeng666666** [comment]
好的

**Comment by jfang137** [comment]
看不见新的testcase是因为是需要rebase的状态，因为没有权限，右侧的版本控制区域隐藏了。不知道什么情况在当前分支做了修改，就导致了这个需要rebase却无法rebase的坑里 @yigexu @Zeng666666

**Comment by yigexu** [comment]
我应该没有对分支做过修改，因为chatbot是最近的，这个org我应该几个月没访问了...
另外我现在还是没有org的权限，和这个有关系吗？

**Comment by jfang137** [comment]
可能是另外那个clone的bug导致的问题

**Comment by Zeng666666** [comment]
大概理解了，我猜测是这样：我们的 agent 和 org 是没有关系的，我们的 org owner 只作用在 org 上，因此：

- 在 meichang 的 org 内，大家 **都是 owner**，因为是 owner 才有了 agent 的权限；
  - yige 在这里有了分支；

- 在 test001 的 org 内，大家 **不是** owner、也没有 agent 权限；
  - zeng 在这里 merge 了 master；

这是同一个 agent id 挂在不同 org id 后的表现，所以 yige 有该 agent id 的分支，但没有 org 权限，因此没有 rebase 权限。

**Comment by jfang137** [comment]
是的，org agent id不匹配的问题我改一下

**Comment by Zeng666666** [comment]
好的

**Comment by Zeng666666** [comment]
@yigexu 我前几天误删了老的 test001，这个 test001 是新建的。[🤦‍♀️]

**Comment by yigexu** [comment]
@Zeng666666 @jfang137 这个问题最后结论是什么？解决完我能看到testcase吗？

**Comment by jfang137** [comment]
之前你看见的是org和agent不匹配的的情况下产生的脏数据，可以说是一个不存在的分支， @Zeng666666 可以重新弄个新的agent试试 @yigexu
