### ISSUE TITLE
[Bug]: Columns are not created in the order of generation

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

Columns are created in the order of alphabet except for ID and created_at.

Order at present: boolean, float, int, localDate, localDateTime, localTime, string
![image](https://user-images.githubusercontent.com/95261974/208406085-1443ffe3-ea25-40d3-b966-907edb51522c.png)

### Expected Behavior

Columns should be created in the order of generation.

Order in expectation: int, float, string, boolean, localDateTime, localDate, localTime
![image](https://user-images.githubusercontent.com/95261974/208406437-7b9b36cc-6d7c-477d-8558-40fa3f04490e.png)

### Use Case

/

### Steps To Reproduce

1. Create a Postgrest provider
2. Create a frame and enable storage
3. Add slots to the frame, merge to master and deploy
4. Go to backoffice

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/625e2f3cd31e3de801ef5a93/agent/639fbf45f250735372676332/frame/639fbfaef250735372676335

**Comment by Zeng666666** [comment]
list order, detail page order, slot order, the order of display is different, they need to be consistent

- List order
![image](https://user-images.githubusercontent.com/37056884/208410491-b9f0b849-034b-44cf-8bb8-5c0a8236f9e7.png)

- Detail Page order
![image](https://user-images.githubusercontent.com/37056884/208410581-d924896d-b0b8-4044-b497-caef35923dea.png)

- Slot order
![image](https://user-images.githubusercontent.com/37056884/208410667-16180440-f940-47e4-91c1-278027fbaed2.png)

**Comment by hisunnymay** [comment]
Checked, It's fixed.
