### ISSUE TITLE
[Bug]: No code completion for the interfaces

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 skill 中添加 service slot 之后，在 code expression 中不会自动补全该 service 以及 service 中定义的 interfaces

1. 添加 service slot

![image](https://user-images.githubusercontent.com/95261974/212228351-104c0050-3b98-4d68-9af7-ec93680bff83.png)

2. 在 code expression 中填写 service 的部分字母，没有自动补全 _（期望此处有 `reservation` 的提示）_

![image](https://user-images.githubusercontent.com/95261974/212228497-e3e684eb-8e8e-44c2-86da-9fb30e1b873b.png)

3. 在 code expression 中填写 service 之后，使用 `.` 调用 service 中定义的 interface，没有自动补全 _（期望此处有 `availableTimeRanges` 的提示）_

![image](https://user-images.githubusercontent.com/95261974/212228617-360d4545-2b3c-4b32-ba1c-83131bb5db1a.png)

### Expected Behavior

在 skill 中添加 service slot 之后，在 code expression 中能自动补全该 service 以及 service 中定义的 interfaces

### Use Case

/

### Steps To Reproduce

1. 进入 [tableReservation - Function_11 (skill) - Response](https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63be10b215b99221ac752317/intent/63c0ca5d9527ebce05500d43?tab=2)
2. 修改 **Multiple Value Message** 的 **Source** 为 `reser` 或 `reservation.avai`

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/622c8ff683536204fe062b55/agent/63be10b215b99221ac752317/intent/63c0ca5d9527ebce05500d43?tab=2

**Comment by jfang137** [comment]
@hisunnymay https://github.com/framely/community/issues/710 之前已经给 @xiaoyunwu 提过feature request了，好像他还没有找到空闲支持

**Comment by hisunnymay** [comment]
@jfang137 好的，我之前用关键词搜索的，没有找到这个，那这个 issue 我就先 close 了
