### ISSUE TITLE
[Feature Request]: Value check function invocation

### ISSUE THREAD

**Issue by yigexu** [framely/community#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Background 
Background and full proposal: [On VC function invocation 2](https://naturali-io.feishu.cn/docs/doccnYbnGmdC7sKuSIwKhYUQn4d)

# Requirement
Snapshot for runtime requirement:
1. runtime will only invoke the function when all actual parameters who are slots are filled. (regardless they are before or after check)
2. There's a chance the actual parameter who is a slot is null if builder using state update and assign null to them. We should leave this to builder's responsibility, since this is caused by them but not user

### Motivation

/

### Describe alternatives you've considered

/

**Comment by XiaoboYuan** [comment]
@xiaoyunwu 
我记得你告诉我没有什么nullable对invocation的影响了，如果我理解的没错的话这个feature request是废弃了吧？

**Comment by xiaoyunwu** [comment]
right, after code gen, runtime does not need to do anything special.
