### ISSUE TITLE
[Bug]: Failed to save text in value check - prompt

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

填写Value check - prompt后，点击“Save”，弹窗显示“Successfully saved”， 再点击进入Value check，发现prompt为空

1. 点击“Save”后的截图
![image](https://user-images.githubusercontent.com/95261974/157820478-69c6bd42-9adf-4558-bd91-2f32bd955a1b.png)

2. 再次进入value check的截图
![image](https://user-images.githubusercontent.com/95261974/157820589-6e0bbce5-b77e-4a10-9df4-6033cf2ce0e7.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/6214832e33a75aab159263ea/intent/621486ff33a75aab15928220/slot/621c9bbb7cb494e0d5fa6f87

**Comment by hisunnymay** [comment]
@jfang137 是不是因为之前定义的intent - value check没有删除掉，导致不能写入新的prompt呀？我的bot现在还会输出之前在intent - value check 定义的内容，但是我在平台上没有办法删除他们。
![image](https://user-images.githubusercontent.com/95261974/157822652-e60109e2-1973-4532-a20f-07e511dfacfc.png)

**Comment by jfang137** [comment]
这个问题先解决了稍后可测，另外发现diff里面看不到修改，issue先别关

**Comment by jfang137** [comment]
ok了

**Comment by hisunnymay** [comment]
@jfang137 现在能添加prompt了，但是当value check failed的时候，bot没有输出value check的prompt

如下图所示，当value check failed的时候，slot：time的值被clear，要求user重新重填slot：time，但是没有输出value check的prompt

1. value check的定义
![image](https://user-images.githubusercontent.com/95261974/157833819-a1aa1225-17e5-417c-9d9e-c3152b5203aa.png)

2. 实际表现
![image](https://user-images.githubusercontent.com/95261974/157834015-e0f7a5d0-f6c6-499a-b95a-7524cdcada4a.png)

**Comment by jfang137** [comment]
哪个bot？

**Comment by jfang137** [comment]
@hisunnymay 我不确定runtime是否已经把value check切换到slot level了，你这个intent之前有7个frame level value check同样传给了后端，只是在前端隐藏了，是不是它们影响了你的预期表现 @XiaoboYuan

**Comment by hisunnymay** [comment]
@jfang137 你之前的处理是把7个frame level value check的prompt清空了吗？能不能帮忙把这7个frame level value check也删除了呢？我这边删除不了在frame level value check中使用了的function

**Comment by hisunnymay** [comment]
@jfang137 可以正常输出vc prompt了
