### ISSUE TITLE
[Bug]: Can't find the imported frame after importing a library

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

1. 在 [tableReservation_demo](https://build.opencui.io/org/me.test/agent/tableReservation_demo/struct/intent) 中导入 [components](https://build.opencui.io/org/io.opencui/agent/components/struct/intent) 之后，创建了一个 skill，在该 skill 中添加 slot，在 Frame 那栏找不到导入的 io.opencui.components.dateEntry.DatePicker

![xM6x05xXfp](https://user-images.githubusercontent.com/95261974/219605342-b7126a5c-a175-48f3-adc0-68ee85163ab5.jpg)

2. 切换到 Frames 页面，点击 Imported，有 DatePicker 和 TimePicker

![image](https://user-images.githubusercontent.com/95261974/219609370-50867b62-6646-42e1-a1c5-f3a1f211ab37.png)

3. 再切换到 skill 中，Frame 那栏仍然没有 DatePicker。
4. 尝试**刷新网页**之后，能在 Frame 那栏找到 DatePicker

![image](https://user-images.githubusercontent.com/95261974/219606269-2d2c37f7-181d-4559-ab86-f5c93a992a63.png)

### Expected Behavior

期望导入某个 library 之后，不需要刷新网页就能在添加 slot 到时候选择到从该 library 导入的 type

如果必须刷新网页，需要通过某种方式让 builder 知道导入的 project 需要在刷新网页之后才能添加 imported frame 类型的 slot

### Use Case

/

### Steps To Reproduce

1. 先进入 [issue_0217](https://build.opencui.io/org/me.test/agent/issue_0217/struct/intent)
2. 再进入 [components](https://build.opencui.io/org/io.opencui/agent/components/struct/intent)，点击 Import，将该 library 导入 module：me.test.issue_0217 中 
3. 回到 issue_0217, 进入 MakeReservation skill，点击 Add Slot，没有  io.opencui.components.dateEntry.DatePicker 的选项
5. 刷新网页，点击 Add Slot，有  io.opencui.components.dateEntry.DatePicker 的选项

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.test/agent/issue_0217/struct/intent?page=0&imported=false&search=

**Comment by hisunnymay** [comment]
Update 23/03/01

等待添加导入 library 之后需要刷新页面的提示

**Comment by jfang137** [comment]
文案更新了刚刚

**Comment by hisunnymay** [comment]
Checked, it's fixed. 成功导入 library 后的提示是：

Successfully imported. If the target project's page is already open, please reload the page to update the local data.

![screenshot-20230302-093835](https://user-images.githubusercontent.com/95261974/222308661-58868d62-8415-4ea9-8736-cdd36b23d753.png)
