### ISSUE TITLE
[Bug]: Wrong loading icon

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

目前点击 Deploy 之后，Pull Request button 会出现 loading 的 icon

![image](https://user-images.githubusercontent.com/95261974/221482975-94c93ab9-80ec-4957-b7f8-257569f999d2.png)

### Expected Behavior

点击 Deploy 之后，如果有 loading 的 icon，应该出现在 Deploy button 上

### Use Case

/

### Steps To Reproduce

1. 进入 [tableReservationApp](https://build.opencui.io/org/me.restaurant/agent/tableReservationApp/en/version)
2. 点击 Deploy，可以看到 Pull request button 上出现 loading 的 icon

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.restaurant/agent/tableReservationApp/en/version

**Comment by jfang137** [comment]
loading 状态应该所有的button都不能点，所以改成了几个button 同时loading

**Comment by jfang137** [comment]
或者button都不loading， 只留loading1, 或者都loading, loading一般不会细化到每一个button上，它是一个页面状态，或者数据相互关联的一组组件的状态

**Comment by hisunnymay** [comment]
@jfang137 哦哦明白了，那可以只留 loading1

**Comment by hisunnymay** [comment]
Checked, 现在点击 deploy 之后，button 不呈现 loading 状态，仅对页面显示 loading 状态 （页面如下）

![image](https://user-images.githubusercontent.com/95261974/221521993-68a71219-c2e5-48c3-ba93-3fcc15ee9e14.png)
