### ISSUE TITLE
[Bug]: Intent End can not work

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 定义了当 number 的 label 是 3 时，执行 Intent End Action：

- 定义：
   
![image](https://user-images.githubusercontent.com/37056884/157833653-e417830d-ed46-41cd-a469-879db456faeb.png)

   - 表现：不会执行 Intent End，会一直走完 Response：

![image](https://user-images.githubusercontent.com/37056884/157834076-e77ffd52-2afd-4646-89a5-7686d98d242b.png)

2. 如果定义了 reply，会在所有 slot 追问完，执行 reply、再执行 response：

- 定义：

![image](https://user-images.githubusercontent.com/37056884/157835997-05924df9-b995-435c-bdb0-47ccb18c80cc.png)

- 表现：不会执行 Intent End，会继续追问下一个 slot，并在 response 之前 reply：

![image](https://user-images.githubusercontent.com/37056884/157834429-059f0b08-3b74-4c64-a962-39053e0e5c34.png)

### Expected Behavior

1. Intent End 应当是满足条件后，就退出 intent，不应该继续追问下一个 slot，也不应该能走到 response 去；

2. 跟 Intent End 一起定义的 Reply 应当在结束 intent 的同时回复出来；
   1. 不知道这里怎么定义顺序？先定义 intent end 还是 reply？

### Use Case

Test Case：https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622b02272fb46d1befef2c7b/test_case

![image](https://user-images.githubusercontent.com/37056884/157835822-40cb3ffd-7a20-4083-bf7e-e275327001f6.png)

### Steps To Reproduce

复现 query：
1. qwer
2. three
3. 123456

### Label of org.project

test001.test_intentend

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622b02272fb46d1befef2c7b/intent/621d942961f0057d035f8f6e/state_update/622b02c32fb46d1befef2ca1

**Comment by XiaoboYuan** [comment]
@Zeng666666 产品需求是intent end在跳过fill的同时会跳过intent的response

**Comment by Zeng666666** [comment]
可以了。

@XiaoboYuan 对了，在 state update 定义时，intent end 和其他 action（比如 reply）需要有先后顺序的吗？比如谁先谁后？会有不同吗？还是都可以？

同样的问题，比如 handoff 和 reply 之间的定义顺序，是有要求的吗？会有不同吗？

**Comment by XiaoboYuan** [comment]
@Zeng666666 
先执行的action如果对后执行的action操作的东西（比如slot）有影响的时候，是会相互影响的
目前intent end和handoff都不改变slot的值，所以textoutput在前或后都没有关系
但是如果是clear slot这种就会有关系

**Comment by Zeng666666** [comment]
好的，明白了

**Comment by xiaoyunwu** [comment]
Intent end is only compatible with messaging. not clean slot.

**Comment by Zeng666666** [comment]
@xiaoyunwu 好的，不过前端上对于 intent end 还没有做任何限制，即 update action 中的选项，目前是都可以选择的。需要做哪些限制吗？比如：选择了 intent end，与之互斥的 action 就不可以选了；如果先选了互斥的 action，那么 intent end 就不能选了。
- intent end 互斥的 action：fill slot、clear slot、recheck、intent start、intent abort；
- 不互斥的 action：simple reply、list reply、hand off、close session。

**Comment by xiaoyunwu** [comment]
eventually, this seems reasonable.
