### ISSUE TITLE
[Feature Request]: Display runtime error instead of internal service error

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now, if we run into a runtime error, we get an internal error on the try it now, there is a internal error, I think we need to give it the same treatment as the code gen error for now. (Improve the builder experience via LSP and deep learning based code generation is the long term goal), 

### Motivation

So that is possible for other enlighten builder to quickly figure out what is the problem. It should only be displayed on the try it now. 

### Describe alternatives you've considered

n/a

**Comment by xiaoyunwu** [comment]
@jfang137 If we capture the stack, how do we send it to you? How do you know it is Internal error for now?

**Comment by jfang137** [comment]
现在正常被捕获的错误现在都会抛给前端，internal system err  一般是go的一些代码问题导致的，这个就需要发现并完善对应的代码，把它改成可以被正常抛出的错误

**Comment by jfang137** [comment]
slot type 未找到的错误能被正常抛出来了

**Comment by jfang137** [comment]
@yigexu @hisunnymay  刚刚改了一下后端的compile 缓存实例，可以先看看还会不会稳定复现问题
