### ISSUE TITLE
[Bug]: Incorrect display of hint in INTERACTION layer

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

目前涉及 entry 的部分，在 INTERACTION layer 显示的内容是 EN layer 的 hint

1. Multiple Value Message

![image](https://user-images.githubusercontent.com/95261974/224647479-2e3627f0-06f7-4579-889d-189553c87e52.png)

2. Value recommendation

![image](https://user-images.githubusercontent.com/95261974/224646837-f63a9ca3-898f-4526-bbb7-26ad6384f839.png)

### Expected Behavior

应该和其他的 lanugage 的部分显示一样，统一用同一个文案，比如：
> This part is language related content, you can modify it by switching to the language layer.

### Use Case

/

### Steps To Reproduce

1. 进入 [hint_0313](https://build.opencui.io/org/me.test/agent/hint_0313/struct/intent/640edd4258a649b8fde25b9f/slot/640edfbf58a649b8fde26442) 
2. 点击 Value Recommendation，可以查看该部分的 hint
3. 返回到 Skill 页面
4. 切换到 Response，在 Default action 中添加 Multiple Value Message，可以看到该部分的 hint

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.test/agent/hint_0313/struct/intent/640edd4258a649b8fde25b9f/slot/640edfbf58a649b8fde26442

**Comment by hisunnymay** [comment]
Value Rec 的改过来了， @jfang137 Multiple Value Message 这个也需要改一下

![image](https://user-images.githubusercontent.com/95261974/225248332-215fd4b5-7a27-463b-a5a0-69ff6ba3b1c0.png)

**Comment by hisunnymay** [comment]
@jfang137 不好意思，我刚看到 [Multi-Valued Confirmation](https://build.opencui.io/org/me.test/agent/hint_0313/struct/intent/640edd4258a649b8fde25b9f/slot/640edfbf58a649b8fde26442) 里面也有 Display，这里的 Body 也需要麻烦修改一下

![image](https://user-images.githubusercontent.com/95261974/225491773-8163ac56-fee0-4ecd-ac42-51087b10b95a.png)

**Comment by jfang137** [comment]
> @jfang137 不好意思，我刚看到 [Multi-Valued Confirmation](https://build.opencui.io/org/me.test/agent/hint_0313/struct/intent/640edd4258a649b8fde25b9f/slot/640edfbf58a649b8fde26442) 里面也有 Display，这里的 Body 也需要麻烦修改一下
> 
> ![image](https://user-images.githubusercontent.com/95261974/225491773-8163ac56-fee0-4ecd-ac42-51087b10b95a.png)

我的问题，代码加错地方了

**Comment by hisunnymay** [comment]
Checked, it's fixed.

1. mv confirmation

![image](https://user-images.githubusercontent.com/95261974/225788825-5fb58e61-8580-4588-9a06-2f424919f3fd.png)

2. value rec

![image](https://user-images.githubusercontent.com/95261974/225788882-c3555f3c-c3ae-4b3d-a712-67a8ab492de8.png)

3. multiple value message

![image](https://user-images.githubusercontent.com/95261974/225788925-08316e36-ea5a-4905-a895-c0f4d1dd0119.png)
