### ISSUE TITLE
[Feature Request]: hide assisted mode

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hide assisted mode on the platform

### Motivation

Code expression has many potential advantages:
1. potentially code generation from natural text description of goal.
2. arbitrary 
3. lsp support. 

### Describe alternatives you've considered

by hiding the assisted mode, it will force us to focus on how to code expression to work well.

**Comment by XiaoboYuan** [comment]
@xiaoyunwu 
code expression有一个很大的问题是没办法知道这个expression最后的结果的type
这将导致一些问题比如无法在vr的body或是list response body里面知道list item的type，从而没办法auto complete
当然如果对LSP related feature的预期是可以计算出code expression的type，那就没问题，如果只是像现在这样的字符串层面的auto complete，那可能会造成问题

**Comment by Zeng666666** [comment]
@xiaoyunwu https://naturali-io.feishu.cn/docs/doccnsfoT0L68Tid51mIflWk7mh#

**Comment by jfang137** [comment]
隐藏了以后前端交互上没法再兼容旧数据，会将旧的function invocation mode的数据都变成code expression mode且code 为空，需要填写code才能有正确的runtime表现 @XiaoboYuan @Zeng666666

**Comment by jfang137** [comment]
原有的code expression不受影响

**Comment by Zeng666666** [comment]
cc @hisunnymay  @yigexu
