### ISSUE TITLE
[Bug]: There is no way to remove library when switching from Types page at EN layer to Dependencies page

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

从 Types 页面的 EN layer 切换到 Dependencies 页面之后，没有能对 library 进行操作的选项

![image](https://user-images.githubusercontent.com/95261974/226501325-f787afc0-bf91-40ca-9f52-5f15cce9ed0e.png)

### Expected Behavior

从 Types 页面的 EN layer 切换到 Dependencies 页面之后，有对 library 进行操作的选项

- 下图是从 Types 页面的 INTERACTION layer 切换到 Dependencies 页面的截图

![image](https://user-images.githubusercontent.com/95261974/226501265-e66f10e0-1c1c-4318-a4e9-895a3ee90f2e.png)

### Use Case

/

### Steps To Reproduce

1. 点击进入 https://build.opencui.io/org/me.test/agent/t_slotUpdate_0310/en/library
2. 将鼠标放置在任意一个 library 上，没有显示 "..."

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.test/agent/t_slotUpdate_0310/en/library

**Comment by jfang137** [comment]
@hisunnymay  language layer本来就不允许操作import的， @Zeng666666 昨天是刚说过移除imported page的layer switch对吗

**Comment by Zeng666666** [comment]
@jfang137 是的，移除 switch lang 那条功能栏

@hisunnymay 你现在提的是一个不存在的问题。本身 lang 也不允许操作的。

**Comment by jfang137** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/16040960/226502837-5fb81355-933b-4ad5-b392-8852228df8b6.png">

**Comment by hisunnymay** [comment]
@Zeng666666 @jfang137 你们认为现在的表现是预期的表现吗？

我理解的预期是：目前在 Dependencies 页面应该允许 update 或者 remove 操作，不论之前 Types 页面是在 EN layer 还是在 INTERACTION layer。

我对移除 swich lang 的理解是：Dependencies Tab 的操作和在哪一个 layer 无关了，builder 只要在 Dependencies 页面，就能对导入的 library 进行操作

**Comment by jfang137** [comment]
产品方面有分歧的话你们可以再讨论讨论。有结论了给我最新方案我再改，这应该不算是一个bug

**Comment by Zeng666666** [comment]
dependencies 应当只有一个页面，不应该再切换 struct/lang 了，始终在这个页面上 update/remove，这里是不是 url 没有改过来？

**Comment by jfang137** [comment]
@xiaoyunwu @Zeng666666 隐藏了switch不代表我们的数据没有layer了， language layer的数据是不能被操作的，它是integration propagate过来的，所以你们是要在进入这个页面自动切换到integration layer上吗？

**Comment by Zeng666666** [comment]
@jfang137 之前 imported 在顶栏的时候，是永远展示 integration layer 吗？
![img_v2_1867095d-84b4-454c-af4f-751608ade83g](https://user-images.githubusercontent.com/37056884/226509996-09962672-541a-40f2-bc5e-fedd8a437c8e.jpg)

**Comment by jfang137** [comment]
@Zeng666666 我不记得之前有这种改动，你的意思是即使是lang layer，这个页面也只展示和操作integration layer的数据？

**Comment by Zeng666666** [comment]
@jfang137 给 builder 展示的 dependencies 页面，应当始终只有一个页面，builder 在这个页面上进行 update/remove 操作。如果这个页面对于你来说是 integration layer，那应该就是始终展示 integration layer。builder 的实际操作，比如 propagate 和 commit 是在 type tab 进行的，platform 希望这部分从 builder 视角是和 dependencies tab 无关的。也就是说无论 builder 在 dependencies 做了什么，他都需要回到 type tab 进行 propagate。

**Comment by jfang137** [comment]
好的我改一下，你们看看效果对不对

**Comment by Zeng666666** [comment]
好的

**Comment by jfang137** [comment]
@Zeng666666 @hisunnymay 改好发了

**Comment by hisunnymay** [comment]
Checked, it's fixed

![image](https://user-images.githubusercontent.com/95261974/226514541-ee8c7a7f-a6ea-477c-b115-6193c43f5bee.png)
