### ISSUE TITLE
[Bug]: SEP 引用 ${movie!!.normalized()}，try it now 会报错 "Internal Server Error"

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 如果 SEP Prompt 定义了：${movie!!.normalized()}；try it now 时，轮到该 slot 时会报 "Internal Server Error"

![image](https://user-images.githubusercontent.com/37056884/158009975-0154078b-36ce-4c4e-b3d6-ed442a7e2a9c.png)

![image](https://user-images.githubusercontent.com/37056884/158007315-d3cb2ae8-a77a-4958-808c-08703083b5b8.png)

2. 如果 SEP 不定义引用，就不会报错（这里定义的是 explicit SEP）：

![image](https://user-images.githubusercontent.com/37056884/158008267-30326139-7f0b-4639-8bb0-e724a13d48a5.png)

### Expected Behavior

- SEP 应当允许引用参数，因为 builder 也不知道是什么情况下是 SEP 以及 SEP 时的 value 是什么，因此 builder 需要引用参数，告诉 end-user 这个唯一的选项是什么。

- SEP 本质是 confirmation，此时 value 已经是 candidate value 了，应当是可以使用 ${movie!!.normalized()} 进行引用的。

### Use Case

/

### Steps To Reproduce

复现 query：
- qwer
- 1

### Label of org.project

test001.test_zep

### Framely Link

https://framely.naturali.io/org/621d809561f0057d035f6437/agent/622adde22fb46d1befee2232/intent/622addfa2fb46d1befee223a/slot/622addff2fb46d1befee223e

**Comment by hisunnymay** [comment]
@Zeng666666 把${movie!!.normalized()}换成${it.normalized()}试试呢？

**Comment by Zeng666666** [comment]
可以了。那这里为什么是 ${it.normalized()} ？而不是 ${movie!!.normalized()} 呢？

**Comment by hisunnymay** [comment]
可能是因为要VR结束之后，才会把值填入slot中，填入之后才能饮用

**Comment by Zeng666666** [comment]
好的
