### ISSUE TITLE
[Bug]: Failed to add a deploy service provider when there is "en" in the url

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 Settings - Integration 页面，当 url 中包含 “**en**” 时， 无法添加 deploy service provider

- 补充：当 url 中包含 “**struct**” 时， 可以成功添加 deploy service provider

https://user-images.githubusercontent.com/95261974/227445574-2121f489-7596-49db-a8a3-e32dbaf27217.mp4

### Expected Behavior

无论 url 中包含的是 en 还是 struct，只要在 Settings - Integration 页面就应该可以添加 service provider

分析和 [[Bug]: There is no way to remove library when switching from Types page at EN layer to Dependencies page](https://github.com/framely/community/issues/896#top) 类似

### Use Case

/

### Steps To Reproduce

1. 点击进入 [addProvider_0324](https://build.opencui.io/org/me.test/agent/addProvider_0324/en/setting?tab=integration)
2. 点击 select service，选择任意一个 provider  后填写任意信息，点击 Save，可以看到 service provider 添加失败

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.test/agent/addProvider_0324/en/setting?tab=integration

**Comment by Zeng666666** [comment]
单版本的操作，如 version、settings，URL 中是不是不应该有 struct 或 en？

**Comment by jfang137** [comment]
不行，靠url记录layer的，不然切回types就得没有layer信息了，只能重置到struct

**Comment by jfang137** [comment]
再试试 @hisunnymay

**Comment by hisunnymay** [comment]
Checked, it's fixed


https://user-images.githubusercontent.com/95261974/227458933-ff8bbe07-0512-4b4e-9577-eae690a238e2.mp4
