### ISSUE TITLE
[Bug]: can not import module

### ISSUE THREAD

**Issue by Zeng666666** [framely/community#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 [io.opencui.components](https://build.opencui.io/org/io.opencui/agent/components/struct/type?page=0&imported=false&search=&category=ALL) 中点击 import，选择 test001.testImport 后点击 save 后，页面没有操作成功的提示：

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/37056884/227451116-fc01fc70-9216-4df8-ba0a-a5821bde8579.png">

回到目标 chatbot 也没有导入进来

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/37056884/227451839-8f046e5e-e655-4059-aefb-1b800025500d.png">

### Expected Behavior

应当可以正常导入，且有导入成功的提示

### Use Case

/

### Steps To Reproduce

可以将 https://build.opencui.io/org/io.opencui/agent/components/struct/type?page=0&imported=false&search=&category=ALL 导入任何 project，目前点击 save 后，页面没有任何动静，目标 project 中也没有出现这个 module

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/io.opencui/agent/components/struct/type?page=0&imported=false&search=&category=ALL

**Comment by jfang137** [comment]
@Zeng666666 再试试

**Comment by jfang137** [comment]
刷新一下前端

**Comment by Zeng666666** [comment]
可以了现在
