### ISSUE TITLE
[Feature Request]: kotlin String should not be CUI slot type 

### ISSUE THREAD

**Issue by xiaoyunwu** [framely/community#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

kotlin.String should not be used as CUI slot type, since it is a low level storage type. There are two kind of constraints we can add.
1. prevent string as slot type. (easy to do, but might be too restrictive)
2. prevent string slot type from any form of asking. (might need some explanation). 

For now, let's just do #1, String should NOT be used as slot type. We can change to #2 if there are strong case for it. 

### Motivation

String type has not meaning at the CUI level, so we should not used it as CUI slot type. 

### Describe alternatives you've considered

N/A

**Comment by jfang137** [comment]
@xiaoyunwu 当frame对应provider中的table时，包含string type的column似乎是一个比较常见的情况， string type column不是对应 frame中的string slot type么。我们确定要加这种限制吗？ @yigexu @Zeng666666

**Comment by yigexu** [comment]
CUI slot type 是不是没有开启 storage annotation enable 的 frame 下的 slot？

**Comment by jfang137** [comment]
添加slot 操作可以发生在开启storage annotation enable 之前

**Comment by Zeng666666** [comment]
string type 不能有 CUI 行为，应该是找一种方式可以做这样的限制。不知道不能成为 slot 会不会有点强？有没有什么是需要 string 的场景 @yigexu ?

**Comment by yigexu** [comment]
@jfang137 我还没理解到能讨论方案的程度；

@xiaoyunwu 我想先确认一下什么是CUI slot type。
有很多方式去定义它：
1. 没有开启 storage enabled 的 frame 中的 slot
2. 除了只在 provider frame 中出现过的slot
3. 1、2 的某种 hybrid
4. 还是说，没有一个对应到 platform 上的静态定义，而是看 user 会不会与和这个 slot 对话。（换句话说，概念上或者DU认为说 string 没有意义）

因为我理解 service类型的library 在当作 service 看时，算是非 CUI level，但是当作 library 看时算作 CUI level，所以我这里存在一个即算是 CUI 又不算的状态。

**Comment by jfang137** [comment]
provider 中的frame即使没有开启storage enable, 不创建table，也可能会生成composite type，这个frame的slot 
 type应不应当算作CUI slot type. @xiaoyunwu

**Comment by yigexu** [comment]
@xiaoyunwu 另外，我这边存在 never ask slot，存的是 db 拿来的 image url 的情况，我感觉更适合 <2>。不过我们也可以考虑 java url。我是首先向明确你对 CUI slot type 的定义。

**Comment by jfang137** [comment]
@xiaoyunwu 如果string slot不允许为never ask，那么它默认是always ask或是什么?

**Comment by yigexu** [comment]
我理解这个规则是：平台可以选string，但是选了的slot，1- askstrategy只能是neverask，2-在expression$$时为不可选状态
@Zeng666666 @jfang137 如果是这样，我这边的场景没什么问题；看看有没有什么其他场景，和逻辑上的问题

**Comment by Zeng666666** [comment]
在expression $ 引用时，如果能不出现是最好的，就是不让 builder 看见。因为如果 builder 能看到但不能选，就会产生疑问。其他的我没有问题。

**Comment by jfang137** [comment]
ok，我也没什么问题了

**Comment by xiaoyunwu** [comment]
string slot  can only be never ask. A slot is considered as not CUI slot if
: 1. never ask. 2. not in expression or basically we do not provide
interact for it. @Yi Fang ***@***.***>

**Comment by jfang137** [comment]
了解，开始搞反了

**Comment by xiaoyunwu** [comment]
cool.

**Comment by Zeng666666** [comment]
哦，那 slot 是 string type 的，应该是所有 CUI 相关的定义都不能定义

**Comment by xiaoyunwu** [comment]
not CUI slot:
1. never ask.
2. not in expression
or basically we do not provide interact for it.

**Comment by xiaoyunwu** [comment]
the other choice is to force String slot to be never ask. And make sure it
can not appear in the expression.
