### ISSUE TITLE
[Bug]: connect error

### ISSUE THREAD

**Issue by yigexu** [framely/community#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

输入：i want to order some food，first 
实际表现：问side dish
预期表现：问想要什么面，有 dry noodle，soup noodle
相关分析：
1. 我比较怀疑是 state update condition 没有被触发；因为我额外设置了一个 condition = true 的条件，也没看到被触发；但是如果弄一个demo bot，condition是正常的
2. 不排除是我的问题

<img width="250" alt="Screen Shot 2022-03-14 at 3 17 11 PM" src="https://user-images.githubusercontent.com/6505755/158123129-650ffde9-d8c5-4a3b-aba0-bb79124760d5.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

restaurant002 /restaurantC214 

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b808ff5c77cdfc256ce6/test_case

### Test Case

test0314

**Comment by XiaoboYuan** [comment]
fixed

**Comment by yigexu** [comment]
@hisunnymay

**Comment by yigexu** [comment]
@XiaoboYuan 这个最后是 never ask + state update condition 吗，还是因为什么其他的原因？
