### ISSUE TITLE
[Bug]: cannot add frame as slot

### ISSUE THREAD

**Issue by yigexu** [framely/community#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题是没办法把frame设置intent的一个slot
https://user-images.githubusercontent.com/6505755/158314352-9fee8c50-5ca0-4152-be9f-0b6161d5cb3b.mov

我现在唯一怀疑可能是我的问题在于，也许红色部分陷入了什么循环检查？

<img width="1790" alt="Screen Shot 2022-03-15 at 1 43 12 PM" src="https://user-images.githubusercontent.com/6505755/158314443-781838a2-16af-4001-a8dd-f59240f6d240.png">

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/622019f92b38932409a18edd/frame/6230252c0171eb6ab6d23390

**Comment by yigexu** [comment]
@jfang137 重新进入org后可以添加，应该和缓存相关。
我目前能绕过去了，这个不着急处理了。

**Comment by jfang137** [comment]
我试了下没有复现，你那里再复现的话麻烦看一下console或是network有什么抛错没有

**Comment by yigexu** [comment]
都没有。
复现的方式是：你进入bot，创建一个frame，然后进入随便一个intent，在intent的slot中去添加那个 frame。
没有复现可能是因为你从链接进的，所以可能缓存被刷了？

**Comment by jfang137** [comment]
修复了一下
