### ISSUE TITLE
[Bug]: Failed to execute 'setItem' on 'Storage': Setting the value of 'dhlCache' exceeded the quota.

### ISSUE THREAD

**Issue by yigexu** [framely/community#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 我今天见到好几次这个错误
2. 暂时找不到复现的路径，能找到的规律是“当从 struct 切换到 lang 后”，应该和哪个 bot 无关
3. network 和 console 看起来都很正常

先留个记录，如果再遇到补充

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

/

### Framely Link

https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b6d1ff5c77cdfc255d0f/intent/61f0b1826a5313c74a2df848?tab=1

**Comment by jfang137** [comment]
这个是我们缓存的数据量过大导致的，我还在找方案解决

**Comment by jfang137** [comment]
暂时移除一部分缓存看看有什么影响

**Comment by yigexu** [comment]
我需要一些时间观察一下这个
